### ISSUE TITLE
Avahi-daemon needs to be restarted often. 

### ISSUE THREAD

**Issue by davegarnett** [mikebrady/shairport-sync#598] opened 2017-10-04 15:47 UTC
I have a Raspberry Pi 3b with hifiberry DAC+ running Shairpory-Sync. 
Firstly thanks for this build you have made my 30 year old B&O sound system into the modern age.

Ok so I have a random problem with the avahi-daemon and didn’t know whether it is caused by shairport-sync or not. 

So if I don’t manually disconnect from the airplay device next time I try to connect I cannot see the device to connect. 
A reboot doesn’t even fix this, only way to make it visisble again is to restart the avahi-daemon service. 

Any help would be great. 
Thanks,
Dave

**Comment by mikebrady** [comment] 2017-10-04 18:25
Thanks Dave. Not sure what the problem with the `avahi-daemon` is, TBH. Is there anything in the logs? If not, I wonder (i.e. I don’t actually know how to) if the `avahi-daemon` can be made to log verbosely; it might give some kind of clue about the cause.

**Comment by davegarnett** [comment] 2017-10-12 04:16
Hi Mike. Thanks for the speedy reply.

OK I'm going to start with facts. 
My perceived problem was not my actual problem
My AirPlay **Beocenter** speaker  is sometimes not visible, but `shairport-sync` is always running.
I have to  `sudo systemctl restart avahi-daemon` and then I am able to connect.
The cause of the issue is not a disconnection issue. (tried replicating far too many times this week).
Today it finally happened again after a reboot.

So I did  `sudo systemctl status avahi-daemon -l` and this is what it spit out. 

`Joining mDNS multicast group on interface eth0.IPv4 with address 192.168.1.7.`
`New relevant interface eth0.IPv4 for mDNS.`
`Registering new address record for 192.168.1.7 on eth0.IPv4.`
`Joining mDNS multicast group on interface eth0.IPv6 with address fe81::876:8f88:4705:7ffd.`
`New relevant interface eth0.IPv6 for mDNS.`
`Registering new address record for fe81::876:8f88:4706:7ffd on eth0.*.`
`Leaving mDNS multicast group on interface eth0.IPv6 with address fe81::876:8f88:4705:7ffd.`
`Joining mDNS multicast group on interface eth0.IPv6 with address 2606:a010:4dcc:5600:294b:87e5:bae5:1ea0.`
`Registering new address record for 2606:a010:4dcc:5600:294b:87e5:bae5:1ea0 on eth0.*.`
`Withdrawing address record for fe81::876:8f88:4706:7ffd on eth0.`

So then I thought maybe it's after I reboot I have the problem (I set up a weekly crontab that updates my repos and packages automatically then reboots). 
I restarted `avahi-daemon` and made sure the connection worked then I rebooted the pi and sure enough I could not find my **Beocenter**.

I tried `sudo nano /etc/avahi/avahi-daemon.conf` and cuncommenting `deny-interfaces=eth1`.
Next I `sudo apt-get purge avahi-daemon` then reinstalled `avahi-daemon`. 
I'm really struggling here to find the solution. Any ideas.

**Comment by mikebrady** [comment] 2017-10-12 06:33
Thanks for the update. I have a suspicion that the problem might be caused by your RPi acquiring a global IPv6 address. Can you prevent that from happening, i.e. can you set some kind of flag to prevent the RPi acquiring a globally routeable IPv6 address and see what happens?

**Comment by youpiyo** [comment] 2017-10-24 11:43
I had the same issue with my raspbian.
A firmware update made the RPI not to work. I had to reinstall and it solved the solution for me.

**Comment by davegarnett** [comment] 2017-10-31 15:43
So I `sudo nano /etc/sysctl.conf`
and added the lines 
`net.ipv6.conf.all.disable_ipv6 = 1`
`net.ipv6.conf.default.disable_ipv6 = 1`
`net.ipv6.conf.lo.disable_ipv6 = 1`
saved and rebooted.
After the reboot the issue persisted, but a little bit flaky.
So it will start up every 1 in 5 times I reboot.

After a bit more research I wonder whether having a static IP may make a difference?

**Comment by mikebrady** [comment] 2017-10-31 21:36
Thanks. It would be worth doing an `$ ifconfig` for those situations that do and that don't work, I guess. I can't see how a static IP would help, to be honest. No harm in trying though.

**Comment by echtelerp** [comment] 2017-12-06 16:31
I seem to have the exact same Issue on my PI 3. 
can I support you with logs or stuff like this?

**Comment by mikebrady** [comment] 2019-10-24 10:27
Closing the issue. Please open a new one if necessary.

**Closed by mikebrady** 2019-10-24 10:27 UTC
