### ISSUE TITLE
Works from IOS, not from OS X [Solved]

### ISSUE THREAD

**Issue by jief666** [mikebrady/shairport-sync#416] opened 2016-11-09 15:26 UTC
Hi,

I've compiled for ARM, for Ubuntu and for OS X. All have the same problem : it works from IOS 8.1.2 (iphone 5S) and 8.4 (iphone 4S), but not from OS X.
On ubuntu, I tried stdout backend and then listen to it to be sure it wasn't a sound card problem. It's not.
If you want to hear, here is the generated file. No header so have to be played with aplay -f cd test.wav
[test.wav.zip](https://github.com/mikebrady/shairport-sync/files/581122/test.wav.zip)

Any idea ?

Regards.

**Comment by mikebrady** [comment] 2016-11-09 17:47
Thanks for the post. Shairport Sync definitely works with iTunes n OS X and it also works as a sound output device. From what you've said, the problem is associated with OS X only.

So, a few questions:
What do you mean "from OS X"? Do you mean for iTunes or something else? What version of OS X? Do you have a firewall running? 
Do you have a firewall running on OS X?
Is OS X running over wired ethernet to a router that is also a wireless access point?
How is Shairport Sync connected – is it over Ethernet or WiFi?

You can turn on logging on Shairport Sync to see what it might be reporting.

**Comment by jief666** [comment] 2016-11-09 18:01
There is no report from Shairport-sync for that sound.
The MacPro used for test and compilation is wired to the provider router
(SwissCom). The wifi access point (open-wrt) is separated on bridge mode.
So only one network exist : 192.168.3.x
Shairport-Sync on the MacPro, so it's wired.
Firewall is on provider router.
All my OS X are Yosemite (MacPro and Laptop).
I have a lot of "Buffers exhausted".

**Comment by mikebrady** [comment] 2016-11-09 18:59
Thanks. Just to be clear, I'm assuming that you have compiled Shairport Sync onto the Mac Pro itself and the Mac Pro is wired to one port of the provider router with the OpenWrt box wired wired to another port on the provider router.

So, is it true that the iPhones can play music onto the Shairport Sync running on the Mac Pro?

**Comment by jief666** [comment] 2016-11-09 21:28
Absolutely, iphones can.
I did a test I should have done before opening the issue. I have a "real"
airport express. The laptop sound the same on the airport as
Sahirport-sync. Most likely the problem is the laptop, not shairport !
Sorry, I forgot to do that test ;-)

**Comment by jief666** [comment] 2016-11-09 22:47
Well, I really embarassed myself with this issue. I didn't think about playing sound from other than VLC. If I had clicked on the preview of a mp3 in the Finder, it would have been enough to know that OS X, my laptop and the network wasn't the problem. I just had to change to "Network Caching (ms)" preferences in VLC and everything is working now : Iphones, laptop, Itunes, VLC...
Great,
Sorry.

**Comment by mikebrady** [comment] 2016-11-10 09:19
I'm glad that three was a good outcome, and I didn't know about that VLC thing.

**Comment by jief666** [comment] 2016-11-10 09:22
Maybe you can change the title by Doesn't work from VLC. :-)

**Comment by mikebrady** [comment] 2016-11-10 09:28
Done.

**Comment by mikebrady** [comment] 2019-10-15 15:11
Closing the issue. Thanks for your contribution. Please open a new issue if necessary.

**Closed by mikebrady** 2019-10-15 15:11 UTC
