### ISSUE TITLE
Unable to play using Twist on Android

### ISSUE THREAD

**Issue by sticilface** [mikebrady/shairport-sync#492] opened 2017-03-13 09:44 UTC
Using version 3.0.2
  
When I try to connect I get an immediate disconnect on the android device.   working fine streaming from iTunes and and iPhone.  Is this likely to be a Twist app error?  the only thing is that is seems to work fine streaming to earlier versions of shairport that are running on Moode Players I have around the house which use 2.9.1 development version. 

Here is the shairport-sync log
```
Mar 13 09:37:25 rPi3 shairport-sync[8114]: one thread joined...
Mar 13 09:37:25 rPi3 shairport-sync[8114]: New RTSP connection from 192.168.1.182:40566 to self at 192.168.1.245:5000.
Mar 13 09:37:25 rPi3 shairport-sync[8114]: CSeq: 1.
Mar 13 09:37:25 rPi3 shairport-sync[8114]: User-Agent: iTunes/11.0.4 (Macintosh; OS X 10.8.4) AppleWebKit/536.30.1.
Mar 13 09:37:25 rPi3 shairport-sync[8114]: Client-Instance: 6E97129790C24FEE.
Mar 13 09:37:25 rPi3 shairport-sync[8114]: Apple-Challenge: ssMxXwfaPDrXr1ByuIwPuw.
Mar 13 09:37:25 rPi3 shairport-sync[8114]: RTSP Packet received of type "OPTIONS":
Mar 13 09:37:25 rPi3 shairport-sync[8114]: Type: "CSeq", content: "1"
Mar 13 09:37:25 rPi3 shairport-sync[8114]: Type: "User-Agent", content: "iTunes/11.0.4 (Macintosh; OS X 10.8.4) AppleWebKit/536.30.1"
Mar 13 09:37:25 rPi3 shairport-sync[8114]: Type: "Client-Instance", content: "6E97129790C24FEE"
Mar 13 09:37:25 rPi3 shairport-sync[8114]: Type: "Apple-Challenge", content: "ssMxXwfaPDrXr1ByuIwPuw"
Mar 13 09:37:25 rPi3 shairport-sync[8114]: RTSP Response:
Mar 13 09:37:25 rPi3 shairport-sync[8114]: Type: "Apple-Response", content: "ukKm8DqgAwy7kknMKOOcxCOTx/DNKX/SbmSbnvucvw9B3GmkDxNj1p/cgOnh/mtuxqi++WpnckFxyWTTHX/UtxEOH4/kKPczmIUHUiAuHoux9YT77ydt1xZamw7HvzKtNK7010dEvS48F0RQAH6yr/cfUnQaMMRca2e88eMc8xjKB5Z72fsYCFcbsPNuyiEO8ym8O/OSu7ssExxarvt3vwgbejO7blybQeZK2yT3xmT8B4AAFY/3YHwWDENsIIpH+FQ73cuiX8L2AoaQG09x67sInIaO9KsIBYZLfUkaatZADkEylHHeC8NoVN8+L2VHoW+RmXln05mMMtmj+r4w6Q"
Mar 13 09:37:25 rPi3 shairport-sync[8114]: Type: "CSeq", content: "1"
Mar 13 09:37:25 rPi3 shairport-sync[8114]: Type: "Server", content: "AirTunes/105.1"
Mar 13 09:37:25 rPi3 shairport-sync[8114]: Type: "Public", content: "ANNOUNCE, SETUP, RECORD, PAUSE, FLUSH, TEARDOWN, OPTIONS, GET_PARAMETER, SET_PARAMETER"
Mar 13 09:37:25 rPi3 shairport-sync[8114]: CSeq: 2.
Mar 13 09:37:25 rPi3 shairport-sync[8114]: Content-Type: application/sdp.
Mar 13 09:37:25 rPi3 shairport-sync[8114]: Content-Length: 572.
Mar 13 09:37:25 rPi3 shairport-sync[8114]: User-Agent: iTunes/11.0.4 (Macintosh; OS X 10.8.4) AppleWebKit/536.30.1.
Mar 13 09:37:25 rPi3 shairport-sync[8114]: Client-Instance: 6E97129790C24FEE.
Mar 13 09:37:25 rPi3 shairport-sync[8114]: RTSP Packet received of type "ANNOUNCE":
Mar 13 09:37:25 rPi3 shairport-sync[8114]: Type: "CSeq", content: "2"
Mar 13 09:37:25 rPi3 shairport-sync[8114]: Type: "Content-Type", content: "application/sdp"
Mar 13 09:37:25 rPi3 shairport-sync[8114]: Type: "Content-Length", content: "572"
Mar 13 09:37:25 rPi3 shairport-sync[8114]: Type: "User-Agent", content: "iTunes/11.0.4 (Macintosh; OS X 10.8.4) AppleWebKit/536.30.1"
Mar 13 09:37:25 rPi3 shairport-sync[8114]: Type: "Client-Instance", content: "6E97129790C24FEE"
Mar 13 09:37:25 rPi3 shairport-sync[8114]: Play connection from user agent "iTunes/11.0.4 (Macintosh; OS X 10.8.4) AppleWebKit/536.30.1".
Mar 13 09:37:25 rPi3 shairport-sync[8114]: RTSP Response:
Mar 13 09:37:25 rPi3 shairport-sync[8114]: Type: "CSeq", content: "2"
Mar 13 09:37:25 rPi3 shairport-sync[8114]: Type: "Server", content: "AirTunes/105.1"
Mar 13 09:37:25 rPi3 shairport-sync[8114]: CSeq: 3.
Mar 13 09:37:25 rPi3 shairport-sync[8114]: Transport: RTP/AVP/UDP;unicast;interleaved=0-1;mode=record;control_port=6001;timing_port=6002.
Mar 13 09:37:25 rPi3 shairport-sync[8114]: User-Agent: iTunes/11.0.4 (Macintosh; OS X 10.8.4) AppleWebKit/536.30.1.
Mar 13 09:37:25 rPi3 shairport-sync[8114]: Client-Instance: 6E97129790C24FEE.
Mar 13 09:37:25 rPi3 shairport-sync[8114]: RTSP Packet received of type "SETUP":
Mar 13 09:37:25 rPi3 shairport-sync[8114]: Type: "CSeq", content: "3"
Mar 13 09:37:25 rPi3 shairport-sync[8114]: Type: "Transport", content: "RTP/AVP/UDP;unicast;interleaved=0-1;mode=record;control_port=6001;timing_port=6002"
Mar 13 09:37:25 rPi3 shairport-sync[8114]: Type: "User-Agent", content: "iTunes/11.0.4 (Macintosh; OS X 10.8.4) AppleWebKit/536.30.1"
Mar 13 09:37:25 rPi3 shairport-sync[8114]: Type: "Client-Instance", content: "6E97129790C24FEE"
Mar 13 09:37:25 rPi3 shairport-sync[8114]: User-Agent is iTunes 10 or better, (actual version is 11); selecting the iTunes latency of 11 frames.
Mar 13 09:37:25 rPi3 shairport-sync[8114]: rtp_setup: cport=6001 tport=6002.
Mar 13 09:37:25 rPi3 shairport-sync[8114]: Set up play connection from 192.168.1.182 to self at 192.168.1.245.
Mar 13 09:37:25 rPi3 shairport-sync[8114]: listening for audio, control and timing on ports 6001, 6002, 6003.
Mar 13 09:37:25 rPi3 shairport-sync[8114]: RTSP Response:
Mar 13 09:37:25 rPi3 shairport-sync[8114]: Type: "CSeq", content: "3"
Mar 13 09:37:25 rPi3 shairport-sync[8114]: Type: "Server", content: "AirTunes/105.1"
Mar 13 09:37:25 rPi3 shairport-sync[8114]: Type: "Transport", content: "RTP/AVP/UDP;unicast;interleaved=0-1;mode=record;control_port=6002;timing_port=6003;server_port=6001"
Mar 13 09:37:25 rPi3 shairport-sync[8114]: Type: "Session", content: "1"
Mar 13 09:37:25 rPi3 shairport-sync[8114]: Output sample ratio is 1.
Mar 13 09:37:25 rPi3 shairport-sync[8114]: Output frame bytes is 4.
Mar 13 09:37:25 rPi3 shairport-sync[8114]: Audio receiver -- Server RTP thread starting.
Mar 13 09:37:25 rPi3 shairport-sync[8114]: Control receiver -- Server RTP thread starting.
Mar 13 09:37:25 rPi3 shairport-sync[8114]: Timing receiver -- Server RTP thread starting.
Mar 13 09:37:25 rPi3 shairport-sync[8114]: Output bit depth is 16.
Mar 13 09:37:25 rPi3 shairport-sync[8114]: Dithering will be enabled the output volume is being altered in software
Mar 13 09:37:25 rPi3 shairport-sync[8114]: Timing sender thread starting.
Mar 13 09:37:25 rPi3 shairport-sync[8114]: RTSP connection closed.
Mar 13 09:37:25 rPi3 shairport-sync[8114]: Closing down RTSP conversation thread...
Mar 13 09:37:25 rPi3 shairport-sync[8114]: % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Mar 13 09:37:25 rPi3 shairport-sync[8114]: Dload  Upload   Total   Spent    Left  Speed
Mar 13 09:37:25 rPi3 shairport-sync[8114]: 0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0Shut down audio, control and timing threads
Mar 13 09:37:25 rPi3 shairport-sync[8114]: Audio receiver -- Server RTP thread interrupted. terminating.
Mar 13 09:37:25 rPi3 shairport-sync[8114]: Control RTP thread interrupted. terminating.
Mar 13 09:37:25 rPi3 shairport-sync[8114]: Timing thread interrupted. terminating.
Mar 13 09:37:25 rPi3 shairport-sync[8114]: rtp_timing_sender thread interrupted. terminating.
Mar 13 09:37:25 rPi3 shairport-sync[8114]: Closed and terminated timer requester thread.
Mar 13 09:37:25 rPi3 shairport-sync[8114]: Timing RTP thread terminated.
Mar 13 09:37:25 rPi3 shairport-sync[8114]: timing thread joined
Mar 13 09:37:25 rPi3 shairport-sync[8114]: audio thread joined
Mar 13 09:37:25 rPi3 shairport-sync[8114]: control thread joined
Mar 13 09:37:25 rPi3 shairport-sync[8114]: Player thread exit
Mar 13 09:37:25 rPi3 shairport-sync[8114]: shutting down RTP thread
Mar 13 09:37:25 rPi3 shairport-sync[8114]: RTSP conversation thread terminated.
Mar 13 09:37:25 rPi3 shairport-sync[8114]: 100 69955  100 69955    0     0  1194k      0 --:--:-- --:--:-- --:--:-- 1219k
Mar 13 09:37:26 rPi3 shairport-sync[8114]: % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Mar 13 09:37:26 rPi3 shairport-sync[8114]: Dload  Upload   Total   Spent    Left  Speed
Mar 13 09:37:26 rPi3 shairport-sync[8114]: 0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0#015100  5951  100  5951    0     0  77677      0 --:--:-- --:--:-- --:--:-- 79346
```

**Comment by mikebrady** [comment] 2017-03-13 09:52
Thanks for this. I don't recognise the lines:
```
Mar 13 09:37:26 rPi3 shairport-sync[8114]: % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Mar 13 09:37:26 rPi3 shairport-sync[8114]: Dload  Upload   Total   Spent    Left  Speed
Mar 13 09:37:26 rPi3 shairport-sync[8114]: 0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0#015100  5951  100  5951    0     0  77677      0 --:--:-- --:--:-- --:--:-- 79346
```
What are they?

**Comment by sticilface** [comment] 2017-03-13 09:54
I have no idea!  These lines just come straight from the daemon.log file.

**Comment by mikebrady** [comment] 2017-03-13 09:56
Very strange. Let me look into it.

**Comment by sticilface** [comment] 2017-03-13 09:57
I get the same lines when I play using iTunes on my mac

**Comment by faxm0dem** [comment] 2017-03-13 10:06
Did you try playing some Rock'n'Roll instead?

**Comment by sticilface** [comment] 2017-03-13 10:22
👍 ;)

**Comment by mikebrady** [comment] 2017-03-13 11:05
They look like output from `curl`. What are they doing there, I wonder?

**Comment by sticilface** [comment] 2017-03-13 11:20
It does look like that, i agree.  

if it helps I'm using rPi

**Comment by mikebrady** [comment] 2017-03-13 19:03
Is the app you're talking about "doubleTwist"?

https://play.google.com/store/apps/details?id=com.doubleTwist.androidPlayer&hl=en

**Comment by sticilface** [comment] 2017-03-13 19:06
yes it is.  
I should say that the output that looks like curl, is there when i stream using iTunes, so it is not just that.  And it works on the older version of shairport used in Moode.  Double checked to make sure.

**Comment by mikebrady** [comment] 2017-03-13 19:11
Okay thanks.

**Comment by mikebrady** [comment] 2017-03-13 19:44
So, it seems AirPlay is payware? I've just tried AllConnect and it's working fine on a Nexus 5.

**Comment by lujnan** [comment] 2017-03-14 15:33
Hi,Mike, Maybe the AllConnect or Another app(I forgot the real app name)，it will send a broken announce request header，just `a=fmtp:96`  or the full line like `a=fmtp:96 352 0 16 40 10 14 2 255 0 0 44100`，So I patched some codes for myself to prevent crash.

```
static int rokid_hack_ftmp[12] = { 96, 352, 0, 16, 40, 10, 14, 2, 255, 0, 0, 44100 };
for (i = 0; i < sizeof(conn->stream.fmtp) / sizeof(conn->stream.fmtp[0]);
         i++) {
      if (pfmtp == NULL)
        conn->stream.fmtp[i] = rokid_hack_ftmp[i];
      else
        conn->stream.fmtp[i] = atoi(strsep(&pfmtp, " \t"));
    }
```

**Comment by sticilface** [comment] 2017-03-14 15:46
I will try all connect and see.  It is the gf's phone, not mine, so takes a little longer.

**Comment by mikebrady** [comment] 2017-03-14 15:54
Thanks. AllConnect works fine for me, it's the other one – doubleTwist – that is the problem.

Are you suggesting that the code:

```
    if (!pfmtp) {
      warn("FMTP params missing from the following ANNOUNCE message:");
      // print each line of the request content
      // the problem is that nextline has replace all returns, newlines, etc. by
      // NULLs
      char *cp = req->content;
      int cp_left = req->contentlength;
      while (cp_left > 1) {
        if (strlen(cp) != 0)
          warn("    %s", cp);
        cp += strlen(cp) + 1;
        cp_left -= strlen(cp) + 1;
      }
      goto out;
    }
```
be removed?

**Comment by sticilface** [comment] 2017-03-14 16:11
OK, so all connect does work, but doubleTwist does not!

**Comment by mikebrady** [comment] 2017-03-14 16:33
Thanks for the update.

**Comment by lujnan** [comment] 2017-03-15 09:26
Hi, @mikebrady , I no remove these codes.

`    if (!pfmtp) {
      warn("FMTP params missing from the following ANNOUNCE message:");
      // print each line of the request content
      // the problem is that nextline has replace all returns, newlines, etc. by
      // NULLs
      char *cp = req->content;
      int cp_left = req->contentlength;
      while (cp_left > 1) {
        if (strlen(cp) != 0)
          warn("    %s", cp);
        cp += strlen(cp) + 1;
        cp_left -= strlen(cp) + 1;
      }
      goto out;
    }`

**Comment by mikebrady** [comment] 2017-03-15 14:52
OK, I've just pushed an update with the FLUSH request metadata in place. The code is `flsr`. Also, at log verbosity 1 or greater, it prints out the initial  fmtp data. If you got a chance, would you be kind enough to run it using the `doubleTwist` program and let me see what comes back. (Thanks for this idea, BTW!)

**Comment by sticilface** [comment] 2017-03-15 17:23
i'll let you know.

**Comment by mikebrady** [comment] 2017-03-15 18:43
Many thanks for this. Can you write the full command you are using to call Shairport Sync please? I am still completely mystified by the lines:
```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:–     0
```

**Comment by sticilface** [comment] 2017-03-15 18:49
literally in this case 
`shairport-sync -v`

my uninformed guess is that it is output for some process on the pi.  this is being build on rpi3.

**Comment by mikebrady** [comment] 2017-03-15 18:57
Thanks again. It's really mysterious, because in the original post is was logged as coming from Shairport Sync and in the recent logs it's in there still, in the same place. It looks like it is connected with Shairport Sync.

Would it be possible to log a brief part of the log with `shairport-sync -vvv` please? The interesting part would be around the output:
```
Output bit depth is 16.
Closing down RTSP conversation thread...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0Shut down audio, control and timing threads
Audio receiver -- Server RTP thread interrupted. terminating.
Timing thread interrupted. terminating.
rtp_timing_sender thread interrupted. terminating.
```
just before the `Closing down RTSP conversation thread...` message. If it comes back with the message `RTSP connection closed.`, then it seems to indicate that the sender closed the connection. By the way, what is the sender – is it `doubleTwist`?

**Comment by sticilface** [comment] 2017-03-15 19:08
its defo shairport sync.  the output i posted above it me just starting it from the command line.  so not from a daemon.  What i pasted is direct output.

**Comment by mikebrady** [comment] 2017-03-15 19:20
Thanks. It's really weird.

**Comment by mikebrady** [comment] 2017-03-15 21:23
Thanks again.

**Comment by sticilface** [comment] 2017-03-15 22:13
here is the output from -vvv, using doubletwist
```
pi@rPi3:~ $ shairport-sync -vvv
Looking for the configuration file "/etc/shairport-sync.conf".
Looking for configuration file at full path "/etc/shairport-sync.conf"
Output device name is "default".
The processor is running little-endian.
Version: "3.1s1-OpenSSL-Avahi-ALSA-soxr-metadata-sysconfdir:/etc"
statistics_requester status is 0.
daemon status is 0.
rtsp listening port is 5000.
udp base port is 6001.
udp port range is 100.
Shairport Sync player name is "LivingRoom".
Audio Output name is "(null)".
on-start action is "/home/pi/turnampon.sh".
on-stop action is "(null)".
wait-cmd status is 0.
mdns backend "(null)".
userSuppliedLatency is 0.
AirPlayLatency is -1.
iTunesLatency is -1.
forkedDaapdLatency is -1.
stuffing option is "1" (0-basic, 1-soxr).
resync time is 0.050000 seconds.
allow a session to be interrupted: 1.
busy timeout time is 30.
drift tolerance is 0.001995 seconds.
password is "(null)".
ignore_volume_control is 0.
volume_max_db is not set
playback_mode is 0 (0-stereo, 1-mono, 1-reverse_stereo, 2-both_left, 3-both_right).
disable_synchronization is 0.
use_mmap_if_available is 1.
output_rate is 44100.
output_format is 3 (0-unknown, 1-S8, 2-U8, 3-S16, 4-S24, 5-S24_3LE, 6-S24_3BE, 7-S32).
audio backend desired buffer length is 0.150000 seconds.
audio backend latency offset is 0.000000 seconds.
volume range in dB (zero means use the range specified by the mixer): 0.
zeroconf regtype is "_raop._tcp".
decoders_supported field is 1.
use_apple_decoder is 0.
no special mdns service interface was requested.
configuration file name "/etc/shairport-sync.conf" resolves to "/etc/shairport-sync.conf".
metdata enabled is 0.
metadata pipename is "(null)".
metadata socket address is "(null)" port 0.
metadata socket packet size is "500".
get-coverart is 0.
loudness is 0.
loudness reference level is -20.000000
Successful Startup
avahi: avahi_register.
avahi: register_service.
avahi: service 'F0EFAB8C5D21@LivingRoom' group is not yet commited.
avahi: request to add "_raop._tcp" service without metadata
avahi: service 'F0EFAB8C5D21@LivingRoom' group is registering.
avahi: service 'F0EFAB8C5D21@LivingRoom' successfully added.
New RTSP connection from 192.168.1.182:60817 to self at 192.168.1.245:5000.
    CSeq: 1.
    User-Agent: iTunes/11.0.4 (Macintosh; OS X 10.8.4) AppleWebKit/536.30.1.
    Client-Instance: 15D9776C69FEC4F1.
    Apple-Challenge: wSDltwJV03M0HxZsDaLdSA.
RTSP Packet received of type "OPTIONS":
  Type: "CSeq", content: "1"
  Type: "User-Agent", content: "iTunes/11.0.4 (Macintosh; OS X 10.8.4) AppleWebKit/536.30.1"
  Type: "Client-Instance", content: "15D9776C69FEC4F1"
  Type: "Apple-Challenge", content: "wSDltwJV03M0HxZsDaLdSA"
RTSP Response:
  Type: "Apple-Response", content: "KX5ACUEtkWP33IyYdzzfc6NbI+lhrurceWNk6iZ8BzSzQ3QRIuVW2xvkNDrZ5tYv1Hxs510pSLHj/GY/ynAhXwcJ0kGxbYUeF50J6C7SNcZao2DcyufWbvOD9dFqKo3yh1q8haDKMFRnU35R+UgW1U1D6DGQAJfHqgxqHIlgHHLdzLjVXwWJoVs/kEqL0+5Dq1UOC5SGw/ZKf/QkUVJuK45zf6l73dHbEus52sfcQnVwDkKuxSujHwDsWdTmqMj1jfdH9NOZoh30wR9cIJsRgBrGAMCv96dbV0JLJZasiKbhmqjCE5TbEo77MCzYeievEnSjq+qBnvPm71FZTWp2VA"
  Type: "CSeq", content: "1"
  Type: "Server", content: "AirTunes/105.1"
  Type: "Public", content: "ANNOUNCE, SETUP, RECORD, PAUSE, FLUSH, TEARDOWN, OPTIONS, GET_PARAMETER, SET_PARAMETER"
    CSeq: 2.
    Content-Type: application/sdp.
    Content-Length: 572.
    User-Agent: iTunes/11.0.4 (Macintosh; OS X 10.8.4) AppleWebKit/536.30.1.
    Client-Instance: 15D9776C69FEC4F1.
RTSP Packet received of type "ANNOUNCE":
  Type: "CSeq", content: "2"
  Type: "Content-Type", content: "application/sdp"
  Type: "Content-Length", content: "572"
  Type: "User-Agent", content: "iTunes/11.0.4 (Macintosh; OS X 10.8.4) AppleWebKit/536.30.1"
  Type: "Client-Instance", content: "15D9776C69FEC4F1"
  fmtp[ 0] is:         96
  fmtp[ 1] is:        352
  fmtp[ 2] is:          0
  fmtp[ 3] is:         16
  fmtp[ 4] is:         40
  fmtp[ 5] is:         10
  fmtp[ 6] is:         14
  fmtp[ 7] is:          2
  fmtp[ 8] is:        255
  fmtp[ 9] is:          0
  fmtp[10] is:          0
  fmtp[11] is:      44100
Play connection from user agent "iTunes/11.0.4 (Macintosh; OS X 10.8.4) AppleWebKit/536.30.1".
RTSP Response:
  Type: "CSeq", content: "2"
  Type: "Server", content: "AirTunes/105.1"
    CSeq: 3.
    Transport: RTP/AVP/UDP;unicast;interleaved=0-1;mode=record;control_port=6001;timing_port=6002.
    User-Agent: iTunes/11.0.4 (Macintosh; OS X 10.8.4) AppleWebKit/536.30.1.
    Client-Instance: 15D9776C69FEC4F1.
RTSP Packet received of type "SETUP":
  Type: "CSeq", content: "3"
  Type: "Transport", content: "RTP/AVP/UDP;unicast;interleaved=0-1;mode=record;control_port=6001;timing_port=6002"
  Type: "User-Agent", content: "iTunes/11.0.4 (Macintosh; OS X 10.8.4) AppleWebKit/536.30.1"
  Type: "Client-Instance", content: "15D9776C69FEC4F1"
User-Agent is iTunes 10 or better, (actual version is 11); selecting the iTunes latency of 11 frames.
rtp_setup: cport=6001 tport=6002.
Set up play connection from 192.168.1.182 to self at 192.168.1.245.
listening for audio, control and timing on ports 6001, 6002, 6003.
RTSP Response:
  Type: "CSeq", content: "3"
  Type: "Server", content: "AirTunes/105.1"
  Type: "Transport", content: "RTP/AVP/UDP;unicast;interleaved=0-1;mode=record;control_port=6002;timing_port=6003;server_port=6001"
  Type: "Session", content: "1"
Output frame bytes is 0.
Output sample ratio is 1.
RTSP connection closed.
Closing down RTSP conversation thread...
Audio receiver -- Server RTP thread starting.
Control receiver -- Server RTP thread starting.
Timing receiver -- Server RTP thread starting.
Output bit depth is 16.
Timing sender thread starting.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0Shut down audio, control and timing threads
Audio receiver -- Server RTP thread interrupted. terminating.
Timing thread interrupted. terminating.
rtp_timing_sender thread interrupted. terminating.
Control RTP thread interrupted. terminating.
Closed and terminated timer requester thread.
Timing RTP thread terminated.
timing thread joined
audio thread joined
control thread joined
Player thread exit
shutting down RTP thread
RTSP conversation thread terminated.
100 69965  100 69965    0     0  1087k      0 --:--:-- --:--:-- --:--:-- 1102k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  5951  100  5951    0     0  64318      0 --:--:-- --:--:-- --:--:-- 63989
```

**Comment by mikebrady** [comment] 2017-03-15 22:17
Great thanks. I'll study it.

**Comment by mikebrady** [comment] 2017-03-16 07:28
Thanks for your patience with this. If you set `allow_session_interruption` back to `"no"` does the problem go away?

**Comment by sticilface** [comment] 2017-03-17 10:58
ok, sorry for the delay there.  The answer is no.  settings no interrupts yields the same
```
pi@rPi3:/etc $ shairport-sync -vvv
Looking for the configuration file "/etc/shairport-sync.conf".
Looking for configuration file at full path "/etc/shairport-sync.conf"
Output device name is "default".
The processor is running little-endian.
Version: "3.1s1-OpenSSL-Avahi-ALSA-soxr-metadata-sysconfdir:/etc"
statistics_requester status is 0.
daemon status is 0.
rtsp listening port is 5000.
udp base port is 6001.
udp port range is 100.
Shairport Sync player name is "LivingRoom".
Audio Output name is "(null)".
on-start action is "/home/pi/turnampon.sh".
on-stop action is "(null)".
wait-cmd status is 0.
mdns backend "(null)".
userSuppliedLatency is 0.
AirPlayLatency is -1.
iTunesLatency is -1.
forkedDaapdLatency is -1.
stuffing option is "1" (0-basic, 1-soxr).
resync time is 0.050000 seconds.
allow a session to be interrupted: 0.
busy timeout time is 30.
drift tolerance is 0.001995 seconds.
password is "(null)".
ignore_volume_control is 0.
volume_max_db is not set
playback_mode is 0 (0-stereo, 1-mono, 1-reverse_stereo, 2-both_left, 3-both_right).
disable_synchronization is 0.
use_mmap_if_available is 1.
output_rate is 44100.
output_format is 3 (0-unknown, 1-S8, 2-U8, 3-S16, 4-S24, 5-S24_3LE, 6-S24_3BE, 7-S32).
audio backend desired buffer length is 0.150000 seconds.
audio backend latency offset is 0.000000 seconds.
volume range in dB (zero means use the range specified by the mixer): 0.
zeroconf regtype is "_raop._tcp".
decoders_supported field is 1.
use_apple_decoder is 0.
no special mdns service interface was requested.
configuration file name "/etc/shairport-sync.conf" resolves to "/etc/shairport-sync.conf".
metdata enabled is 0.
metadata pipename is "(null)".
metadata socket address is "(null)" port 0.
metadata socket packet size is "500".
get-coverart is 0.
loudness is 0.
loudness reference level is -20.000000
Successful Startup
avahi: avahi_register.
avahi: register_service.
avahi: service 'F0EFAB8C5D21@LivingRoom' group is not yet commited.
avahi: request to add "_raop._tcp" service without metadata
avahi: service 'F0EFAB8C5D21@LivingRoom' group is registering.
avahi: service 'F0EFAB8C5D21@LivingRoom' successfully added.
New RTSP connection from 192.168.1.182:39416 to self at 192.168.1.245:5000.
    CSeq: 1.
    User-Agent: iTunes/11.0.4 (Macintosh; OS X 10.8.4) AppleWebKit/536.30.1.
    Client-Instance: 6FC3664F4687913A.
    Apple-Challenge: tOjr8m+cEl8jgEnUSQEWZQ.
RTSP Packet received of type "OPTIONS":
  Type: "CSeq", content: "1"
  Type: "User-Agent", content: "iTunes/11.0.4 (Macintosh; OS X 10.8.4) AppleWebKit/536.30.1"
  Type: "Client-Instance", content: "6FC3664F4687913A"
  Type: "Apple-Challenge", content: "tOjr8m+cEl8jgEnUSQEWZQ"
RTSP Response:
  Type: "Apple-Response", content: "z4wtsueTIY+4M8X7Oa8MA2HKVi2YylOJ+uB6DTJn+HsHkHO8DqPJA0YBMkwvYT64zFR4t9qXLE/k19k+rVzNx/w6ucpTn6AOJtoMlvjPWGd6uxKN+ByHBzKmDjji5J4dKIvZ7c38GY1uDrz0j08UyeAJrt34+9hC57al2X34i+njgig6WvR+l07zBSiYhvZ1YYIUclCl+dhDhs/tZPxRil8lKAHZxy6ZoRtYYmbUXIBrrcPknNt/XFDV1bTtoJSxjn16b6Zl74kfbqGvT8KouyEmzevybQC13tlplwUuPTQ1ah2lHvXIIry3/N8BDgsMCaPRUzn6dz/dxEFu4rXW2A"
  Type: "CSeq", content: "1"
  Type: "Server", content: "AirTunes/105.1"
  Type: "Public", content: "ANNOUNCE, SETUP, RECORD, PAUSE, FLUSH, TEARDOWN, OPTIONS, GET_PARAMETER, SET_PARAMETER"
    CSeq: 2.
    Content-Type: application/sdp.
    Content-Length: 572.
    User-Agent: iTunes/11.0.4 (Macintosh; OS X 10.8.4) AppleWebKit/536.30.1.
    Client-Instance: 6FC3664F4687913A.
RTSP Packet received of type "ANNOUNCE":
  Type: "CSeq", content: "2"
  Type: "Content-Type", content: "application/sdp"
  Type: "Content-Length", content: "572"
  Type: "User-Agent", content: "iTunes/11.0.4 (Macintosh; OS X 10.8.4) AppleWebKit/536.30.1"
  Type: "Client-Instance", content: "6FC3664F4687913A"
  fmtp[ 0] is:         96
  fmtp[ 1] is:        352
  fmtp[ 2] is:          0
  fmtp[ 3] is:         16
  fmtp[ 4] is:         40
  fmtp[ 5] is:         10
  fmtp[ 6] is:         14
  fmtp[ 7] is:          2
  fmtp[ 8] is:        255
  fmtp[ 9] is:          0
  fmtp[10] is:          0
  fmtp[11] is:      44100
Play connection from user agent "iTunes/11.0.4 (Macintosh; OS X 10.8.4) AppleWebKit/536.30.1".
RTSP Response:
  Type: "CSeq", content: "2"
  Type: "Server", content: "AirTunes/105.1"
    CSeq: 3.
    Transport: RTP/AVP/UDP;unicast;interleaved=0-1;mode=record;control_port=6001;timing_port=6002.
    User-Agent: iTunes/11.0.4 (Macintosh; OS X 10.8.4) AppleWebKit/536.30.1.
    Client-Instance: 6FC3664F4687913A.
RTSP Packet received of type "SETUP":
  Type: "CSeq", content: "3"
  Type: "Transport", content: "RTP/AVP/UDP;unicast;interleaved=0-1;mode=record;control_port=6001;timing_port=6002"
  Type: "User-Agent", content: "iTunes/11.0.4 (Macintosh; OS X 10.8.4) AppleWebKit/536.30.1"
  Type: "Client-Instance", content: "6FC3664F4687913A"
User-Agent is iTunes 10 or better, (actual version is 11); selecting the iTunes latency of 11 frames.
rtp_setup: cport=6001 tport=6002.
Set up play connection from 192.168.1.182 to self at 192.168.1.245.
listening for audio, control and timing on ports 6001, 6002, 6003.
RTSP Response:
  Type: "CSeq", content: "3"
  Type: "Server", content: "AirTunes/105.1"
  Type: "Transport", content: "RTP/AVP/UDP;unicast;interleaved=0-1;mode=record;control_port=6002;timing_port=6003;server_port=6001"
  Type: "Session", content: "1"
Output frame bytes is 0.
Output sample ratio is 1.
Audio receiver -- Server RTP thread starting.
Control receiver -- Server RTP thread starting.
Output bit depth is 16.
Timing receiver -- Server RTP thread starting.
RTSP connection closed.
Closing down RTSP conversation thread...
Timing sender thread starting.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0Shut down audio, control and timing threads
Audio receiver -- Server RTP thread interrupted. terminating.
Control RTP thread interrupted. terminating.
Timing thread interrupted. terminating.
rtp_timing_sender thread interrupted. terminating.
Closed and terminated timer requester thread.
Timing RTP thread terminated.
timing thread joined
audio thread joined
control thread joined
Player thread exit
shutting down RTP thread
RTSP conversation thread terminated.
100 69953  100 69953    0     0  1048k      0 --:--:-- --:--:-- --:--:-- 1067k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  5951  100  5951    0     0  69603      0 --:--:-- --:--:-- --:--:-- 70845

```

**Comment by mikebrady** [comment] 2017-03-17 11:13
Thanks.

**Comment by mikebrady** [comment] 2019-10-24 10:00
There have been many changes, so this may have been addressed in more recent versions of Shairport Sync! Closing this inactive issue. Please open a new one if necessary.

**Closed by mikebrady** 2019-10-24 10:00 UTC
