### ISSUE TITLE
No longer syncs. Latest version of shairport-sync and macOS [Resolved]

### ISSUE THREAD

**Issue by ThewC** [mikebrady/shairport-sync#607] opened 2017-10-23 22:04 UTC
Macbook Pro Retina Mid 2010
macOS Sierra 10.12.6

I updated to Sierra a while back and while I can still stream to my Raspberry Pi running Shairport-Sync it didn't sync the audio anymore. I've updated and even re-isntalled Shairport-Sync to try and resolve the issue.

Thanks for reading. me@mathewc.com

**Comment by mikebrady** [comment] 2017-10-23 22:22
Thanks. I’m running everything up to date and sync is still there. What is your audio source on the Mac. Is it Chrome, by any chance? Have you check iTunes or Safari?

**Comment by chromoxdor** [comment] 2017-11-21 09:16
I maybe have the same issue.
Since MacOS Sierra and iOS11 i had problems playing audio (stuttering) und it didn´t sync audio from video on my raspi with an about one year old version of shaiport-sync.
So i thought its time for an update. Unfortunately nothing has changed. With my Apple devices running on operating systems before iOS11 and MacOS i don´t have this problems.

Btw: @ThewC : there is no Macbook Pro Retina Mid 2010. I must know because i have a Macbook Pro Mid 2010 (but at least high-res)  :)

**Comment by mikebrady** [comment] 2017-11-21 10:43
Thanks for the post. Would you be kind enough to give me an example of this with informations about the machine, the version of the OS, the application you are using and, if possible, a link to of a video, please? Then I can see what's happening.

**Comment by chromoxdor** [comment] 2017-11-21 16:27
at first i have to correct myself.... 
stuttering happens on all devices since upgrade.
here ist the output of shairport:
(out of sync details will follow)

root@raspberry:~# sudo shairport-sync -vv  -a Sonne -S soxr  -t 5 -L 22050 
Looking for configuration file at full path "/usr/local/etc/shairport-sync.conf"
alsa output device name is "default".
The processor is running little-endian.
The default latency setting is deprecated, as Shairport Sync can now get the correct latency from the source.
Please remove this setting and use the relevant audio_backend_latency_offset setting, if necessary, to compensate for delays elsewhere.
Version: "3.1.3-OpenSSL-Avahi-ALSA-soxr-sysconfdir:/usr/local/etc"
statistics_requester status is 0.
daemon status is 0.
deamon pid file is "/var/run/shairport-sync/shairport-sync.pid".
rtsp listening port is 5000.
udp base port is 6001.
udp port range is 100.
player name is "Sonne".
backend is "(null)".
on-start action is "(null)".
on-stop action is "(null)".
wait-cmd status is 0.
on-start returns output is 0.
mdns backend "(null)".
userSuppliedLatency is 22050.
AirPlayLatency is -1.
iTunesLatency is -1.
forkedDaapdLatency is -1.
stuffing option is "1" (0-basic, 1-soxr).
resync time is 0.050000 seconds.
allow a session to be interrupted: 0.
busy timeout time is 5.
drift tolerance is 0.001995 seconds.
password is "(null)".
ignore_volume_control is 0.
volume_max_db is not set
playback_mode is 0 (0-stereo, 1-mono, 1-reverse_stereo, 2-both_left, 3-both_right).
disable_synchronization is 0.
use_mmap_if_available is 1.
output_rate is 44100.
output_format is 3 (0-unknown, 1-S8, 2-U8, 3-S16, 4-S24, 5-S24_3LE, 6-S24_3BE, 7-S32).
audio backend desired buffer length is 0.150000 seconds.
audio backend latency offset is 0.000000 seconds.
audio backend silence lead-in time is -1.000000 seconds. A value -1.0 means use the default.
volume range in dB (zero means use the range specified by the mixer): 0.
zeroconf regtype is "_raop._tcp".
decoders_supported field is 1.
use_apple_decoder is 0.
alsa_use_playback_switch_for_mute is 0.
no special mdns service interface was requested.
configuration file name "/usr/local/etc/shairport-sync.conf" resolves to "/usr/local/etc/shairport-sync.conf".
loudness is 0.
loudness reference level is -20.000000
Successful Startup
avahi: avahi_register.
avahi: register_service.
avahi: service '973433B9B55D@Sonne' group is not yet committed.
avahi: request to add "_raop._tcp" service without metadata
avahi: service '973433B9B55D@Sonne' group is registering.
avahi: service '973433B9B55D@Sonne' successfully added.
New RTSP connection from [fe80::9227:e4ff:fefe:2472]:55240 to self at [fe80::821f:2ff:feb9:6fbb]:5000 on conversation thread 0.
Play connection from device named "X1" on RTSP conversation thread 0.
Play connection from user agent "AirPlay/215.18" on RTSP conversation thread 0.
Active-Remote string seen: "232160909".
User-Agent is AirPlay; selecting the AirPlay latency of -1 frames.
rtp_setup: cport=65023 tport=50745.
Set up play connection from fe80::9227:e4ff:fefe:2472 to self at fe80::821f:2ff:feb9:6fbb on RTSP conversation thread 0.
listening for audio, control and timing on ports 6001, 6002, 6003.
Output frame bytes is 4.
Output bit depth is 16.
Timing receiver -- Server RTP thread starting.
Control receiver -- Server RTP thread starting.
Audio receiver -- Server RTP thread starting.
Timing sender thread starting.
syncing to seqno 65070.
Hammerton Decoder used on encrypted audio.
Output written using MMAP
PCM handle name = 'default'
alsa device parameters:
  access type = MMAP_INTERLEAVED
  format = 'S16_LE' (Signed 16 bit Little Endian)
  subformat = 'STD' (Standard)
  number of channels = 2
  number of significant bits = 16
  rate = 44100 frames per second (precisely).
  precise (rational) rate = 0.000 frames per second (i.e. 0/1088784512).
  period_time = 21333 us (>).
  period_size = 940 frames (>).
  buffer_time = 341315 us (>).
  buffer_size = 15052 frames (>).
  periods_per_buffer = 341315 (>).
Error -32 writing 351 samples in play(): "Broken pipe".
Error -32 writing 351 samples in play(): "Broken pipe".
Error -32 writing 351 samples in play(): "Broken pipe".
Error -32 writing 351 samples in play(): "Broken pipe".
Error -32 writing 351 samples in play(): "Broken pipe".
Error -32 writing 351 samples in play(): "Broken pipe".
Error -32 writing 351 samples in play(): "Broken pipe".
Error -32 writing 351 samples in play(): "Broken pipe".
Error -32 writing 351 samples in play(): "Broken pipe".
Error -32 writing 351 samples in play(): "Broken pipe".
Error -32 writing 351 samples in play(): "Broken pipe".
Error -32 writing 351 samples in play(): "Broken pipe".
Error -32 writing 351 samples in play(): "Broken pipe".
`

**Comment by chromoxdor** [comment] 2017-11-21 16:33
And nothing interesting to find in the console.app

**Comment by chromoxdor** [comment] 2017-11-21 16:44
Ok....stuttering gone!!!!
I tried shairport without soxr.
I´m not really sure why used it in first place but i think i remember that there always was a crackling or humming in the background when i used it without it.

**Comment by chromoxdor** [comment] 2017-11-21 17:05
...and was there always a -B and -E option? I had to write a script for that two years ago :)

**Comment by mikebrady** [comment] 2017-11-21 17:23
Thanks for all these.

Okay, the first thing to notice is that you have set a latency of 0.5 seconds (22050 frames) rather than the two seconds that is normally negotiated automatically. This means that Shairport Sync has much less time to adjust for timing delays and to accommodate sudden heavy processing loads caused by using SoX. I suggest you remove the `-L 22050` option. (Perhaps the last time you looked, Shairport Sync did not set latencies automatically, but it does now.)

It is worth not selecting the `soxr` option until you have everything else sorted out. Then, if stuttering recommences, you will know it's `soxr` that is causing it...

The `-B` and `-E` options are still there, and they are also settable from within the configuration file.

**Comment by mikebrady** [comment] 2017-11-21 17:37
Also, that `-L 22050` setting would account for the lack os synchronisation. Safari, Quicktime Player and iTunes, and possibly others, will delay the video part of a movie by the agreed latency, so that the video on the screen will be in sync with the audio AirPlay, which is delayed by the agreed latency, usually two seconds or slightly more in the case of iTunes.

**Comment by chromoxdor** [comment] 2017-11-21 18:27
I also tried to run shairport without -L  (it never was or is the problem) but the sync problem is still there.
And only disabling soxr removes the stutter.
Here is a short video about the issue:
https://drive.google.com/open?id=11KoFUKoFKxGNY7TJRESKaQNORbVlFIo2

command: sudo shairport-sync -a Sonne  -t 5 
and i also tried it on my girlfriends mac (10.12.6) and another mac with pre macOS.
Same results..... new OS...video out of sync

**Comment by mikebrady** [comment] 2017-11-21 18:40
Thanks again. If I’m not mistaken, you are using Chrome, which does not delay the video. Try using Safari, and leave the `-L` option out.

**Comment by chromoxdor** [comment] 2017-11-21 18:46
unfortunately not browser nor youtube related.

**Comment by chromoxdor** [comment] 2017-11-21 18:47
and as i wrote before, i used this for testing:

shairport-sync -a Sonne -t 5

**Comment by chromoxdor** [comment] 2017-11-21 20:06
I found out, that Quicktime is the only program, that plays video in sync with audio on shairport.
:/

btw. thanks for helping me!

**Comment by mikebrady** [comment] 2017-11-21 20:21
Thanks for the update – it is very reassuring that Quicktime is working. I expect therefore that if you have an iTunes video, it will also play in sync.

Now that I've had an opportunity to look at your video in a quiet room, I notice around 1:21, on the Sierra Mac, you start the video and then switch to the Shairport Sync speaker – this won't get sync. However, if you (a) are using Safari and (b) ensure you are not playing a video when you switch over to the Shairport Sync speaker and (c) start the video, you should get sync. Would you be kind enough to try it out please?

**Comment by chromoxdor** [comment] 2017-11-22 13:28
In this order it works.....

**Comment by mikebrady** [comment] 2017-11-22 13:34
Good. This seems to be a feature of the way AirPlay has been implemented – it's not a Shairport Sync thing. BTW, in VLC, you can use the Window > Track Synchronisation panel to synchronise the audio with the video.

**Comment by mikebrady** [comment] 2017-11-24 20:42
Fixed, I think?

**Comment by chromoxdor** [comment] 2017-11-25 17:50
Let´s say it´s a workaround to use safari und switch to shairport before. Anyway, it´s not that important to investigate it further.
Plain audio-steaming works very well and that more important to me.

Thanks a lot for your help!!!

**Closed** 2019-10-24 10:29 UTC
