### ISSUE TITLE
intermittent audio jittering on raspberry pi 3

### ISSUE THREAD

**Issue by min-xu-ai** [mikebrady/shairport-sync#640] opened 2018-01-08 00:52 UTC
Hi Mike,

First, thanks for awesome work on shairport-sync! I have been using it on a lot of different devices at home and work. Even an old powerbook G4 is running it.

On my PI3 though, I occasionally run into intermittent audio jittering and skipping after some time of streaming from my iPhone SE. The time could be 10, 20 minutes after streaming started or could be longer, but after it starts, it seems to continue and doesn't recover.

Today, I did some debugging by enabling -v. I saw that dithering was enabled. So I uncommented the code for fixed_volume and disabled dithering. That seems to help a lot.

```
diff --git a/player.c b/player.c
index 8530f44..4f96a8b 100644
--- a/player.c
+++ b/player.c
@@ -1368,7 +1368,7 @@ static void *player_thread_func(void *arg) {
   conn->ab_synced = 0;
   conn->first_packet_timestamp = 0;
   conn->flush_requested = 0;
-  // conn->fix_volume = 0x10000;
+  conn->fix_volume = 0x10000;
 
   int rc = pthread_mutex_init(&conn->ab_mutex, NULL);
   if (rc)
```

However, with that change, I just run into the same jitter just now. The debug log has this:

```
Inconsistent sequence numbers detected
Inconsistent sequence numbers detected
Aliasing of buffer index -- reset.
Player: packets out of sequence: expected: 65221, got: 197, with ab_read: 198 and ab_write: 328.
```

But it seems to recover this time. Previously, it doesn't seem to recover. But that could be me not waiting long enough.

Any other debug log I should collect?

Thanks!
Min

**Comment by min-xu-ai** [comment] 2018-01-08 01:25
BTW, maybe the log output lines can be prefixed with some timestamps so that it is easier to correlate the output with problem that might be happening at the time?

**Comment by min-xu-ai** [comment] 2018-01-08 01:26
Some additional log outputs just now seems to be related to a short jitter ( a few seconds) but it immediately recovered.

```
Player thread exit on RTSP conversation thread 0.
RTSP conversation thread 0 terminated.
New RTSP connection from [fe80::4bc:1a2d:dcdd:d31]:50842 to self at [fe80::ba27:ebff:fe77:cf3]:5000 on conversation thread 1.
Play connection from user agent "AirPlay/354.54.6" on RTSP conversation thread 1.
Active-Remote string seen: "1839647459".
DACP-ID string seen: "F91E47F536878887".
Set up play connection from fe80::4bc:1a2d:dcdd:d31 to self at fe80::ba27:ebff:fe77:cf3 on RTSP conversation thread 1.
Output frame bytes is 4.
Output bit depth is 16.
Set initial volume to -1.875000.
Using negotiated latency of 88200 frames and a static latency correction of 0
Hammerton Decoder used on encrypted audio.
Aliasing of buffer index -- reset.
Player: packets out of sequence: expected: 20551, got: 21063, with ab_read: 21064 and ab_write: 21232.
```

**Comment by mikebrady** [comment] 2018-01-08 08:08
Thanks for the post, and for your detective work. A couple of points:

1. If you enable a level of logging in the configuration file, install your modified program with `$ sudo make install`  and restart it as a daemon using `$ sudo systemctl restart shairport-sync`, you will get the timestamps in the log file with something like `$ sudo journalctl -n 100 -f` which prints the most recent 100 lines and any further log  entries as they are posted.
2. It seems unlikely that either the dithering or the fixed volume initialisation would make any difference (although, of course, you never know :))
3. Is `soxr` interpolation on? The aliasing of the buffer index usually occurs because something holds up the output processing of audio frames. One possible culprit is `soxr` processing. If so, please turn it off and see if the problem continues to occur.
4. If the problem persists, it would be really great to try to reproduce it "at will", so if there was some sure-fire way of getting it to happen, then would be really fantastic.

**Comment by min-xu-ai** [comment] 2018-01-08 17:37
Awesome. Thanks for quick reply. I will try turning off soxr.

**Comment by min-xu-ai** [comment] 2018-01-08 20:19
Actually, I never had soxr turned on in my setup. Here is the startup log:

```
starting...
ERROR: Failed to load plugin /usr/lib/ao/plugins-4/libpulse.so => dlopen() failed
Version: "3.1.6-OpenSSL-Avahi-ao-soxr-sysconfdir:/usr/local/etc"
statistics_requester status is 0.
daemon status is 0.
deamon pid file is "/var/run/shairport-sync/shairport-sync.pid".
rtsp listening port is 5000.
udp base port is 6001.
udp port range is 100.
player name is "Bookshelf".
backend is "(null)".
on-start action is "(null)".
on-stop action is "(null)".
wait-cmd status is 0.
on-start returns output is 0.
mdns backend "(null)".
stuffing option is "0" (0-basic, 1-soxr).
resync time is 0.050000 seconds.
allow a session to be interrupted: 0.
busy timeout time is 120.
drift tolerance is 0.001995 seconds.
password is "(null)".
ignore_volume_control is 0.
volume_max_db is not set
playback_mode is 0 (0-stereo, 1-mono, 1-reverse_stereo, 2-both_left, 3-both_right).
disable_synchronization is 0.
use_mmap_if_available is 1.
output_rate is 44100.
output_format is 3 (0-unknown, 1-S8, 2-U8, 3-S16, 4-S24, 5-S24_3LE, 6-S24_3BE, 7-S32).
audio backend desired buffer length is 1.000000 seconds.
audio backend latency offset is 0.000000 seconds.
audio backend silence lead-in time is -1.000000 seconds. A value -1.0 means use the default.
volume range in dB (zero means use the range specified by the mixer): 0.
zeroconf regtype is "_raop._tcp".
decoders_supported field is 1.
use_apple_decoder is 0.
alsa_use_playback_switch_for_mute is 0.
no special mdns service interface was requested.
configuration file name "/usr/local/etc/shairport-sync.conf" can not be resolved.
loudness is 0.
loudness reference level is 0.000000
Successful Startup
avahi: avahi_register.
avahi: register_service.
avahi: request to add "_raop._tcp" service without metadata
avahi: service '97E56CAEDE5C@Bookshelf' successfully added.
```

Staffing setting is 0, i.e. basic.

I will turn on statistics next. In my setup, I don't use a conf file or system. I just run the binary out of its build tree. Since I need to frequently restart shairport-sync (due to the jitter), I wrote a wrapper just start/stop it based on whether my DAC is turned on/off. When my DAC is on, the USB device shows up in lsusb, so I then start shairport. I also compiled it using libao backend since that one works better with my script killing it. Here is my build script:

```
./configure --with-ao --with-avahi --with-ssl=openssl --with-soxr 
make -j
```

If you want my wrapper script, I can upload that too.

I wish to reproduce it at will, but I don't see a way now. Maybe I can try unplug network cable or something?

**Comment by min-xu-ai** [comment] 2018-01-08 20:36
stats seems quite clean with 2 columns always 0s. (I don't know what they are)

```
       0.0,       65195,      0,    291,      0,    294,  289,  298
       0.0,       66198,      0,    291,      0,    294,  290,  299
       0.0,       67201,      0,    291,      0,    294,  291,  300
       0.0,       68204,      0,    291,      0,    294,  292,  301
       0.0,       69207,      0,    291,      0,    294,  293,  301
       0.0,       70210,      0,    291,      0,    294,  294,  302
       0.0,       71213,      0,    291,      0,    294,  295,  303
       0.0,       72216,      0,    291,      0,    294,  295,  320
       0.0,       73219,      0,    291,      0,    294,  306,  320
       0.0,       74222,      0,    291,      0,    294,  306,  321
       0.0,       75225,      0,    291,      0,    294,  307,  322
       0.0,       76228,      0,    291,      0,    294,  297,  323
       0.0,       77231,      0,    291,      0,    294,  309,  323
       0.0,       78234,      0,    291,      0,    294,  308,  325
       0.0,       79237,      0,    291,      0,    294,  309,  325
       0.0,       80240,      0,    291,      0,    294,  311,  327
       0.0,       81243,      0,    291,      0,    294,  312,  327
       0.0,       82246,      0,    294,      0,    297,  313,  327
       0.0,       83249,      0,    294,      0,    297,  311,  329
       0.0,       84252,      0,    294,      0,    297,  315,  329
       0.0,       85255,      0,    294,      0,    297,  314,  331
       0.0,       86258,      0,    294,      0,    297,  317,  331
```

**Comment by mikebrady** [comment] 2018-01-09 10:53
Thanks for the log, which is quite interesting. BTW, the headings for the column would have been somewhere further back in the log. They are: 
`sync error in milliseconds`; `total packets`; `missing packets`; `late packets`; `too late packets`; `resend requests`; `minimum buffer occupancy` and finally `maximum buffer occupancy`. The first column -- `sync error in milliseconds` -- really shouldn't be there, TBH, and should be ignored. Lines are printed approximately every eight seconds (1,003 packets, each of 352 audio frames).

The thing to notice is that the `ao` back end is being used and so no synchronisation is done.

This means that if the `ao` system consumes audio data faster than it is being supplied to Shairport Sync by the source, starvation (i.e. underflow) will eventually occur. 

What is actually happening in this case, though, is that the `ao` system is consuming data slightly slower than it is being supplied to Shairport Sync, so overflow eventually occurs.

Specifically, excess data accumulates in Shairport Sync's buffers, as shown in the rightmost two columns above. These show a gradual rise in the minimum and maximum number of buffers in use, respectively, starting with a min/max of 289/298 at the time of the first sample moving to 317/331 at the time of the last sample. Eventually all 512 buffers will be occupied and aliasing of buffer index numbers will start to occur. Shairport Sync will then misbehave and possibly crash.

The solution is to use one of the back ends that supports synchronisation, such as the `alsa` back end.

**Comment by min-xu-ai** [comment] 2018-01-09 16:20
I see. That's very helpful! I will try switch the backend. I had no idea ao doesn't support sync. :-)

**Closed** 2018-01-09 16:21 UTC

**Comment by min-xu-ai** [comment] 2018-01-09 16:23
BTW, will alsa backend tolerate a USB sound device comes and goes away? I don't always keep my DAC on and when it is off, the USB device in linux is also gone. I remember alsa didn't like it. :-(

**Comment by mikebrady** [comment] 2018-01-09 17:29
Hmm, I'll try this out.

**Comment by min-xu-ai** [comment] 2018-01-09 19:35
Thanks a lot, Mike!

**Comment by min-xu-ai** [comment] 2018-01-10 05:37
I think I reproduced the issue with alsa backend I was having:

```
Error -5 writing 351 samples in play(): "Input/output error".
Error -5 writing 351 samples in play(): "Input/output error".
Error -5 writing 351 samples in play(): "Input/output error".
Error -5 writing 351 samples in play(): "Input/output error".
Error -5 writing 351 samples in play(): "Input/output error".
Error -5 writing 351 samples in play(): "Input/output error".
Error -5 writing 351 samples in play(): "Input/output error".
Error -5 writing 351 samples in play(): "Input/output error".
Error -5 writing 351 samples in play(): "Input/output error".
Error -5 writing 351 samples in play(): "Input/output error".
Error -5 writing 351 samples in play(): "Input/output error".
Error -5 writing 351 samples in play(): "Input/output error".
Error -5 writing 351 samples in play(): "Input/output error".
Error -5 writing 351 samples in play(): "Input/output error".
Error -5 writing 351 samples in play(): "Input/output error".
Error -5 writing 351 samples in play(): "Input/output error".
```

If I turn off my DAC while iPhone is connected to shairport and while it is playing, I got the error above. From the client point of view, it is still playing (from the iPhone side). Although, shairport is just busy printing the error msg above.

When I turn back on the DAC, shairport does _not_ recover and continues to print the error msg.

When I press ^C or kill -9 shairport-sync at that state, it is not killable. I think it just stucks at a system call. I have to _reboot_ the kernel to get out of that state. :-(

Ideally, in this case, I would think when I turn off the DAC, shairport should disconnect the client and wait for the next connection or something?

**Comment by mikebrady** [comment] 2018-01-10 09:07
Any general solution to this problem would go far beyond Shairport Sync, I'm afraid.

Unfortunately, AFAIK, there's no general guarantee that the USB DAC will reappear when switched back on -- that depends on whether the system is set up to do hot-plugging, and then the details of whether and how `alsa` deals with a newly-appearing device will be important. Even if it is recognised and configured in `alsa` (a big supposition!), it may not have the same identity as it had before it was switched off.

So, to be honest, I think you're out of luck there.

**Comment by min-xu-ai** [comment] 2018-01-10 14:35
Thanks a lot. Should I try pulseaudio backend?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by mikebrady** [comment] 2018-01-10 15:09
Yes indeed. The `pa` one -- use the `--with-pa` configuration option. It has synchronisation too.

**Comment by min-xu-ai** [comment] 2018-01-11 03:53
Great! I can report back and confirm pulseaudio indeed works for this case. Hotplug is handled correctly. Shairport-sync just continue to play to the default dummy output sink when the USB DAC is powered off. But when the DAC is turned back on, the audio resumes to it.

Since I use my wrapper script to start/stop shairport-sync, iPhone will also stop if I turn off USB. So all my needs are met.

I did hit one assert:

```
stopping...
shutdown requested...
avahi: avahi_unregister.
Request to shut down all rtsp conversation threads
asking playing threads to stop
Playback Stopped. Total playing time 00:00:12.
Assertion 'pthread_mutex_lock(&m->mutex) == 0' failed at pulsecore/mutex-posix.c:90, function pa_mutex_lock(). Aborting.
```

But that's in the pulse library, perhaps indicating something not cleaned up on stopping.

This setup uses a bit more cpu and memory (since both shairport and pulseaudio processes must be running). But that's completely fine with Pi3. I am a little worried that pulseaudio does unnecessary data processing (like resampling) for the data but so far I can't hear any difference. Perhaps I will try to play some "HIFI" titles later. ;-)

**Comment by min-xu-ai** [comment] 2018-01-11 22:01
some verbose output when I connect pulseaudio client to shairport from a linux box:

```
Hammerton Decoder used on encrypted audio.
Volume request value -30.000381 is out of range: should be from 0.0 to -30.0 or -144.0.
unrecognised parameter: "SET_PARAMETER rtsp://172.29.10.149/3629747221 RTSP/1.0" (54)

unrecognised parameter: "CSeq: 8" (7)

unrecognised parameter: "Session: 1" (10)

unrecognised parameter: "Content-Type: text/parameters" (29)

unrecognised parameter: "Content-Length: 19" (18)

unrecognised parameter: "User-Agent: iTunes/11.0.4 (Windows; N)" (38)

unrecognised parameter: "" (0)

Playback Stopped. Total playing time 00:00:08.
```

Sorry, if this is not interesting. Just FYI.

**Comment by mikebrady** [comment] 2018-01-12 08:58
Thanks for the post. (I should really modify Shairport Sync to better capture that diagnostic information.) The PulseAudio to AirPlay module “raop” was hopelessly out-of-date, but it may (?) have been recently updated. Do you happen to know anything about the airplay module PulseAudio is using?

**Comment by min-xu-ai** [comment] 2018-01-12 15:17
Unfortunately, I dont know much about it.

Do you know how to avoid the assert I ran into?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by mikebrady** [comment] 2018-01-12 15:54
I'm afraid I don't really know what parameter PulseAudio is sending out. Recently, however, in the `development` branch, the ability to handle one particular `SET_PARAMETER` handler was added.

On the chance that is is the same one that PulseAudio is putting out, it is probably worth switching to the `development` branch of Shairport Sync and updating. The procedure to follow to update to the `development` branch is almost the same as that given on the UPDATING page, but just after the `$ cd shairport-sync` command, enter the command `$ git checkout development` before continuing with the `$ autoreconf -fi` command and all the rest of it. Everything else will be the same.

**Comment by min-xu-ai** [comment] 2018-01-12 19:06
I don't really care about pulseaudio client to shairport-sync myself. My use case doesn't need that. In my case, I just use pulseaudio client to connect to pulseaudio server directly anyway.
