### ISSUE TITLE
shairport-syng is beeing used by someone else.

### ISSUE THREAD

**Issue by dhojgaard** [mikebrady/shairport-sync#34] opened 2015-01-24 18:07 UTC
I love this little application that makes my raspberry pi very useful. However with the latest version installed as a service (the only one I've tried I sometimes get the error: shairport-syng is beeing used by someone else. Even though I am the only one using it. Sometimes a service restart works and sometimes I have to restart the raspberry pi. Sometimes that even does not work.. I can't seem to find any log.. Can you help me?

**Comment by mikebrady** [comment] 2015-01-24 21:40
Thanks for your report. Can you tell me what version of Linux you are using on your Raspberry Pi – is it Raspian, Arch Linux or something else? Also, where do you see this message – is it on your iPhone / iTunes?

**Comment by dhojgaard** [comment] 2015-01-24 22:17
I am using Raspbian, and i am seeing the message in my iphone...

**Comment by mikebrady** [comment] 2015-01-25 18:33
Thanks. Sometimes this is caused by a faulty WiFi network and by a network having multiple access points. When the iPhone connects over one AP and then roams to another, it sometimes looks like a new connection and causes the message to be sent – see https://github.com/mikebrady/shairport-sync/issues/8.

You can stop shairport-sync sending this message by setting the `-t` option to zero.

**Comment by dhojgaard** [comment] 2015-01-25 18:40
Actually I only have one AP.. So that can't be the problem. I just started shairport-sync with -v and at some point I saw: connection from iTunes.... Buy I know for sure that my phone was not connected and no PC with iTunes was connected.. When I tried to connect the output from terminal was: Already in use...Sent using CloudMagicOn søn., jan. 25, 2015 at 19.33,  mikebrady/shairport-sync <reply@reply.github.com> wrote:            Thanks. Sometimes this is caused by a faulty WiFi network and by a network having multiple access points. When the iPhone connects over one AP and then roams to another, it sometimes looks like a new connection and causes the message to be sent – see #8.

You can stop shairport-sync sending this message by setting the -t option to zero.

**Comment by mikebrady** [comment] 2015-01-25 18:44
Very mysterious. Are you really sure – it wouldn't report iTunes unless it was really happening, or unless some other program you have masquerades as iTunes – AirFoil for Windows, for example?

**Comment by mikebrady** [comment] 2015-02-16 11:32
Is it safe to close this?

**Comment by dhojgaard** [comment] 2015-02-16 13:00
YesSent using CloudMagicOn man., feb. 16, 2015 at 12.32,  mikebrady/shairport-sync <reply@reply.github.com> wrote:            Is it safe to close this?

**Comment by mikebrady** [comment] 2015-02-16 13:08
Thanks.

**Closed by mikebrady** 2015-02-16 13:08 UTC
