### ISSUE TITLE
Airplay sync problem 

### ISSUE THREAD

**Issue by Mikemansi** [mikebrady/shairport-sync#805] opened 2019-02-09 12:28 UTC
Hello Mike,

sorry to bother you with my request but I'm a noob and I can't figure out a silly problem with my apple tv 4k and my rasp.

Actually I get the audio from my appletv 4k using airplay with a raspberry pi2 with a iqaudio pi-dac+ running moode audio 4.4, it should come with your latest version of shairport-sync with bug fix for iOS 12 device and audio syncro. The iqaudio board is directly connected to my 2ch denon amplifier.

Unfortunately by my test made the audio is earlier for around 150ms/166ms and I'm not able to fix this by any of the apple tv settings.
What can I do? there are settings by ssh for made by myself the sync tune? 

I'll look for your help
thanks
Mike

**Comment by mikebrady** [comment] 2019-02-09 15:24
My guess is that the problem is caused by the Apple TV (ATV) taking about 150/166 milliseconds to process the audio. If that is so, then there is a setting in Shairport Sync's configuration file, normally at `/etc/shairport-sync.conf`, that you can use -- `audio_backend_latency_offset_in_seconds`.

So, for example, if the ATV delays audio by 150 milliseconds, set this to 0.15 so that the audio from Shairport Sync comes out at the same time.

Be careful to get the syntax exactly right!

**Comment by Mikemansi** [comment] 2019-02-09 17:41
Hi Mike thanks for the info, i fount the file shairport-sync.conf inside the path

/usr/local/etc/shairport-sync.conf

but now how can I write the command audio_backend_latency_offset_in_seconds ? I get command not found, surely the point is that I've 0 skills on programming

**Comment by mikebrady** [comment] 2019-02-09 18:16
Well, it's worth trying anyway.

What you need to do is edit that file. It's already got the setting `audio_backend_latency_offset_in_seconds` in it, but it's commented out and the setting's value is 0.0. 

You'll have to use a text editor like `vi` or `nano`, but you'll have to prefix it with `sudo` because the file can only be changed when you're in super mode. Thus, for example:

`$ sudo vi /usr/local/etc/shairport-sync.conf` will open the file for editing (don't type the `$` -- that's represents the command line prompt).

The line with the setting in it is a comment because it begins with `//`. That means it is ignored. Once  you have changed the setting from 0.0 to 0.15, remember also to remove the `//` from the start, because otherwise it will continue to be ignored. When you have successfully changed the file, save it and close it and reboot the machine; this is to get Shairport Sync to re-read the settings. Then see if it works.

**Comment by Mikemansi** [comment] 2019-02-09 18:54
I did it using the nano command and now everything seems fine. Thank you Mike for your great support (on Saturday!) have a nice weekend

**Comment by mikebrady** [comment] 2019-02-12 08:36
Hi Mike. Is it okay to close this issue?

**Comment by Mikemansi** [comment] 2019-02-12 09:03
Hi Mike,

yes I've solved the problem on Moode audio, but I'd like to ask you another thing, because I'm used to Volumio distro, I wasn't able to find the audio_backend_latency_offset_in_seconds command into it's file 
shairport-sync.conf.tmpl

this is the file, https://github.com/volumio/Volumio2/blob/master/app/plugins/music_service/airplay_emulation/shairport-sync.conf.tmpl

do you know where I can write the command about the latency here?

**Comment by mikebrady** [comment] 2019-02-12 09:06
I'm afraid I'm not familiar with how the Volumio guys have packaged up Shairport Sync -- best ask on their forum, I'd suggest.

**Comment by Mikemansi** [comment] 2019-02-12 09:07
Ok never mind, you can close this issue and thank you again for your great support!

**Closed** 2019-02-12 09:08 UTC
