### ISSUE TITLE
Volume reverts to previous level when streaming program temporarly loses the connection and then reconnects

### ISSUE THREAD

**Issue by wokawoka** [mikebrady/shairport-sync#511] opened 2017-04-16 16:10 UTC
Hello Mike. Great project, thank you very much for your work!!

Finally I decided myself to find the time to build up a new setup in my house for multiroom audio so this weekend I finally started to put everything together. At the moment I'm simply using some raspberry pi zero boards together with some decent sounding usb speakers I bought for the porpose.
My aim is to be able to control the volume in the different rooms from both the streaming software and directly from the volume buttons on the usb speakers when I'm near them.
In order to achieve that I set up a triggerhappy service on each raspberry pi installation that is monitoring the button events of the usb speakers and correctly changing the volume on the PCM mixer.
I believe to have correctly indicated the same mixer in the config file of each shairport-sync installation commenting out the string "mixer_control_name = "PCM";".

Everything apparently seems to work pretty well: the audio is streamed perfectly in sync across the rooms and I can control the volume of the individual rooms without any problem. I can also see the voume level regularly changing on the alsamixer graph when I change the volume either from the streaming programs I'm using for the tests (airfoil on windows/mac or airaudio on android) or directly using the buttons on the USB speakers.

The only problem Im facing at the moment is that sometimes it happens that the volume level reverts to a different previous level, and it feels very unpleasant when the music suddenly becomes very loud while listening in the middle of the night...
This problem arises, whenever the wi-fi network get congested (something I will have to fix at the router level anyway) and some packets get lost or when I'm streaming from my phone and the wi-fi signal becomes weak because I moved away from the access point range. Immediately after the small gap of silence during a rebuffering or a resyncing, the volume level jumps to the level the I initially set on the streaming program even if that level was set many hours before and in the meantime I have changed the level trough the speakers buttons.
It's like that the changes I do to the volume mixer from the USB buttons (but I imagine that it would be the same if I change the volume from the command line) are always overwritten by the one that the streaming program sends again after any reconnection. 

The thing is that I'm not experiencing the same problem with some other Pioneer airplay receivers I have here in my apartment. Whenever a reconnection or a resync happens they keep the last volume level I set from their buttons even if the volume level on the streaming program is different which make me think that either they communicate the volume level to the streaming program after any change (but I don't think so), or they just keep the last volume level after a reconnection even if the streaming program is sending a different volume value, which is the result I would like to achieve with shairport-sync as well.  

I'm running shairport-sync 3.0.2 compiled with "OpenSSL-Avahi-ALSA-soxr-metadata-sysconfdir:/etc" parameters.

I'm really sorry if I was too long! Any suggestion would be helpful. Thank you very much again and keep up with the good work!!!
W.

**Comment by mikebrady** [comment] 2017-04-16 17:06
Thanks for the interesting post. I've been doing some work that may indirectly affect your situation. Would you be kind enough to switch to the `development` branch please? Then if you could let me know if the problem continues we can explore it further.

**Comment by wokawoka** [comment] 2017-04-17 23:11
Alright Mike, I'll try to let you know tomorrow.
Thank you again.

**Comment by mikebrady** [comment] 2017-04-18 16:22
Help again. I've been thinking about this situation. When Shairport Sync reconnects and/or resyncs a play session, it always sets the volume, assuming it has control of the mixer. This is intentional behaviour, since it can't know what has happened to the mixer when it was off line. This interferes with you scheme, of course, where the mixer levels have been intentionally changed.

A possible solution is for Shairport Sync to refrain from controlling the mixer by instead using software volume control. The mixer would then be totally at the control of you `triggerhappy` service and Shairport Sync would never try to change it. Would that work? (The reference to the `development` branch above is because some of the code for releasing and retaking the audio output device and mixer has been updated, but on reflection, it doesn't seem to be relevant to your situation.)

**Comment by wokawoka** [comment] 2017-04-19 17:04
Hello Mike. Thank you for your new suggestions. 
Unfortunately I wasn't able to try the delopment branch yet as these days I'm not at home and travelling all the time. I was waiting to do it in order to write you back.

I did read carefully your last message and I did try to understand from your explanation how shairport sync is managing the volume level. But there's something that I'm still missing. 
It's clear to me that when shairport sync reconnects it always sets the volume. What I can't still understand is the part when you write that "this is intentional behaviour, since it can't know what has happened to the mixer when it was off line". 

The thing is that when I modify the volume (remotely from the streaming program, from the command line, from alsamixer, or via a triggerhappy script following a button event) shairport sync is indeed online and playing the music, and I was assuming that it could read the instant volume level of the mixer and take it as the new volume level.

If I've understood right I imagine that switching to the software volume control would prevent me to set the volume level in the different rooms directly from the slider of the streaming program (at the moment I'm doing some tests streaming with airfoil on windows/mac and airaudio on android).
In my case the ideal situation would be similar to the one I used to experiment with some pioneer airplay receivers I was using in the past. I was able to set their volume from both the streaming program and their hardware buttons and the volume always remained constant even after the quick disconnections/packet drops that were happening because of my congested wi-fi network. 

Maybe I'm asking too much but I like the idea of trying to find an alternative solution to this relatively small annoyance in order to fully enjoy the music system.
Just a random thought: if shairport sync is not able to "sense" a new level of the mixer set in a way other than the streaming program volume slider, wouldn't it be possible to have the triggerhappy service modify the level by passing the volume up/down/mute commands to shairport sync via a command instead to directly to the mixer? I imagine that this would solve the problem, assuming that something like this would be possible.

I'm open to any other suggestion and of course I will test the development releases as soon as possible.
Thank you very much again for your help and you time! 
W.

**Comment by wokawoka** [comment] 2017-04-26 23:25
Hello Mike! I was finally able to test the development branch (I'm on 3.1d8 now) and unfortunately the same problem with the volume arises as soon as the stream resync/reconnects. :(

I did also try to switch to the software volume control, as you suggested, but the max volume level is low (I imagine I should make some tests modifying the volume_range_db and volume_max_db parameters in the config file), but the real issue is that I can't change the volume consistently from both the streaming app and the hardware buttons (and now there are actually 3 volume levels involved (instead of 2): the music application volume, the shairport software volume and the alsamixer/hardware buttons one).
 
Assuming that there's no way to have shairport-sync to keep the same alsamixer volume level before and after resyncing/reconnections (if the volume was previously changed from alsamixer and not from the streaming program), do you think that it would be possible to find a way to pass to shairport-sync some commands from the command line in order to modify the volume (something like volume 5%+, 5%- and mute/unmute)?
This way it would be possible to circumvent the problem with triggerhappy directly talking with shairport-sync instead of alsamixer.... What do you think?

Thank you very much once again for your work (and your help)!

**Comment by mikebrady** [comment] 2017-04-27 10:52
Thanks for the update. 
1. When you use software volume control in Shairport Sync, the software volume is set by the music application, e.g. iTunes. Full software volume corresponds to full music application volume. The output of Shairport Sync then goes to the alsa device through the device's mixer, which can be controlled by `alsamixer` or by your `triggerhappy` script. So the final output volume is affected only by two volumes, not three; they are (1) the software volume controlled by the music application's volume and (2) the ALSA device's mixer volume, controlled by `alsamixer` or `triggerhappy`.
The low volume you report might be because the mixer volume was left low – use `alsamixer` or `triggerhappy` to change it.
It seems to me that this is the best solution for you given the capabilities of Shairport Sync. Shairport Sync will not interfere with the mixer volume control, so when it disconnects and reconnects it will merely set the software volume to what it should be.
2. Shairport Sync does not monitor the levels of the mixer to see if they have been changed. The working assumption is that Shairport Sync is in complete control of the mixer. If you want to change the output level, you do it at the music application.
3. Shairport Sync does not have a local interface – it's a daemon – so there's no interface in it to send commands to.
3. Some people have been working on remote control applications, which run on the same computer as Shairport Sync and send commands back to the music application. I think approach that might be worth exploring.

**Comment by mikebrady** [comment] 2017-04-27 12:34
Looking again at your thoughtful posts, it strikes me that we might be coming with different experiences. For instance, I have no experience of any AirPlay receivers apart from the AirPort Express base station, which has no local controls. Maybe AirPlay-equipped receivers allow you to change volume locally and have that reflected back in the music application's setting for that device.  Could that be true?

**Comment by wokawoka** [comment] 2017-04-27 19:18
Alright Mike, thank you for your reply.

To recap, this is my setup at the moment: I'm not streaming directly from a music program with airplay capabilities (such as itunes) but from streaming programs such as airfoil (on windows and mac) or airaudio (on android with root privileges). Those programs act in the system as a gateway and route the sound of a single application (any audio program) to many different airplay receivers and, most importantly, are able to control the audio of the airplay receivers individually through a volume slider. This last feature is very useful in a multiroom setup as you normally need different volume levels in different rooms (because of different room sizes, different hi-fi system used, ....). I uploaded a couple of screenshots that I did find online just in case you did not try them specifically before: http://imgur.com/a/Y24Oe .
I understand that using this kind of programs may be not the default user case but, judging from their popularity, I must be not the only one that is streaming with them.
For the last couple of years I have been using 3 Pioneer A4 XW-SMA4-K (which sound I don't like at all) without particular problems. In the past I also did use some bose soundlink airplay receivers without issues as well.
All of those speakers provide the possibility to adjust the volume level from their hardware buttons.
Whenever the connection temporarily drops or a resyncing happens they just mute for a while and then they just continue playing keeping a constant volume level even if the volume was previously altered from their physical buttons.
My guess is that they must have their own  internal "mixer" and that they are able to consider the last volume level set by the user indiscriminately via the streaming program (not the music player) or via their hardware buttons. 
I don't really know how the airplay protocol works, but my feeling is that they are not transmitting back their volume level to the streaming application, also because the volume slider on the application doesn't move whenever the volume is changed from the hardware buttons.
It might be that they are in a way able to prioritize the last volume level after any volume change and (maybe?) to discard the volume level sent by the streaming application each time after a reconnection (if the volume level is really sent each time after a reconnection. Again, I don't really know how the protocol works).

Coming back to my actual situation and to my efforts to finally replace these consumer plastic receivers with some raspberry pis running shairport-sync and some proper stereo loudspeakers, I did some tests with shairport-sync set with the software volume control, as you suggested.
Now I'm clearly not experiencing any volume "jump" after the resyncing, but with this setup the volume levels involved (as I'm not streaming from itunes or an ios device to some receivers that are playing at the same volume level) are indeed 3: 
1) the music player application volume level (that in a multiroom setup should be kept always at a constant level, as it affects the level of all the different receivers at the same time)  
2) the volume sliders of the receivers shown on the "gateway" application that is routing the music player output to them. 
While before switching to the software volume control I could move the alsamixer level of any of the raspberry pis detected by the streaming application directly from the slider shown near their name, now the slider is still present and it somewhat attenuate the sound level but, obviously, it is not able to increase the final volume level whenever the alsamixer volume level is too low.
3) the alsamixer volume level of the single raspberry PIs , which now is only controlled by the hardware buttons through the triggerhappy script.
Unfortunately this setup limits the possibility to properly control the volume in a consistent way from the software (and eventually oblige the listener to move and increase the alsamixer level from the hardware buttons whenever the alsamixer volume was previously set to a level that is too low).

I perfectly understand that my setup is a bit more complex than the average user case (and that most of the people in my case would either keep using some commercial receivers or even buy some overpriced sonos gear), but considering that shairport-sync is already offering a great degree of options and complex tweaking possibilities I really think that being able to sort out this wierd glitch would benefit other potential users as well and concur to the general completeness of this great peace of software.

If monitoring the levels of the mixer to see if they have been changed would be not viable or too complex to achieve, may it by chance be possible to just discard the old volume level sent again by the streaming application after a resyncing (or, in case the protocol works in a different way, just not to set again the volume after a resyncing )?

Consider me always ready to test any development or test version in the eventuality that you decide to investigate further and to look for a workaround.

Thank you very much once again for your nice work.
W.

**Comment by mikebrady** [comment] 2017-04-28 18:54
Thanks for that. Let me think it over a bit.

**Comment by mikebrady** [comment] 2017-04-30 09:28
So, I think it should be fairly straightforward to change the behaviour of Shairport Sync so that, rather than actively set the volume every time play is started or resumed, that it will only do so when play is started or when the volume is changed by the music application. It might take a little time.

**Comment by wokawoka** [comment] 2017-04-30 14:43
It would be great. Take all your time. Thank you very much once again

**Comment by mikebrady** [comment] 2017-04-30 18:10
I've just pushed an update – 3.1d9 – onto the `development` branch which you can access via a `git pull`. It avoids needlessly [re]setting the volume during resyncs. Could you see if it's working for you, please?

**Comment by wokawoka** [comment] 2017-04-30 22:19
I updated to 3.1d9 but unfortunately I'm experiencing the same behaviour with the volume after the resyncs.
I can imagine that it should be easily reproducible with a generic setup as well: I'm actually testing it by lowering the level of alsamixer via the commandline; whenever the resync happens (I can easily trigger it by moving in a spot of my flat where the signal is a bit weaker) the sound level always come back to the higher one that was previously set by the streaming application. 
I'm always ready to test any other version, I wish I could help doing more than that.
Thanks

**Comment by mikebrady** [comment] 2017-05-01 07:39
Oops, sorry. I forgot to add the final little change to make the fix permanent. It's in 3.1d10 now. I test is using `alsamixer` by starting a play from iTunes, changing the volume with `alsamixer` and then pausing and quickly restarting the music in iTunes. Prior to 3.1d10, the volume would be reset upon resumption.

**Comment by wokawoka** [comment] 2017-05-01 08:33
Unfortunately I'm experiencing the same behaviour after resyncing with version 3.1d10 as well :(

**Comment by mikebrady** [comment] 2017-05-01 09:16
Most peculiar. I hope you don't mind me asking the obvious questions, please. Are you certain that it's 3.1d10 that's actually running? What I'd be doing is, first of all, stopping the Shairport Sync service with `$ sudo systemctl stop shairport-sync`, then going to my build directory, pulling the update, doing the `$ autoreconf -fi` followed by the `$ ./configure...` stage  and finally the `$ make` stage.  Next, I'd check the version with `$ ./shairport-sync -V`; I'm getting `3.1d10-OpenSSL-Avahi-ALSA-soxr-sysconfdir:/etc`. Then I'd be running Shairport Sync from the command line with level 1 debugging: `$ ./shairport-sync -v`

I'm able to use `alsamixer` to change the volume, then pause and resume in iTunes without affecting the output level.

You could also uncomment line 963 of audio_alsa.c which will give you a level 1 debug message whenever Shairport Sync actually does change the mixer volume.

**Comment by wokawoka** [comment] 2017-05-01 10:39
Yes, I'm running 3.1d10-OpenSSL-Avahi-ALSA-soxr-metadata-sysconfdir:/etc .
I did uncomment the line 963 and now I can clearly read `Alsa volume actually set.` on the level 1 debugging output whenever I modify the volume level through the slider on the streaming program.

The strange thing is that whenever a resync happens I clearly read lines like (those are many different resyncing episodes that got logged within a half an hour time) :
```
Lost sync with source for 4 consecutive packets -- flushing and resyncing. Error: -2249.
Lost sync with source for 4 consecutive packets -- flushing and resyncing. Error: -2758.
Lost sync with source for 4 consecutive packets -- flushing and resyncing. Error: -4032.
Buffers exhausted.
Lost sync with source for 4 consecutive packets -- flushing and resyncing. Error: 46724.
Lost sync with source for 4 consecutive packets -- flushing and resyncing. Error: -5442.
Lost sync with source for 4 consecutive packets -- flushing and resyncing. Error: -2490.
Lost sync with source for 4 consecutive packets -- flushing and resyncing. Error: -2272.
Lost sync with source for 4 consecutive packets -- flushing and resyncing. Error: -2632.
Lost sync with source for 4 consecutive packets -- flushing and resyncing. Error: -4344.
Lost sync with source for 4 consecutive packets -- flushing and resyncing. Error: -5550.
Lost sync with source for 4 consecutive packets -- flushing and resyncing. Error: -5199.
```
but after each resync the volume (if it was previously modified via alsamixer while the music was playing) reverts to the old value initially set in the streaming program wthout any ` Alsa volume actually set.` message .

**Comment by mikebrady** [comment] 2017-05-01 11:19
Many thanks for this. I'm a bit stumped on that. On the few resyncs I've experienced due to congestion on the Internet stalling an internet radio feed, it works as I expected. There is nowhere else in the code where volume is set, as far as I can see. I'll continue to experiment. I don't suppose it could be caused by another program monitoring the settings?

**Comment by wokawoka** [comment] 2017-05-01 11:46
I'm testing on a pretty vanilla raspbian installation. If I'm not worng I did just add shairport-sync and triggerhappy to the clean system so I'm pretty sure there shouldn't be any other programs interfering.

Wouldn't it be possible that in your case the internet radio was rebuffering the data that was receiving but the connection with shairport-sync was fine so that shairport-sync was not resyncing in the same was does quite easily here (so that each time I can read the `Lost sync with source for 4 consecutive packets -- flushing and resyncing.` error) ?

There's no rush so take all the time you need, and if you need more logs I'm more than ready to try to help.
Thanks!

**Comment by wokawoka** [comment] 2017-05-01 11:48
I also just tested after having killed triggerhappy and some other processes that could interfere but the situation did not change

**Comment by mikebrady** [comment] 2017-05-01 12:36
Hmm. Clutching at straws here – do you have `run_this_before_play_begins` or `..._ends` procedure installed? I can't even see how they might affect things, TBH, but *something* odd is happening.

**Comment by wokawoka** [comment] 2017-05-01 12:54
No, I did not specify any run_this_before_play_begins or ..._ends parameter in the config file.
The only parameters that I included in the config file are:
```
general=
name = "raspzero1"
log_verbosity = 1;

metadata=
enabled = "yes";
include_cover_art = "yes";

alsa=
mixer_control_name="PCM";
```
and nothing else.
It could be eventually interesting to ask to some other user to do the same test as well.
If this behaviour should not present itself according to shairport-sync's code, I'm starting to doubt that could be something on my side. If needed I could eventually clean reinstall raspbian on the raspberry pi zero and retest, just let me know if you have any suggestions about that.

**Comment by mikebrady** [comment] 2017-05-01 13:00
A clean install might be the quickest way to proceed. But I am mystified by the whole thing – what entity could possibly remember the old settings, apart from Shairport Sync itself?

**Comment by mikebrady** [comment] 2017-05-01 13:02
A quick question. Are you using`alsamixer` to change the volume or are you using a different program? I know you are monitoring things with `alsamixer` alright...

**Comment by mikebrady** [comment] 2017-05-01 13:04
BTW the internet congestion I get causes the same `Lost sync...` messages, so AFAIK it would be treated the same way...

**Comment by wokawoka** [comment] 2017-05-01 13:14
From my point of view the only entity that could remember the old volume setting is the streaming program itself (today I'm using airaudio on android as I can trigger the resyncs more easily from my mobile), that may actively try to reconnect to shairport-sync using the only volume level it knows.
If I reboot the raspberrypi while the program is streaming music to it, sometimes, as the boot cycle has finished and the airplay speaker of shairport-sync is again visible, it reconnects by itself and continue to play the music.
The thing is that there are no volume jumps using the same programs with my pioneer airplay speakers.

Yes, I'm using alsamixer to monitor and to change the volume level as well (up or down arrow)

**Comment by mikebrady** [comment] 2017-05-01 13:18
Thanks. If AirAudio was actively setting the volume with the AirPlay protocol, it should show up as an actual volume adjustment. I'll keep looking...

**Comment by mikebrady** [comment] 2017-05-01 13:22
Another quick question. Rather than rely, as it were, on a network problem, what happens if you pause the output, do a quick volume change with `alsamixer` and then resume, does it leave the volume as if was or does it reset it? In my case, it doesn't change the volume.

**Comment by wokawoka** [comment] 2017-05-01 13:24
Yes, that's right, the strange thing is there are absolutely no messages of volume adjustment after the resync and the volume jump.
I just tried once again to stream from Airfoil on windows and I'm experiencing the same behaviour seen with Airaudio

**Comment by wokawoka** [comment] 2017-05-01 13:39
Actually there's no way to pause the output here, in this moment I'm feeding the audio from spotify to airfoil which is streaming, but the two programs are not really aware of each other. The only thing that I can do is to connect or disconnect to shairport-sync from Airfoil (if I pause Spotify I imagine that Aiaudio keep streaming silence).
If I disconnect the shairport-sync speaker from the Airfoil interface, change the volume level from alsamixer, and then reconnect, the volume level get reverted to the one that Airfoil was previously using which is also the only volume level that Airfoil knows (the volume slider on Airfoil's interface never moves when I change the mixer level with alsamixer)

**Comment by mikebrady** [comment] 2017-05-01 13:51
I presume you mean "Airfoil" where you write "Aiaudio" above?

**Comment by mikebrady** [comment] 2017-05-01 13:53
I guess in the scenario above you should see the "actually" message when you reconnect Airfoil. Is that indeed so?

**Comment by wokawoka** [comment] 2017-05-01 14:23
> I presume you mean "Airfoil" where you write "Aiaudio" above?

Yes, I was meaning Airfoil, sorry.

> I guess in the scenario above you should see the "actually" message when you reconnect Airfoil. Is that indeed so?

Yes, whenever I reconnect Airfoil I always get the big chunk of messages that I receive each time I connect to shairport-sync and among them I can read "Alsa volume actually set".

In the meanwhile I also downloaded and installed Itunes (but I'm on a windows machine at the moment!) and I'm experiencing the same problems seen with Airaudio and Airfoil. The volume jumps as soon as a resyncing happens and it also get reverted to an old value (after having changed it with alsamixer while it was playing) immediately when I press the pause button on itunes (even before pressing the same button to start playing again).   

A very interesting thing that I noticed while I was streaming from itunes to one of my pioneer players is that whenever I change the volume level from the hardware buttons on the unit the volume slider on the itunes interface is moving as well, so obviously the players are transmitting back the volume change to itunes through the protocol itself (I haven't installed any control program of any sort for the stand alone players).

**Comment by mikebrady** [comment] 2017-05-01 14:54
Thanks for the interesting information, both about iTunes resetting the value upon pause (!) and also about the Pioneer behavior. I'll keep digging away here, see if I can find anything to account for it.

**Comment by mikebrady** [comment] 2017-05-02 09:51
Hi there. I think I've found something associated with the interplay between using hardware mute and the volume control. Here is a quick check you could try, to see if my prediction is correct: if you disable hardware mute by setting the new setting `mute_using_playback_switch` to `"no"` in the `alsa` stanza, does the volume-restoring problem go away? 

I'm testing on an RPi with its built-in audio.

Previously, I've been testing on a system where I disable the hardware mute, hence not seeing the issue. I still don't know what might be causing it (it might even be the ALSA subsystem being "smart"), but I'll find out.

**Comment by mikebrady** [comment] 2017-05-02 10:36
Okay, so I think I see what's happening. If a mixer is selected, Shairport Sync opens an instance of the mixer when it starts playing and closes it when play stops. The instance obtains the state of the mixer when opened and updates it whenever Shairport Sync does something to it, but it does not respond to any of the changes that might be made to mixer externally. I think that what should happen is that a mixer instance should be created, used and closed on demand. I'll see if I can do that.

**Comment by wokawoka** [comment] 2017-05-02 12:07
I confirm you that adding the line `mute_using_playback_switch = "no";` to the config file was enough to fix the volume restoring issue. That's great! Thank you very much.

I still have to do some more tests (I'm no more at home at the moment) but, if disabling the hardware mute doesn't bring any big disadvantage, the actual result of this line in the config file would be more than enough for me.
Of course I would be eventually still ready to help you testing any other new modification to how shairport-sync manages the mixer istance.

Just a side question: the usb speakers I'm using at the moment (connected to the raspberry pi zero with shairport-sync running on it) have a status led that starts to blink whenever the mixer is muted. 
Recently I noticed that very often, whenever a listening session via shairport-sync did finish and the streaming program was disconnected (so that probably shairport-sync in some minutes was free again to receive a new stream from another transmitter) the status led used to start to blink (so that I was assuming that shairport-sync was muting the mixer while waiting for a new stream).
I've noticed that after the  `mute_using_playback_switch = "no";` addition to the config file the led is not blinking anymore in the same situation but, strangely, the mixer remains at the old level (I was expecting to find it not muted but at 0 level). 
I also have noticed that whenever I boot the raspberry pi the mixer still get muted after the boot sequence finishes (and the shairport-sync service get loaded) even if the hardware mute is now disabled. Is this behaviour normal?

Thank you very much again,
W.

**Comment by mikebrady** [comment] 2017-05-02 14:59
Thanks are due to you too, for your help and patience!

When you say that it "remains at the old level", I'd expect that it would, as Shairport Sync just relinquishes it.

The muting after boot is not something I'd have expected – I'll look into it.

**Comment by mikebrady** [comment] 2017-05-02 15:32
I'll be pushing an update Real Soon Now (RSN) which should deal better with the ALSA mixer. I haven't seen where the initial mute might be coming from, but I'll keep looking.

**Comment by wokawoka** [comment] 2017-05-02 15:46
Great, I look forward to test the update.

I'm not completely sure about the muting, and it might not be triggered by shairport-sync itself. 
From what I remember I was not experiencing any  hardware "auto" muting of any sort (at boot or after disconnection) while I was using the stable version of shairport-sync so the muting issue could have been introduced by the changes you did in the development version, but I'm not really sure, I should do some more tests by installing back the stable version and compare

**Comment by mikebrady** [comment] 2017-05-02 16:29
A quick check on a Pi shows that the machine starts with the sound card in the same stater as it was when it was last [cleanly] powered down.

**Comment by mikebrady** [comment] 2017-05-02 16:58
Just pushed out 3.1d11 with changes to open and close the mixer when needed rather than all through the play session. So, the volume should not be changed by hardware-supported mute/unmute.

**Comment by wokawoka** [comment] 2017-05-02 18:40
Great Mike, thank you so much for the new version you pushed!

I was just able to do some tests to try to understand the mute issue and this is what I'm experiencing here: if the hardware mute is enabled, whenever I disconnect from shairport-sync with any of the streaming programs I'm using (Airfoil, Airaudio, Itunes on windows) alsamixer gets immediately muted (and the led on the speakers starts blinking). As soon as I connect again the mixer get unmuted and so on (this doesn't happen if the hardware mute is disabled). 
As you wrote a couple of comments ago if I reboot or shutdown the raspberry pi while the streaming program is disconnected (so that the mixer was previously muted) the machine will restart muted (just because it was the previous state before the shutdown, as you made me notice), the same happens if I reboot the pi while the program is streaming to shairport-sync and the music is playing (and again that doesn't happen if the hardware mute is disabled). Apart from the speakers leds blinking all the time around the house whenever they are not playing this doesn't represent a problem for me and probably this has to be considered the right behaviour.

I also tested the new version you just pushed. Everything finally works great without any volume problems, thank you so much!
The only minor issue that I was able to notice (when the hardware mute is enabled) is that whenever I slide down the volume to the minimum from the streaming program the mixer gets correctly muted but if I try to unmute and increase the volume from the alsamixer I'm not able to hear any music even if the volume increases. 
The opposite instead works ok: if I mute from alsamixer I can unmute the music correctly from the streaming program and keep listening. 
I consider it a minor issue but I thought that it could have been interesting to point it out to you.

Thank you a lot once again!

**Comment by mikebrady** [comment] 2017-05-02 21:52
Thanks. I'll have a closer look at that last issue.

**Comment by mikebrady** [comment] 2017-05-03 20:52
I located that issue – it was a kind of a feature, but I think it's no longer necessary, so I'm removed it. Anyway 3.1d12 removes the anomaly, I believe.

**Comment by wokawoka** [comment] 2017-05-04 08:11
Yes! Thank you so much Mike! 
I'm streaming to shairport-sync right in this moment and there are no volume jumps after resyncs, I can also mute from the streaming program and unmute from alsamixer. That's just great.

The only new thing that I'm noticing now (but that is not affecting the listening itself!) is that the mixer is now for most of the time in mute state (I can realize it from the led blinking). Actually it's like it's always mute by default except when shairport-sync is playing some music. 
I've noticed that it even switch to mute by itself about 25 seconds after I put the music on pause (even if the stream is still connected). If I shutdown or reboot the pi after a restart the mixer always come back muted. 
I thought to report it to you since I don't remeber this behaviour in the stable version that I was initially trying. Is this a new feature added on purpose?

A huge thank you once again for this last version with which I'm now finally enjoying a lot of good music :)

**Comment by mikebrady** [comment] 2017-05-04 15:41
Thanks. The mute thing is a reflection of the assumption that Shairport Sync really has the sound card to itself. In such a situation, muting is probably the right thing, to absolutely minimise the possibility of any noise while the system is meant to be silent. I can appreciate that is might cause problems if the sound card is being shared, and in that case, I suppose the best thing is to disable hardware muting with the `mute_using_playback_switch` setting.

The 25 second thing is coming from the music application: if you pause for long enough, the play session is terminated, causing Shairport Sync to mute the output. I think the time delay is a good bit less if the application is iTunes.

I've pushed another update to tidy up some problems with the relationship between volume, mute and hardware support for mute, and I will have to tidy this up before release. Probably change the `mute_using_playback_switch` to something like `use_hardware_mute_if_available` or something.

**Comment by wokawoka** [comment] 2017-05-05 10:57
I'm testing the new version you pushed (not using the `mute_using_playback_switch` option ) and everything works as expected!
I can easily get used to the leds blinking around the house (when the speakers are not playing), the most important thing is that now the volume works just great so I can listen to a lot of good music.

I also tested with the ` mute_using_playback_switch = "no"; ` setting in the config file but again I was not able to unmute shairport-sync from alsamixer after having muted it via the volume slider on the streaming program (and obviously, as expected, from the program after having muted with alsamixer). No problem here, I will continue using shairport-sync using the hardware mute.

Maybe one day it would be great to have shairport-sync to send back the information of the volume level of the mixer to the streaming program (the same way I suppose my Pioneer and hardware airplay  receivers are talking to itunes), but I guess that this would be just a cosmetic addition that would not provide any real value (and probably also difficult to achieve).

I'm very grateful to you for your work and your immense patience!
I look forward your next stable release. Thanks again!

**Comment by mikebrady** [comment] 2017-05-05 13:05
Thanks – I'll explore that remaining issue your testing has identified.  You are right about communicating back to the music application – I'll put it "on the list".

Do you think it would be appropriate now to close this issue?

**Comment by wokawoka** [comment] 2017-05-05 13:21
Sure, I kept commenting just because I thought that I could try to give my contribute testing your changes but I hope that it didn't look like I was demanding too much.

I think that after a total of 50 comments the time to close the issue has come :)
Again, I was not expecting such a degree of care and devotion to this project from your side.
Thanks again and keep up the good work!

**Comment by mikebrady** [comment] 2017-05-05 13:27
Understood. And thanks again.

**Closed by mikebrady** 2017-05-05 13:27 UTC

**Comment by mikebrady** [comment] 2017-09-01 08:28
Hi there. A quick question: in the current Shairport Sync — 3.1.1 — the default for the `mute_using_playback_switch` setting is  `“yes"`, and it’s been suggested that it should default to `“no”`. Would you have any thoughts on the matter? Would it be a bad thing?
