### ISSUE TITLE
have only sound on one side on Synology 

### ISSUE THREAD

**Issue by 1981Erik** [mikebrady/shairport-sync#300] opened 2016-05-16 07:54 UTC
Im using shairport-sync 2.3.11-2 on my synology with synology audio USB adapter.
Since the last update of DSM 6 i have only sound on one side. (DS Audio is working properly)
I have uninstalled shairport rebooted the NAS and installed it again. and done this in diffrent setups, with DS audio installed and without and so on. But no results for so far.
Is there a solution for this issue?

Model: DS112+ Firmware: DSM 6.0-7321 Update 6, shairport-sync 2.3.11-2

**Comment by mikebrady** [comment] 2016-05-16 07:58
Thanks for the report – I've not come across this issue before, and it is really bizarre, because both channels are transported and processed at the same tie.. Have you set up Shairport Sync to control a hardware mixer? If not, then use something like `alsamixer` to check the levels.

**Comment by jmadlun** [comment] 2016-06-05 04:04
I will echo Erik's post.  I have the Synology brand audio dock/remote and audio is now only going to one speaker.  I used your shairport-sync.conf sample file and tried tweaking some of those settings but I am not exactly confident with what I am doing.  When you suggest setting up Shairport Sync to control a hardware mixer, is that done in the alsa settings of that .conf file?  If you can point me in the right direction for what to change, I am OK doing some trial and error.  I tried some of the alsamixer terminal commands when logged into my Synology NAS but it doesn't seem to recognize these so I am not sure how to interact with it.  I did turn on my Synology Audio Station log and it output what I believe represent the name of the mixer:

{
   "collector_version" : 2,
   "global_config" : {
      "aactranscoding" : true,
      "aifftranscoding" : true,
      "audio_default_equalizer" : "Rock",
      "audio_disable_upnp" : true,
      "audio_enable_download" : true,
      "audio_enable_equalizer" : true,
      "downsample_audio_transcoding" : true,
      "enable_alsa" : true,
      "enable_audio_transcoding" : true,
      "enable_diagnosis" : true,
      "enable_personal_library" : false,
      "flactranscoding" : true,
      "oggtranscoding" : true,
      "personal_library_indexable" : true
   },
   "lyrics_plugin" : [
      {
         "enable" : true,
         "name" : "fujirou_lyric_wiki"
      },
      {
         "enable" : true,
         "name" : "fujirou_metro_lyrics"
      },
      {
         "enable" : true,
         "name" : "fujirou_musix_match"
      }
   ],
   "multiple_remote_player" : {
      "total_multiple_airplay" : 0,
      "total_multiple_bluetooth" : 0
   },
   "package_version" : "5.5-2985",
   "remote_player" : {
      "airplay" : [
         {
            "model" : "",
            "name" : "Living Room Speakers",
            "txt" : "\"pw=false\" \"txtvers=1\" \"vn=3\" \"sr=44100\" \"ss=16\" \"ch=2\" \"cn=0,1\" \"et=0,1\" \"ek=1\" \"sm=false\" \"tp=UDP\""
         }
      ],
      "bluetooth" : [],
      "upnp" : [],
      "usb" : {
         "interface" : "C-Media INC. USB Sound Device at usb-ehci-platform.0-1.1, full speed : USB Audio\n\nPlayback:\n  Status: Stop\n  Interface 1\n    Altset 1\n    Format: S16_LE\n    Channels: 2\n    Endpoint: 6 OUT (ADAPTIVE)\n    Rates: 44100, 48000\n",
         "mixer" : "USB Mixer: usb_id=0x0d8c0103, ctrlif=0, ctlerr=0\nCard: C-Media INC. USB Sound Device at usb-ehci-platform.0-1.1, full speed\n  Unit: 13\n    Control: name=\"Loudness\", index=0\n    Info: id=13, control=10, cmask=0x0, channels=1, type=\"BOOLEAN\"\n    Volume: min=0, max=1, dBmin=0, dBmax=0\n  Unit: 13\n    Control: name=\"PCM Playback Volume\", index=0\n    Info: id=13, control=2, cmask=0x3, channels=2, type=\"S16\"\n    Volume: min=-9473, max=-1, dBmin=-3700, dBmax=0\n  Unit: 13\n    Control: name=\"PCM Playback Switch\", index=0\n    Info: id=13, control=1, cmask=0x0, channels=1, type=\"INV_BOOLEAN\"\n    Volume: min=0, max=1, dBmin=0, dBmax=0\n",
         "name" : "C-Media INC. USB Sound Device",
         "pid" : "0103",
         "rev" : "0.10",
         "vid" : "0d8c"
      }
   },
   "statistics" : {
      "playlist" : {
         "total_personal_playlist" : 0,
         "total_shared_playlist" : 2,
         "total_sharing_playlist" : 1
      },
      "rating" : {
         "total_rating" : 1,
         "total_user_has_rating" : 1
      },
      "total_album" : 837,
      "total_artist" : 447,
      "total_composer" : 1950,
      "total_genre" : 61,
      "total_replaygain" : 0,
      "track" : {
         "total_actual_track" : 8883,
         "total_personal_track" : 0,
         "total_shared_track" : 8883,
         "total_virtual_track" : 0
      }
   },
   "user_config" : {
      "total_browse_personal_lib" : 1,
      "total_choose_transcode_wav" : 0,
      "total_not_show_virtual_lib" : 1
   }
}

**Comment by mikebrady** [comment] 2016-06-06 18:23
Thanks for the comprehensive report. It's really an odd situation. What I'd like to do is check if the problem lies with Shairport Sync or with the system. Apologies if you've done all these things already...

First, if you launch `alsamixer`, do you get a screen something like the following:

![screen shot 2016-06-06 at 19 20 08](https://cloud.githubusercontent.com/assets/4265913/15832831/e394bb6a-2c1b-11e6-80a9-5975d49fd8d2.png)

If so, perhaps the utility `speaker-test` is installed; if not, it's in the Linux `alas-utils` package.

If it's installed, it should allow you to check the speakers together and individually.

**Comment by mikebrady** [comment] 2016-06-06 18:35
You asked: 

> When you suggest setting up Shairport Sync to control a hardware mixer, is that done in the alsa settings of that .conf file.

Yes, that's exactly right. In the screenshot above, if looks like there is a mixer called "Master". To use it, you would write `mixer_control_name = "Master";` in the `alsa` section. Note that the double quotes are important, as is the semicolon. Also, make sure to uncomment the line (that is, take away the `//` characters at the start). You need to restart Shairport Sync to get it to use new settings.

If you've set it up correctly, when you alter the volume with, for example, iTunes, you'll see it changing in the `alsamixer` screen.

**Comment by jmadlun** [comment] 2016-06-09 04:20
Thanks Mike.  It seems to be a system problem (Synology) rather than Shaiport Sync; it is now playing from both speakers and I cannot seem to reproduce the issue.  I will keep experimenting.  Thanks again for replying, I appreciate the work you put into this.  Cheers.

**Comment by mikebrady** [comment] 2016-06-09 10:40
Thanks Jason.

**Comment by mikebrady** [comment] 2016-07-05 13:31
Jason, I'm going to close this issue, if that's okay. Feel free to reopen it if there are developments.

**Closed by mikebrady** 2016-07-05 13:31 UTC

**Comment by jmadlun** [comment] 2016-07-05 16:20
Sounds good, Mike, thanks for the note.
