### ISSUE TITLE
iTunes volume control is not a linear map to ALSA PCM volume control

### ISSUE THREAD

**Issue by wsanders** [mikebrady/shairport-sync#124] opened 2015-09-15 22:43 UTC
In oder to get any sound output at all, I had to set 'mixer_control_name = "PCM"' in the shairport-sync.conf file. In case this has not been noticed, when this is done the volume control in iTunes becomes synchronized to the PCM control in ALSA. To demonstrate this, open a terminal window and start alsamixer. Then start playing something through shairport-sync, and move the iTunes volume control to 0. You should see the alsamixer volume control go to 0. Likewise, move the iTunes volume control to 100, you should see the alsamixer volume control go to 100. From what little I know of the Airplay protocol, there is a control channel over which the volume setting is passed.

This may not even have anything to do shairport-sync, but for other volume settings the scale of the volume control slider in iTunes does not scale linearly to the PCM volume in alsamixer. For example:

iTunes volume setting: 0% -> alsamixer PCM volume 0 (muted)
iTunes volume setting: 25% -> alsamixer PCM volume 12 (barely audible)
iTunes volume setting: 50% -> alsamixer PCM volume 35 (very low volume)
iTunes volume setting: 75% -> alsamixer PCM volume 68 (about "normal")
iTunes volume setting: 100% -> alsamixer PCM volume 100 (too loud, overdrives amp)

If you reset your PCM setting with "alsactl restore" the next movement of the volume control with override the restored volume setting. This can counterintuitively make the PCM output volume go down if the iTunes slider is moved up, if you have set the initial PCM slider position to something higher than the initial position of the iTune volume slider at playback startup.

I don't know if any of this has to do with shairport-sync, but is it possible to adjust the mapping of the iTunes volume setting to the PCM volume setting, either via the shairport control channel, or in ALSA itself? This could be provided as a "preemphasis" option to shairport-sync, although an ALSA configuration fix would make more sense. I do see a message "Can't get dB value corresponding to a "volume" of 1." at shairplay-sync startup.

My setup is slightly unusual: Using a Raspberry Pi model B running "2.4-openssl-Avahi-ALSA-metadata" running "Raspbian GNU/Linux 7 (wheezy)". I am playing through the low-fi 3.5mm output jack. ITunes is 11.2.2 running on MacOS and "Music" app on iOS 8.4.1 - both iTunes clients behave the same way.

This issue may be the reason why there are numerous postings about shairport volume being generally faint. The listenable setting for a shairport device in iTunes is always few notches higher than other playback devices.

**Comment by wsanders** [comment] 2015-09-16 03:38
OK - I see how vol2attn works in common.c.  Perhaps I can work up a transfer function more suitable to the raspberry pi if I have time.

**Comment by mikebrady** [comment] 2015-09-16 06:28
Hi there. All you have described is actually meant to happen, so I'm not sure what the issue is. The low-fi output jack is a very bad yardstick to judge the transfer curve, TBH, and I'm not aware of the numerous postings you refer to. Having experimented with some pretty high quality audio systems for well over a year, I think the existing curve is pretty good.

**Comment by mikebrady** [comment] 2015-09-16 07:02
One thing I could do is to expose the parameters for that transfer curve – then people could try alternatives. What do you think?

**Comment by wsanders** [comment] 2015-09-16 15:34
Thanks for the reply Mike - if anyone else has mentioned this, exposing the
params would be OK. Or perhaps just one "pre-emphasis" parameter, that
shifts the whole function up X db. Very low priority. I was planning to
experiment with different parameters in the function, maybe not this week.

I was primarily interested in documenting the effect. I have the original
"shairport" (v 0.05) running on another pi and it does not sync the PCM
slider with the volume control in iTunes. I have set the PCM volume to "85"
on that Pi and it stays put regardless of the volume setting on the iTunes
host. So, with the iTunes slider set at some value, the volume is about the
same subjective "loud" when playing through that Pi as it would be playing
through speakers or headphones directly connected to the iTunes host.

If you wan't to mark as "won't fix" that's OK. Thanks for all your work on
this - It's an interesting and complex problem (except for the figuring out
ALSA part, which is kind of a chore, ha.)

w

**Comment by mikebrady** [comment] 2015-09-16 15:48
Cool -- actually nobody else has mentioned this as an issue, so it might take me a little while to expose and explain (!) the parameters.

BTW, if you don't specify the name of the volume control mixer, Shairport Sync will work like the original Shairport -- i.e. do nothing to the ALSA mixers at all, and do volume levels in software, but with a lag -- 0.15 seconds in Shairport Sync, much longer in Shairport.

**Comment by wsanders** [comment] 2015-09-16 16:22
Now that you mention it, I needed to specify the name of the volume control
mixer ("PCM") to get any sound at all out of the Pi. For now, I think that
it's an ALSA or Pi specific problem.

**Comment by mikebrady** [comment] 2015-09-16 16:47
Possibly not: If you don't specify the name of the mixer, its value is unchanged by Shairport Sync. If it happened to be low or zero, you'd hear nothing. You'd need to adjust it with e.g. `alsamixer`. Does that sound plausible.

**Comment by wsanders** [comment] 2015-09-16 21:22
I've been messing with ALSA that I'm not sure how if it's configured close
to its pristine state or not.

However - I just realized after looking at the comments in vol2attn() that
you are modeling the actual behavior of a real world log taper pot - you
probably know this already but real world log taper lots are made with two
strips of material that yield a curve that's actually two or three linear
regions just like your function. Cool ... I say don't change anything....

I'll try to find some parameters to the function that yield about -15db
attenuation at the midpoint of the iTunes slider and that should fix it for
my special case.

w

**Comment by mikebrady** [comment] 2015-09-16 21:28
Okay – I'll put a "Won't fix" on this. Please let me know how you do – it might be interesting to try your settings out.

**Closed** 2015-09-17 15:29 UTC
Labels: wontfix

**Comment by mihalski** [comment] 2015-10-04 06:04
I'm new to Shairport-Sync and I think I'm having a similar problem. I've hooked up a Turtle Beach Micro II USB adapter to my RasbPi and when using the hardware PCM volume control even the LOWEST volume is FAR too loud and it just goes up from there. Is this an ALSA problem? And if so is there anything I can do about it? Thanks.

**Comment by mikebrady** [comment] 2015-10-04 09:05
This seems to be the opposite problem -- the sound is too loud at low levels, not too quiet. Is this a review of it: http://nwavguy.blogspot.ie/2011/10/turtle-beach-micro-ii.html?

**Comment by mihalski** [comment] 2015-10-04 10:31
I think I've come across that (or a very similar review) before. The Linux driver has Loudness at 0 by default from what I can tell.. I'd previously been using only the optical output so I didn't really care much about the analogue quality. I do have another USB adapter which I will try to see how it fares.

**Comment by mikebrady** [comment] 2015-10-04 12:02
Fair enough. Another, more direct, thing to do is open alsamixer in a separate window and watch what happens to the PCM level when you change volume in iTunes, etc. If all goes well, it should make the PCM level go from its lowest possible value to its highest possible value -- it means that Shairport Sync has control of it, and that it can use its full range of attenuations...
