### ISSUE TITLE
Why is Shairport speaker being grouped with my Apple TV?

### ISSUE THREAD

**Issue by microfx** [mikebrady/shairport-sync#1358] opened 2021-12-03 13:30 UTC
Hey! 

Does anybody know if every AP2 device gets grouped together? This is not the way I want it …can I change this? I am really afraid of having a 3rd AP2 device (which I‘m planning to) 

here is what I‘m talking about - I always have to do one click more - if not my TV turns on (not intendet when listing to audio obviously): 

![FFED55ED-2188-4C3F-9DC5-250E39D624BF](https://user-images.githubusercontent.com/37987212/144610474-afc5a63f-3742-4f39-8621-97046abfc44f.jpeg)

Cheers!

**Comment by mikebrady** [comment] 2021-12-04 16:47
Thanks for the post. Grouping hasn’t been a problem for me. It is possible that the group of two loudspeakers in the screenshot were or are grouped together on another device? That’s what happens in my experience.

**Comment by microfx** [comment] 2021-12-04 17:50
Well, the Apple TV uses it to play...? Hmm... but why is Apple assuming I want to play it on both - always?

**Comment by mikebrady** [comment] 2021-12-07 12:42
So, this looks like a feature of AirPlay 2, not a bug 🙂.

**Comment by mikebrady** [comment] 2021-12-08 20:08
Okay to close this?

**Comment by microfx** [comment] 2021-12-08 20:16
hmmh yeah ... but if somebody knows something, I'd be happy if he shared it with me - undocumented feature / nothing to find on the interwebs. 

By the was ... I read a lot that you can put your AP2 devices into zones (in Home(kit)) - is that feature on some kind of wishlist  ... or even possible already?

**Comment by mikebrady** [comment] 2021-12-08 20:25
Thanks. I have a HomePod mini that does the same thing with grouping. I'm pretty sure it's a feature. When you think about it, it's probably what a normal user would expect.

Yes, you can add them to the Home app as accessories. In the Home app, when you do the "Add Accessory" thing, look under "Other Options..." (The wording is approximate -- my phone is not in English.) Then you can put them in rooms and scenes and stuff.

**Closed** 2021-12-08 20:26 UTC
Labels: question

**Comment by microfx** [comment] 2021-12-08 20:38
Hmm... where can I find the code to add? Or what's the next step?

**Comment by mikebrady** [comment] 2021-12-08 21:52
“Other Options”?

**Comment by microfx** [comment] 2021-12-08 21:56
![6A76D4DB-1CC8-4A63-BCAF-D4B062911773](https://user-images.githubusercontent.com/37987212/145290715-58551044-a80e-4b3a-a360-91bcbb9f72ef.png)

hmm... I suppose it be here? Should I create a new bugreport?

**Comment by mikebrady** [comment] 2021-12-08 22:08
I don't think so. What version is your phone iOS? 
![IMG_3097](https://user-images.githubusercontent.com/4265913/145291997-9b182983-5c96-4c38-90be-50475e4ded2f.PNG | width=300)

**Comment by microfx** [comment] 2021-12-08 22:36
hmm... I'm on 15.2 beta

**Comment by mikebrady** [comment] 2021-12-08 22:38
Thanks. I'm on 15.1. 'll wait for the full version to try it out.

**Comment by microfx** [comment] 2021-12-08 22:41
Full version is ready to install on my device ..will also try that

**Comment by mikebrady** [comment] 2021-12-09 21:27
That’s great news, thanks!
