### ISSUE TITLE
streaming form os x to shairport-sync disconnects between songs [Resolved]

### ISSUE THREAD

**Issue by nilsbecker** [mikebrady/shairport-sync#605] opened 2017-10-22 13:29 UTC
hi,

 i have shairport-sync running on volumio on a rpi3. i am able to connect from a macbook and stream successfully. however, only until the stream is paused. at the shortest pause, e.g. between song, the mac re-selects the internal sound output. it's as if the 'volumio' device becomes unavailable as soon as no stream comes in anymore? 

volumio 2.298
shairport-sync version
3.0.2-OpenSSL-Avahi-ALSA-soxr-metadata-sysconfdir:/etc
config file:
```
general =
{
    name = "Volumio";
    log_verbosity = 0;
    interpolation = "soxr";
};

alsa =
{
  //output_device = "plughw:1,0";
  output_device = "hifi88";
};

sessioncontrol =
{
  allow_session_interruption = "yes";
  run_this_after_play_ends = "/usr/local/bin/volumio stopairplay";
};

metadata =
{
    enabled = "yes";
    include_cover_art = "no";
    //pipe_name = "/tmp/shairport-sync-metadata";
    //pipe_timeout = 5000;
    socket_address = "226.0.0.1";
    socket_port = 5555;
};
```

**Comment by nilsbecker** [comment] 2017-10-22 13:32
now that i'm looking at the config: is the run_this_after_airplay_ends possibly the problem?

**Comment by mikebrady** [comment] 2017-10-22 14:52
Thanks for the post. What is the source of the audio? Is it iTunes on the MacBook, or have you made Shairport Sync the Output Device for the entire system? This is important, because iTunes does not end the play session and start a new one between tracks of a playlist, whereas when Shairport Sync is the chosen output device for the whole system, going from, for example, one YouTube video to the next in Safari causes a play session to end and a new one to begin. In that scenario, the `run_this_after_airplay_ends` application may become important.

Also, it might be worth disabling `allow_session_interruption` to see if it makes any difference (I don't think so, but worth trying nevertheless).

**Comment by nilsbecker** [comment] 2017-10-22 22:42
hi thanks for the reply. indeed i set the output for the system. i tried with spotify web player on firefox, and with the cog audio player. both switched back between songs. i could experiment with commenting the two lines out that yiu mentioned...

**Comment by mikebrady** [comment] 2017-10-23 06:37
Thanks. This behaviour of switching between songs is not something that Shairport Sync can control. I have no idea what the `stopairplay` does, I’m afraid, so I can’t advise you there. Maybe the Volumio guys can tell you... I wonder if there’s a corresponding `startairplay`?

**Comment by nilsbecker** [comment] 2017-10-23 08:34
ok. i did some web search to find out if this switching of outputs is normal behavior on os x for non-itunes but not much came up; i cannot imagine this would be expected behavior since it would make airplay quite useless outside itunes. so i assumed the airplay sinks are expected to somehow show that they remain available when no stream is playing... anyway, i'll post on volumio as well.

**Comment by mikebrady** [comment] 2017-10-23 09:38
Thanks. I think it would be incorrect to characterise AirPlay as "quite useless" in these circumstances. Instead, I think that it a situation that the Volumio guys haven't considered or encountered. Remember, the protocol has never been published, so we don't know whether the behaviour is "expected" or not. It makes sense to me, even if it is a bit awkward to deal with.

What I think is actually happening is that when an AirPlay source wants to play something, it starts a play session, plays the material and then ends the session. For iTunes, the session includes the entire playlist, without a break. For other sources, a session is just one track. Thus, some sources —  e.g. YouTube in Safari on a Mac — will open a session, play a single item, close the session and then immediately open a new session for the next item, and so on. This is fine if the AirPlay sink remains available, as Shairport Sync does and as Apple's own AirPlay devices do – they have absolutely no problem with this.

The problem seems to be that in a Volumio system, when a AirPlay session ends, the `airplaystop` script does something to prevent audio being heard when the next AirPlay session is immediately opened. I guess there should be a corresponding `airplaystart` script, but that's something they would know about.

**Comment by mikebrady** [comment] 2017-10-23 09:42
Re-reading your comments, I think that you might be using an older version of Shairport Sync. Recent versions have made considerable changes to Shairport Sync's behaviour in situations like this, so I suggest you make sure you are running the latest version – 3.1.3. I suggest you do this before anything else :)

**Comment by nilsbecker** [comment] 2017-10-23 09:50
thanks! i am using the shairport-sync version bundled with the most recent volumio, but i guess i can upgrade it by apt-get install? your explanations of what's happening make sense to me. it may well be that os x gets confused by some session-close action taken by volumio...

**Comment by mikebrady** [comment] 2017-10-23 09:57
You can get Shairport Sync's version by typing `$ shairport-sync -V`.

Actually, Shairport Sync was not handling the session-end situation correctly (because the protocol isn't published, we seem to have guessed wrong about it), causing OS X to drop the connection, and this has been fixed. I don't think the `apt-get` packages have been updated, so you might have to compile it yourself using the instructions here. Or you maybe worth asking the Volumio guys to do it...

**Comment by nilsbecker** [comment] 2017-10-23 21:39
fwiw i was using 3.0.3, see above.

**Comment by mikebrady** [comment] 2017-10-23 21:42
Duh, yeah, I see it now, thanks. The relevant update was in 3.1.1 to 3.1.3.

**Comment by nilsbecker** [comment] 2017-10-23 21:50
ok thanks. not sure how quickly i can build it myself, on volumio most of the prerequisites are not installed - i may also have to google some apt repositories to enable first.. would be easier if someone in volumio would give it a go...

**Comment by XavierDupessey** [comment] 2017-11-12 08:54
Hello!

I had the exact same problem with volumio2 (v2.296) installed on my old rpi1.
So I tried to update shairport-sync by running the following commands:

```
git clone https://github.com/mikebrady/shairport-sync.git --depth 1
cd shairport-sync 
sudo apt-get install dh-autoreconf autoconf libtool libdaemon-dev libasound2-dev libpopt-dev libssl-dev libsoxr-dev 
autoreconf -fi 
./configure --with-alsa --with-avahi --with-ssl=openssl --with-metadata --with-soxr --with-systemd --sysconfdir=/etc 
make 
sudo make install 
sudo systemctl daemon-reload 
sudo systemctl restart shairport-sync 
```

I now have the version: `3.1.3-OpenSSL-Avahi-ALSA-soxr-metadata-sysconfdir:/etc` and it seems to work well 😃  I tested with music played from spotify (Chrome), VLC and iTunes from my MacBook Pro (13-inch, Mid 2010) with OS X 10.11.6 (15G1611).

I still have some disconnections after one or few hours (maybe due to my wifi network) but no longuer after every song.

I think the problem is fixed in shairport-sync and the volumio team should just update it!

**Comment by nilsbecker** [comment] 2017-11-12 13:14
cool, thanks for figuring out the build procedure!

**Comment by mikebrady** [comment] 2019-10-24 10:29
Pretty sure this has been addressed in more recent versions of Shairport Sync! Closing this inactive issue. Please open a new one if necessary.

**Closed by mikebrady** 2019-10-24 10:29 UTC
