### ISSUE TITLE
Crash with version 2.9.1

### ISSUE THREAD

**Issue by joerg-krause** [mikebrady/shairport-sync#234] opened 2016-02-23 12:45 UTC
I am streaming from iTunes to four shairport-sync devices. Sometimes shairport-sync crashes without leaving a hint in the log:

```
RTP: Packets out of sequence: expected: 51602, got 51603.
Error -32 in delay(): Broken pipe. Delay reported is 0 frames.
Aliasing of buffer index -- reset.
RTP: Packets out of sequence: expected: 51832, got 51833.
Player: packets out of sequence: expected: 51314, got: 51826, sync error: 0 frames.
Lost sync with source for 4 consecutive packets -- flushing and resyncing. Error: -13473.
Flush requested up to 404219719. It seems as if 0 is special.
Process metadata with type 73736e63, code 70666c73 and length 0.
audio_alsa flush called.
```

This device played around 10 minutes until it crashed, but some devices are running for several hours.

Any ideas how to track down the issue?

**Comment by mikebrady** [comment] 2016-02-23 20:28
Yes, this is very interesting, and I suspect it might be a bug in Shairport Sync. To be precise, BTW, it doesn't look like Shairport Sync crashed, just that it "hiccuped". I'll have to think of a way of getting at it – maybe dump some more information when it happens...

**Comment by joerg-krause** [comment] 2016-02-23 22:25
I'm not sure what you mean by "hiccuped". Enlighten me :smile:

All I can tell is that there is no shairport-sync process running anymore.

**Comment by mikebrady** [comment] 2016-02-23 22:36
Fair enough – it must have died then; it just never said goodbye... 

"Hiccupping" would have been doing this and then continuing on...

**Comment by mikebrady** [comment] 2016-02-24 09:14
A quick question: are all the devices the same? I'm thinking of the DACs principally.

**Comment by mikebrady** [comment] 2016-02-24 09:15
Also, does this happen on any device in particular?

**Comment by joerg-krause** [comment] 2016-02-24 10:15
Yes, all devices are exactly the same. No, it does happen undetermined on any device. One device crashed after 10 minutes, another one after 12 hours. Unfortunatly, I'm not able to reproduce it for now...

**Comment by mikebrady** [comment] 2016-02-27 18:25
I've pushed a `new_queue` branch to gather information which has two changes:

1.  It calculates mean, standard deviation and max stats for inter-packet arrival times for audio packets, to try and get a handle on what's happening on the network.
2.  It does not request resends.

If you got an opportunity to try it out, I would be curious to see if anything unusual turns up. The figures I get are mostly like this:

```
Packet reception intervals: mean, standard deviation and max for the last 1000 packets in us:     7989.3,     3866.7,    30435.0.
```

and occasionally like this:

```
Packet reception intervals: mean, standard deviation and max for the last 1000 packets in us:     7939.3,    16003.4,   184427.0.
```

Once, when I got a resync, I got this:

```
Feb 27 18:13:54 raspberrypi2 shairport-sync[16371]: Packet reception intervals: mean, standard deviation and max for the last 1000 packets in us:     7982.0,     5429.0,    50366.0.
Feb 27 18:13:56 raspberrypi2 shairport-sync[16371]: CSeq: 53.
Feb 27 18:13:56 raspberrypi2 shairport-sync[16371]: User-Agent: iTunes/12.3.2 (Macintosh; OS X 10.11.3).
Feb 27 18:13:56 raspberrypi2 shairport-sync[16371]: Client-Instance: F18FE780B35CFD8D.
Feb 27 18:13:56 raspberrypi2 shairport-sync[16371]: DACP-ID: F18FE780B35CFD8D.
Feb 27 18:13:56 raspberrypi2 shairport-sync[16371]: Active-Remote: 2502662644.
Feb 27 18:13:59 raspberrypi2 shairport-sync[16371]: RTP: Packets out of sequence: expected: 8540, got 8544.
Feb 27 18:13:59 raspberrypi2 shairport-sync[16371]: RTP: Packets out of sequence: expected: 8557, got 8569.
Feb 27 18:13:59 raspberrypi2 shairport-sync[16371]: RTP: Packets out of sequence: expected: 8581, got 8583.
Feb 27 18:14:02 raspberrypi2 shairport-sync[16371]: Packet reception intervals: mean, standard deviation and max for the last 1000 packets in us:     8130.8,    34242.0,   915220.0.
Feb 27 18:14:03 raspberrypi2 shairport-sync[16371]: Aliasing of buffer index. Expected 9052, got 9052. Reset.
Feb 27 18:14:05 raspberrypi2 shairport-sync[16371]: Player: packets out of sequence: expected: 8540, got: 9052, sync error: 0 frames.
Feb 27 18:14:05 raspberrypi2 shairport-sync[16371]: ALSA lib pcm.c:7843:(snd_pcm_recover) underrun occurred
Feb 27 18:14:05 raspberrypi2 shairport-sync[16371]: Error -32 in delay(): Broken pipe. Delay reported is 0 frames.
Feb 27 18:14:05 raspberrypi2 shairport-sync[16371]: Lost sync with source for 4 consecutive packets -- flushing and resyncing. Error: -6233.
Feb 27 18:14:05 raspberrypi2 shairport-sync[16371]: Flush requested up to 1200086487. It seems as if 0 is special.
Feb 27 18:14:05 raspberrypi2 shairport-sync[16371]: audio_alsa flush called.
Feb 27 18:14:05 raspberrypi2 shairport-sync[16371]: syncing to seqno 9320.
Feb 27 18:14:10 raspberrypi2 shairport-sync[16371]: Packet reception intervals: mean, standard deviation and max for the last 1000 packets in us:     7971.3,     4931.9,    48743.0.
```

**Comment by joerg-krause** [comment] 2016-02-28 08:45
This I got when the device shairport-sync running on is acting as the access point where an iPhone is connected to:

```
00:04:51 Ignore received picture item (include_cover_art = no).
00:04:53 Error -32 in delay(): Broken pipe. Delay reported is 0 frames.
00:04:54 Aliasing of buffer index. Expected 50852, got 51364. Reset.
00:04:55 Player: packets out of sequence: expected: 50852, got: 51364, sync error: 0 frames.
00:04:55 Lost sync with source for 4 consecutive packets -- flushing and resyncing. Error: -13221.
00:04:55 Error -32 writing 352 samples in play() Broken pipe.
00:04:57 Packet reception intervals: mean, standard deviation and max for the last 1000 packets in us:     8016.1,    15913.2,   280906.0.
00:05:05 Packet reception intervals: mean, standard deviation and max for the last 1000 packets in us:     7983.1,     8017.6,    37457.0.
00:05:13 Packet reception intervals: mean, standard deviation and max for the last 1000 packets in us:     7995.9,     7991.5,    38537.0.
00:05:21 Packet reception intervals: mean, standard deviation and max for the last 1000 packets in us:     7970.4,     7912.1,    36985.0.
00:05:29 Packet reception intervals: mean, standard deviation and max for the last 1000 packets in us:     7974.2,     8123.2,    36476.0.
00:05:37 Packet reception intervals: mean, standard deviation and max for the last 1000 packets in us:     7966.8,     8185.1,    70145.0.
00:05:45 Packet reception intervals: mean, standard deviation and max for the last 1000 packets in us:     7987.2,     8191.1,    32641.0.
00:05:53 Packet reception intervals: mean, standard deviation and max for the last 1000 packets in us:     7997.4,     7999.3,    32824.0.
00:06:01 Packet reception intervals: mean, standard deviation and max for the last 1000 packets in us:     7975.5,     8192.3,    33398.0.
00:06:08 Packet reception intervals: mean, standard deviation and max for the last 1000 packets in us:     7972.9,     8086.9,    38194.0.
00:06:16 Packet reception intervals: mean, standard deviation and max for the last 1000 packets in us:     7990.6,     8063.6,    33410.0.
00:06:24 Packet reception intervals: mean, standard deviation and max for the last 1000 packets in us:     7993.1,     8105.7,    32947.0.
00:06:32 Packet reception intervals: mean, standard deviation and max for the last 1000 packets in us:     7972.5,     8001.3,    35228.0.
00:06:40 Packet reception intervals: mean, standard deviation and max for the last 1000 packets in us:     7972.3,     8091.7,    37481.0.
00:06:48 Packet reception intervals: mean, standard deviation and max for the last 1000 packets in us:     7977.7,     8075.9,    32979.0.
00:06:56 Packet reception intervals: mean, standard deviation and max for the last 1000 packets in us:     7997.4,     8192.9,    33229.0.
00:07:04 Packet reception intervals: mean, standard deviation and max for the last 1000 packets in us:     7954.2,     8068.8,    37802.0.
00:07:12 Packet reception intervals: mean, standard deviation and max for the last 1000 packets in us:     7978.0,     8274.7,    34738.0.
00:07:20 Packet reception intervals: mean, standard deviation and max for the last 1000 packets in us:     7975.6,     8402.6,    36060.0.
00:07:28 Packet reception intervals: mean, standard deviation and max for the last 1000 packets in us:     7984.4,     8461.4,    36639.0.
00:07:36 Packet reception intervals: mean, standard deviation and max for the last 1000 packets in us:     8023.3,     8452.9,    80236.0.
00:07:38 Aliasing of buffer index. Expected 5963, got 6475. Reset.
00:07:38 Error -32 in delay(): Broken pipe. Delay reported is 0 frames.
00:07:40 Player: packets out of sequence: expected: 5963, got: 6475, sync error: 0 frames.
00:07:40 Lost sync with source for 4 consecutive packets -- flushing and resyncing. Error: -12977.
00:07:40 Error -32 writing 352 samples in play() Broken pipe.
00:07:44 Packet reception intervals: mean, standard deviation and max for the last 1000 packets in us:     7997.1,    11731.1,   264449.0.
00:07:52 Packet reception intervals: mean, standard deviation and max for the last 1000 packets in us:     7983.6,     8084.2,    37285.0.
00:08:00 Packet reception intervals: mean, standard deviation and max for the last 1000 packets in us:     7966.9,     8103.9,    33821.0.
00:08:08 Packet reception intervals: mean, standard deviation and max for the last 1000 packets in us:     7968.4,     8053.6,    38255.0.
00:08:16 Packet reception intervals: mean, standard deviation and max for the last 1000 packets in us:     7979.7,     8187.2,    36655.0.
00:08:24 Packet reception intervals: mean, standard deviation and max for the last 1000 packets in us:     7988.0,     7893.4,    40060.0.
00:08:32 Packet reception intervals: mean, standard deviation and max for the last 1000 packets in us:     7975.3,     8097.9,    35585.0.
00:08:40 Packet reception intervals: mean, standard deviation and max for the last 1000 packets in us:     7977.2,     7920.2,    34071.0.
00:08:48 Packet reception intervals: mean, standard deviation and max for the last 1000 packets in us:     7966.5,     8268.2,    35856.0.
00:08:56 Packet reception intervals: mean, standard deviation and max for the last 1000 packets in us:     8008.0,     8218.6,    36308.0.
00:09:04 Packet reception intervals: mean, standard deviation and max for the last 1000 packets in us:     7971.5,     8547.0,    34620.0.
00:09:12 Packet reception intervals: mean, standard deviation and max for the last 1000 packets in us:     7972.7,     8435.4,    37858.0.
00:09:20 Packet reception intervals: mean, standard deviation and max for the last 1000 packets in us:     7984.7,     8152.9,    35148.0.
00:09:28 Packet reception intervals: mean, standard deviation and max for the last 1000 packets in us:     8001.2,     8025.6,    33927.0.
00:09:36 Packet reception intervals: mean, standard deviation and max for the last 1000 packets in us:     7975.6,     8241.3,    34572.0.
00:09:44 Packet reception intervals: mean, standard deviation and max for the last 1000 packets in us:     7968.4,     8114.2,    69326.0.
00:09:52 Packet reception intervals: mean, standard deviation and max for the last 1000 packets in us:     7975.3,     8046.3,    32896.0.
00:10:00 Packet reception intervals: mean, standard deviation and max for the last 1000 packets in us:     7985.3,     7984.5,    33036.0.
00:10:08 Packet reception intervals: mean, standard deviation and max for the last 1000 packets in us:     7992.2,     8127.6,    36888.0.
00:10:16 Packet reception intervals: mean, standard deviation and max for the last 1000 packets in us:     7971.2,     8131.8,    34600.0.
00:10:24 Packet reception intervals: mean, standard deviation and max for the last 1000 packets in us:     7979.4,     8124.3,    36855.0.
00:10:32 Packet reception intervals: mean, standard deviation and max for the last 1000 packets in us:     7985.9,     8090.0,    32226.0.
00:10:40 Packet reception intervals: mean, standard deviation and max for the last 1000 packets in us:     7990.5,     8083.9,    38939.0.
00:10:48 Packet reception intervals: mean, standard deviation and max for the last 1000 packets in us:     7969.3,     7890.2,    36656.0.
00:10:51 Error -32 in delay(): Broken pipe. Delay reported is 0 frames.
00:10:52 Aliasing of buffer index. Expected 30264, got 30776. Reset.
00:10:54 Player: packets out of sequence: expected: 30264, got: 30776, sync error: 0 frames.
00:10:54 Error -32 in delay(): Broken pipe. Delay reported is 0 frames.
00:10:54 Lost sync with source for 4 consecutive packets -- flushing and resyncing. Error: -13101.
00:10:56 Packet reception intervals: mean, standard deviation and max for the last 1000 packets in us:     8009.8,    11484.5,   224991.0.
00:11:04 Packet reception intervals: mean, standard deviation and max for the last 1000 packets in us:     7980.9,     8838.3,    38550.0.
00:11:12 Packet reception intervals: mean, standard deviation and max for the last 1000 packets in us:     7972.1,     8968.7,    37323.0.
00:11:20 Packet reception intervals: mean, standard deviation and max for the last 1000 packets in us:     8001.0,     8950.3,    36900.0.
00:11:28 Packet reception intervals: mean, standard deviation and max for the last 1000 packets in us:     7977.4,     8788.1,    36366.0.
00:11:36 Packet reception intervals: mean, standard deviation and max for the last 1000 packets in us:     7977.7,     8469.1,    36799.0.
00:11:41 Aliasing of buffer index. Expected 36339, got 36851. Reset.
00:11:42 Error -32 in delay(): Broken pipe. Delay reported is 0 frames.
00:11:42 Player: packets out of sequence: expected: 36339, got: 36851, sync error: 0 frames.
00:11:42 Lost sync with source for 4 consecutive packets -- flushing and resyncing. Error: -13205.
00:11:43 Error -32 writing 352 samples in play() Broken pipe.
00:11:44 Packet reception intervals: mean, standard deviation and max for the last 1000 packets in us:     8023.8,    10457.0,   181707.0.
00:11:52 Packet reception intervals: mean, standard deviation and max for the last 1000 packets in us:     7987.2,     8272.4,    34491.0.
00:12:00 Packet reception intervals: mean, standard deviation and max for the last 1000 packets in us:     7993.6,     8268.2,    36188.0.
00:12:08 Packet reception intervals: mean, standard deviation and max for the last 1000 packets in us:     7973.6,     8348.9,    36196.0.
00:12:09 Error -32 in delay(): Broken pipe. Delay reported is 0 frames.
00:12:10 Aliasing of buffer index. Expected 39991, got 40503. Reset.
00:12:12 Player: packets out of sequence: expected: 39991, got: 40503, sync error: 0 frames.
00:12:12 Lost sync with source for 4 consecutive packets -- flushing and resyncing. Error: -13185.
00:12:16 Packet reception intervals: mean, standard deviation and max for the last 1000 packets in us:     8001.1,    12794.3,   303320.0.
00:12:24 Packet reception intervals: mean, standard deviation and max for the last 1000 packets in us:     7973.8,     8228.8,    33566.0.
00:12:32 Packet reception intervals: mean, standard deviation and max for the last 1000 packets in us:     7985.6,     8159.1,    34448.0.
00:12:40 Packet reception intervals: mean, standard deviation and max for the last 1000 packets in us:     8003.3,     7966.9,    34867.0.
```

**Comment by joerg-krause** [comment] 2016-02-28 08:57
This I got when both devices are connected to the same network:

```
08:48:14 Ignore received picture item (include_cover_art = no).
08:48:21 Packet reception intervals: mean, standard deviation and max for the last 1000 packets in us:     7991.1,    20018.8,   495662.0.
08:48:29 Packet reception intervals: mean, standard deviation and max for the last 1000 packets in us:     7999.1,     8384.7,    37246.0.
08:48:37 Packet reception intervals: mean, standard deviation and max for the last 1000 packets in us:     7973.8,     8187.4,    37033.0.
08:48:45 Packet reception intervals: mean, standard deviation and max for the last 1000 packets in us:     7958.8,    10618.8,   207417.0.
08:48:53 Packet reception intervals: mean, standard deviation and max for the last 1000 packets in us:     7985.2,     8008.3,    38117.0.
08:49:01 Packet reception intervals: mean, standard deviation and max for the last 1000 packets in us:     7996.6,     8067.3,    35955.0.
08:49:09 Packet reception intervals: mean, standard deviation and max for the last 1000 packets in us:     7969.3,     8429.2,    62457.0.
08:49:17 Packet reception intervals: mean, standard deviation and max for the last 1000 packets in us:     7979.4,     8118.6,    39438.0.
08:49:25 Packet reception intervals: mean, standard deviation and max for the last 1000 packets in us:     7976.0,     8258.9,    39807.0.
08:49:33 Packet reception intervals: mean, standard deviation and max for the last 1000 packets in us:     7990.5,     8211.9,    35767.0.
08:49:41 Packet reception intervals: mean, standard deviation and max for the last 1000 packets in us:     7996.6,     8252.4,    38130.0.
08:49:49 Packet reception intervals: mean, standard deviation and max for the last 1000 packets in us:     7979.1,     8062.2,    34841.0.
08:49:57 Packet reception intervals: mean, standard deviation and max for the last 1000 packets in us:     7976.7,     9050.7,    44114.0.
08:50:05 Packet reception intervals: mean, standard deviation and max for the last 1000 packets in us:     8001.6,     8962.0,    33853.0.
08:50:13 Packet reception intervals: mean, standard deviation and max for the last 1000 packets in us:     7976.7,     9118.0,    36344.0.
08:50:21 Packet reception intervals: mean, standard deviation and max for the last 1000 packets in us:     7973.6,     8799.0,    35245.0.
08:50:29 Packet reception intervals: mean, standard deviation and max for the last 1000 packets in us:     7989.1,     8803.2,    36438.0.
08:50:37 Packet reception intervals: mean, standard deviation and max for the last 1000 packets in us:     7997.1,     8161.5,    36632.0.
08:50:45 Packet reception intervals: mean, standard deviation and max for the last 1000 packets in us:     8003.6,     8229.4,    60242.0.
08:50:53 Packet reception intervals: mean, standard deviation and max for the last 1000 packets in us:     7942.8,     8109.1,    34425.0.
08:51:01 Packet reception intervals: mean, standard deviation and max for the last 1000 packets in us:     7976.3,     8106.6,    33749.0.
08:51:09 Packet reception intervals: mean, standard deviation and max for the last 1000 packets in us:     7997.7,     8167.1,    36936.0.
08:51:16 Packet reception intervals: mean, standard deviation and max for the last 1000 packets in us:     7983.6,     8565.4,    46106.0.
08:51:24 Packet reception intervals: mean, standard deviation and max for the last 1000 packets in us:     7975.0,     8206.2,    36911.0.
08:51:32 Packet reception intervals: mean, standard deviation and max for the last 1000 packets in us:     7970.4,     8276.3,    36896.0.
08:51:40 Packet reception intervals: mean, standard deviation and max for the last 1000 packets in us:     7989.5,     8064.9,    33984.0.
08:51:48 Packet reception intervals: mean, standard deviation and max for the last 1000 packets in us:     7996.5,     8334.1,    33026.0.
08:51:56 Packet reception intervals: mean, standard deviation and max for the last 1000 packets in us:     7969.2,     8427.2,    35961.0.
08:52:04 Packet reception intervals: mean, standard deviation and max for the last 1000 packets in us:     7984.0,     8524.9,    34842.0.
08:52:12 Packet reception intervals: mean, standard deviation and max for the last 1000 packets in us:     7971.5,     8561.6,    38536.0.
08:52:20 Packet reception intervals: mean, standard deviation and max for the last 1000 packets in us:     7983.4,     8325.5,    45804.0.
08:52:28 Packet reception intervals: mean, standard deviation and max for the last 1000 packets in us:     7972.9,     8374.7,    40679.0.
08:52:36 Packet reception intervals: mean, standard deviation and max for the last 1000 packets in us:     7976.3,     8497.1,    35942.0.
08:52:44 Packet reception intervals: mean, standard deviation and max for the last 1000 packets in us:     7983.9,     8838.7,    49037.0.
08:52:52 Packet reception intervals: mean, standard deviation and max for the last 1000 packets in us:     7976.0,     9027.9,    36688.0.

[..]

08:55:11 Packet reception intervals: mean, standard deviation and max for the last 1000 packets in us:     7972.1,     8006.6,    35732.0.
08:55:19 Packet reception intervals: mean, standard deviation and max for the last 1000 packets in us:     8001.6,     8046.2,    56899.0.
08:55:22 Error -32 in delay(): Broken pipe. Delay reported is 0 frames.
08:55:22 Aliasing of buffer index. Expected 64994, got 65506. Reset.
08:55:24 Player: packets out of sequence: expected: 64994, got: 65506, sync error: 0 frames.
08:55:24 Lost sync with source for 4 consecutive packets -- flushing and resyncing. Error: -13188.
08:55:24 Error -32 writing 352 samples in play() Broken pipe.
08:55:27 Packet reception intervals: mean, standard deviation and max for the last 1000 packets in us:     8000.2,    10302.4,   192929.0.
08:55:35 Packet reception intervals: mean, standard deviation and max for the last 1000 packets in us:     7970.5,     7783.0,    34841.0.
08:55:43 Packet reception intervals: mean, standard deviation and max for the last 1000 packets in us:     7972.4,     8315.5,    36080.0.
08:55:51 Packet reception intervals: mean, standard deviation and max for the last 1000 packets in us:     7986.2,     8260.5,    34444.0.
08:55:59 Packet reception intervals: mean, standard deviation and max for the last 1000 packets in us:     7993.8,     9308.1,    36472.0.
```

**Comment by mikebrady** [comment] 2016-02-28 11:03
Thanks for this. I can't help thinking that I'm looking at this wrong. Let me keep thinking about it...

**Comment by mikebrady** [comment] 2016-02-28 21:39
So, I think I have uncovered a failure mode that was being masked, to some extent, by the resync. It's effect was to stop output, which in turn causes the buffer to fill up and overflow, causing aliasing, triggering a resync. I don't know what it is yet, but I think it's [a kind of] progress to find it.

**Comment by joerg-krause** [comment] 2016-02-28 22:15
It's really hard to figure out what's happening, because the error happens indeterminate. I'll be glad to help, so if there is anything I can do, just tell.

**Comment by mikebrady** [comment] 2016-02-29 15:37
I found a bug and fixed it – the fix is in the `development` branch – it might just be the cause of the problem you identified. Any feedback would be welcome.

**Comment by mikebrady** [comment] 2016-03-01 10:59
Actually, this might be of interest to @PeterPablo and #205, as it might reduce the residual stutter being experienced...

**Comment by joerg-krause** [comment] 2016-03-01 10:59
This fix is awesome! Now, shairport-sync plays smoothly - no resyncs, no stuttering so far!

**Comment by mikebrady** [comment] 2016-03-01 11:05
Thanks for the feedback. I've been running it at home, overnight, occasional missed frames, but with no drop-offs on three separate devices and on a pretty dodgy WiFi network. Maybe I should push it to the `master` branch pretty quickly...

**Comment by joerg-krause** [comment] 2016-03-01 11:52
Would be great! Many thanks for solving this annoying issue!

**Comment by mikebrady** [comment] 2016-03-01 12:36
Thanks to you for identifying the issue so concisely. Assuming there are no negative reports, I'll merge the current `development` branch into the `master` over the weekend.

**Comment by PeterPablo** [comment] 2016-03-01 13:19
just briefly from mobile - great fix that helped me as well. tested
yesterday evening for two hours. will report in detail at a later point.

**Comment by mikebrady** [comment] 2016-03-04 22:31
Just for the information of anyone else reading this – these fixes are now in the `master` version at 2.8.1.

**Comment by mikebrady** [comment] 2016-03-05 16:01
Is it safe to close this issue now?

**Closed** 2016-03-05 16:20 UTC

**Comment by guanaco** [comment] 2017-09-19 10:24
Hello,

I'm still hitting similar (if not the same) issue.
I could probably get more verbose log later.
Should I open another issue?

Sep 18 21:38:37 rpi0w-speaker systemd[1]: Started Shairport Sync - AirPlay Audio Receiver.
Sep 18 21:38:38 rpi0w-speaker shairport-sync[433]: alsa output device name is "default".
Sep 18 21:38:38 rpi0w-speaker shairport-sync[433]: Version: "3.1.2rc0-OpenSSL-Avahi-ALSA-soxr-metadata-sysconfdir:/usr/local/etc"
Sep 18 21:38:38 rpi0w-speaker shairport-sync[433]: statistics_requester status is 0.
Sep 18 21:38:38 rpi0w-speaker shairport-sync[433]: daemon status is 0.
Sep 18 21:38:38 rpi0w-speaker shairport-sync[433]: deamon pid file is "/var/run/shairport-sync/shairport-sync.pid".
Sep 18 21:38:38 rpi0w-speaker shairport-sync[433]: rtsp listening port is 5000.
Sep 18 21:38:38 rpi0w-speaker shairport-sync[433]: udp base port is 6001.
Sep 18 21:38:38 rpi0w-speaker shairport-sync[433]: udp port range is 100.
Sep 18 21:38:38 rpi0w-speaker shairport-sync[433]: player name is "Rpi0w-speaker".
Sep 18 21:38:38 rpi0w-speaker shairport-sync[433]: backend is "(null)".
Sep 18 21:38:38 rpi0w-speaker shairport-sync[433]: on-start action is "(null)".
Sep 18 21:38:38 rpi0w-speaker shairport-sync[433]: on-stop action is "(null)".
Sep 18 21:38:38 rpi0w-speaker shairport-sync[433]: wait-cmd status is 0.
Sep 18 21:38:38 rpi0w-speaker shairport-sync[433]: on-start returns output is 0.
Sep 18 21:38:38 rpi0w-speaker shairport-sync[433]: mdns backend "(null)".
Sep 18 21:38:38 rpi0w-speaker shairport-sync[433]: stuffing option is "0" (0-basic, 1-soxr).
Sep 18 21:38:38 rpi0w-speaker shairport-sync[433]: resync time is 0.050000 seconds.
Sep 18 21:38:38 rpi0w-speaker shairport-sync[433]: allow a session to be interrupted: 0.
Sep 18 21:38:38 rpi0w-speaker shairport-sync[433]: busy timeout time is 120.
Sep 18 21:38:38 rpi0w-speaker shairport-sync[433]: drift tolerance is 0.001995 seconds.
Sep 18 21:38:38 rpi0w-speaker shairport-sync[433]: password is "(null)".
Sep 18 21:38:38 rpi0w-speaker shairport-sync[433]: ignore_volume_control is 0.
Sep 18 21:38:38 rpi0w-speaker shairport-sync[433]: volume_max_db is not set
Sep 18 21:38:38 rpi0w-speaker shairport-sync[433]: playback_mode is 0 (0-stereo, 1-mono, 1-reverse_stereo, 2-both_left, 3-both_right).
Sep 18 21:38:38 rpi0w-speaker shairport-sync[433]: disable_synchronization is 0.
Sep 18 21:38:38 rpi0w-speaker shairport-sync[433]: use_mmap_if_available is 1.
Sep 18 21:38:38 rpi0w-speaker shairport-sync[433]: output_rate is 44100.
Sep 18 21:38:38 rpi0w-speaker shairport-sync[433]: output_format is 3 (0-unknown, 1-S8, 2-U8, 3-S16, 4-S24, 5-S24_3LE, 6-S24_3BE, 7-S32).
Sep 18 21:38:38 rpi0w-speaker shairport-sync[433]: audio backend desired buffer length is 0.150000 seconds.
Sep 18 21:38:38 rpi0w-speaker shairport-sync[433]: audio backend latency offset is 0.000000 seconds.
Sep 18 21:38:38 rpi0w-speaker shairport-sync[433]: audio backend silence lead-in time is -1.000000 seconds. A value -1.0 means use the default.
Sep 18 21:38:38 rpi0w-speaker shairport-sync[433]: volume range in dB (zero means use the range specified by the mixer): 0.
Sep 18 21:38:38 rpi0w-speaker shairport-sync[433]: zeroconf regtype is "_raop._tcp".
Sep 18 21:38:38 rpi0w-speaker shairport-sync[433]: decoders_supported field is 1.
Sep 18 21:38:38 rpi0w-speaker shairport-sync[433]: use_apple_decoder is 0.
Sep 18 21:38:38 rpi0w-speaker shairport-sync[433]: alsa_use_playback_switch_for_mute is 0.
Sep 18 21:38:38 rpi0w-speaker shairport-sync[433]: no special mdns service interface was requested.
Sep 18 21:38:38 rpi0w-speaker shairport-sync[433]: configuration file name "/usr/local/etc/shairport-sync.conf" resolves to "/usr/local/etc/shairport-sync.conf".
Sep 18 21:38:38 rpi0w-speaker shairport-sync[433]: metadata enabled is 0.
Sep 18 21:38:38 rpi0w-speaker shairport-sync[433]: metadata pipename is "(null)".
Sep 18 21:38:38 rpi0w-speaker shairport-sync[433]: metadata socket address is "(null)" port 0.
Sep 18 21:38:38 rpi0w-speaker shairport-sync[433]: metadata socket packet size is "500".
Sep 18 21:38:38 rpi0w-speaker shairport-sync[433]: get-coverart is 0.
Sep 18 21:38:38 rpi0w-speaker shairport-sync[433]: loudness is 0.
Sep 18 21:38:38 rpi0w-speaker shairport-sync[433]: loudness reference level is -20.000000
Sep 18 21:38:38 rpi0w-speaker shairport-sync[433]: Successful Startup
Sep 18 21:38:39 rpi0w-speaker shairport-sync[433]: avahi: avahi_register.
Sep 18 21:38:39 rpi0w-speaker shairport-sync[433]: avahi: register_service.
Sep 18 21:38:39 rpi0w-speaker shairport-sync[433]: avahi: request to add "_raop._tcp" service without metadata
Sep 18 21:38:39 rpi0w-speaker shairport-sync[433]: avahi: service '4CEDE8F0D741@Rpi0w-speaker' successfully added.
Sep 19 07:02:59 rpi0w-speaker shairport-sync[433]: New RTSP connection from 192.168.1.33:59477 to self at 192.168.1.36:5000 on conversation thread 0.
Sep 19 07:02:59 rpi0w-speaker shairport-sync[433]: RTSP conversation thread 0 terminated.
Sep 19 07:02:59 rpi0w-speaker shairport-sync[433]: New RTSP connection from 192.168.1.33:59476 to self at 192.168.1.36:5000 on conversation thread 1.
Sep 19 07:03:00 rpi0w-speaker shairport-sync[433]: Play connection from user agent "AirPlay/320.20" on RTSP conversation thread 1.
Sep 19 07:03:00 rpi0w-speaker shairport-sync[433]: Active-Remote string seen: "2618309947".
Sep 19 07:03:00 rpi0w-speaker shairport-sync[433]: DACP-ID string seen: "32C79D851C896B00".
Sep 19 07:03:00 rpi0w-speaker shairport-sync[433]: Set up play connection from 192.168.1.33 to self at 192.168.1.36 on RTSP conversation thread 1.
Sep 19 07:03:00 rpi0w-speaker shairport-sync[433]: Output frame bytes is 4.
Sep 19 07:03:00 rpi0w-speaker shairport-sync[433]: Output bit depth is 16.
Sep 19 07:03:00 rpi0w-speaker shairport-sync[433]: Hammerton Decoder used on encrypted audio.
Sep 19 07:03:00 rpi0w-speaker shairport-sync[433]: Output written using MMAP
Sep 19 07:18:40 rpi0w-speaker shairport-sync[433]: Error -32 in delay(): "Broken pipe". Delay reported is 0 frames.
Sep 19 07:18:40 rpi0w-speaker shairport-sync[433]: Error -32 in delay(): "Broken pipe". Delay reported is 0 frames.
Sep 19 07:18:40 rpi0w-speaker shairport-sync[433]: Error -32 in delay(): "Broken pipe". Delay reported is 0 frames.
Sep 19 07:18:40 rpi0w-speaker shairport-sync[433]: Error -32 in delay(): "Broken pipe". Delay reported is 0 frames.
Sep 19 07:18:40 rpi0w-speaker shairport-sync[433]: Error -32 in delay(): "Broken pipe". Delay reported is 0 frames.
Sep 19 07:18:40 rpi0w-speaker shairport-sync[433]: Error -32 writing 352 samples in play(): "Broken pipe".
Sep 19 07:18:40 rpi0w-speaker shairport-sync[433]: Error -32 in delay(): "Broken pipe". Delay reported is 0 frames.
Sep 19 07:18:41 rpi0w-speaker shairport-sync[433]: Error -32 in delay(): "Broken pipe". Delay reported is 0 frames.
Sep 19 07:18:41 rpi0w-speaker shairport-sync[433]: Error -32 in delay(): "Broken pipe". Delay reported is 0 frames.
Sep 19 07:18:41 rpi0w-speaker shairport-sync[433]: Error -32 in delay(): "Broken pipe". Delay reported is 0 frames.
Sep 19 07:18:41 rpi0w-speaker shairport-sync[433]: Error -32 in delay(): "Broken pipe". Delay reported is 0 frames.
Sep 19 07:18:41 rpi0w-speaker shairport-sync[433]: Error -32 in delay(): "Broken pipe". Delay reported is 0 frames.
Sep 19 07:18:41 rpi0w-speaker shairport-sync[433]: Error -32 in delay(): "Broken pipe". Delay reported is 0 frames.
Sep 19 07:18:41 rpi0w-speaker shairport-sync[433]: Error -32 in delay(): "Broken pipe". Delay reported is 0 frames.

**Comment by mikebrady** [comment] 2017-09-19 10:48
Thanks for the report. It's quite different, I think, to the original issue, so might be worth opening a new issue. Before that, just try changing one of the settings in the configuration file – change the `use_mmap_if_available` setting to `"no"`, so the line should read:

```
  use_mmap_if_available = "no"; // Use this optional advanced setting to control whether MMAP-based output is used to communicate  with the DAC. Default is "yes"
```
Remember to uncomment the line by removing the `//` at the start! If that doesn't work (and it's a long shot) then please open a new issue.

**Comment by guanaco** [comment] 2017-09-19 19:34
I managed to reproduce it with log verbosity set to 3 and not using mmap, will create a new issue soon.
