### ISSUE TITLE
Interrupt play

### ISSUE THREAD

**Issue by ghendo** [mikebrady/shairport-sync#389] opened 2016-10-09 01:33 UTC
If something is playing on my raspberry pi via shairport-sync from say an iPhone and I wish to break into this and mute the speakers or play something else via the terminal am I able to so this?

**Comment by mikebrady** [comment] 2016-10-09 08:46
If you mute or stop the source, Shairport Sync releases the output device immediately.
There is also a awkward and deprecated way by sending Shairport Sync some Unix signals. It hasn't been tested for a long time.

**Comment by ghendo** [comment] 2016-10-09 09:33
need to have an automated way to stop the stream so I would be keen to try some weird way to do it

I can't send any pause signal to the source as it could be from any number of potential places. Ie computers iPhones guests iPhones etc. 

Graeme

**Comment by mikebrady** [comment] 2016-10-09 10:52
The core of the problem is that there is currently no IPC system built into Shairport Sync. I guess the obvious one is dbus, but I'm not familiar enough with it yet. Maybe other people have some ideas.

**Comment by tapeboy7** [comment] 2016-11-30 13:04
How about dipping the volume during a notification, then restore the volume?
I would like a feature like this for a doorbell sound playing from my server.

**Comment by NoelSinggih** [comment] 2017-01-18 05:49
Mike, you said above that "If you mute or stop the source, Shairport Sync releases the output device immediately." - could this be the cause of some random disconnection that I experienced in my system when I switched tracks frequently on Tidal?

Could it be that while switching tracks, Tidal stop sending signal to the Shairport-Sync (on Volumio 2.041) and it disconnects? I noticed that when I am playing my offline Tidal content, I am not getting this issue.

Is there a log somewhere that I can look to confirm the above?

Thanks in advance.
Noel

**Comment by mikebrady** [comment] 2017-03-11 20:30
Hi Noel. Sorry for the very long delay here. I've been getting some reports of instabilities and I this might be related. Anyway, I've been cleaning up code that I suspect, but can't prove, is possibly causing problems. It's now on the `development` branch. I'd be obliged if you tried it out, to see it it's any better.

**Comment by mikebrady** [comment] 2019-10-11 16:40
Hi Noel. I'm pretty sure this has been addressed in more recent versions of Shairport Sync! Please open a new issue if necessary.

**Closed by mikebrady** 2019-10-11 16:40 UTC
Labels: enhancement, question
