### ISSUE TITLE
much hiss with yosemite and itunes and raspberry pi

### ISSUE THREAD

**Issue by webattitude** [mikebrady/shairport-sync#134] opened 2015-09-28 20:46 UTC
Hi, volume is very low with much hiss (?) / noise...
I've installed shairport-sync on rapsberry pi (raspbian), I'm using yosemite 10.10.5

I'm using also with a mixing (dsnoop) in asound.conf, although I dont know anything about asound.conf syntax.

```
pcm.salon {
        type plug
        slave.pcm "dmixer"
}

pcm.dmixer  {
        type dmix
        ipc_key 1024
        slave {
                pcm "hw:1,0"
                period_time 0
                period_size 1024
                buffer_size 4096
                rate 44100
        }
        bindings {
                0 0
                1 1
        }
}

ctl.dmixer {
        type hw
        card 0
}

pcm.mixin {
        type dsnoop
        ipc_key 5978293 # must be unique for all dmix plugins!!!!
        ipc_key_add_uid yes
        slave {
                pcm "hw:0,0"
                channels 2
                period_size 1024
                buffer_size 4096
                rate 44100
                periods 0
                period_time 0
        }
        bindings {
                0 0
                0 1
        }
}
```

**Comment by mikebrady** [comment] 2015-09-28 20:59
Hi Thomas. If you are listening on the built-in headphone jack, that's the problem. It's really very poor. Even a $5 USB DAC is way better. See https://github.com/mikebrady/shairport-sync/issues/92 for more discussion.

**Comment by webattitude** [comment] 2015-09-30 07:11
Hi, I'm using the headphone jack.
I've also installed gmrender-resurrect (dnla renderer), which plays through gstreamer and also, hence the mixer config I've set up in asound.conf, and the sound is loud and clear...

**Comment by mikebrady** [comment] 2015-09-30 11:15
Hi Thomas. It's well known that the audio on the headphone jack is very poor. It has 11 bits of resolution (a dynamic range of 33 dB) and can't reproduce sounds over 15 kHz. The newer models don't seem to improve much on the old one – see http://www.crazy-audio.com/2014/07/sound-quality-of-the-raspberry-pi-b/.

The problem is compounded because the firmware advertises the device's mixer as having a volume-control range of 106.35 dB, which is utter fiction. If you use the mixer to control the volume, then Shairport Sync maps the iTunes volume to this range, and this compounds the problem. The result is that only when the iTunes volume is at its maximum or very close to it does the sound level come up.

One way to sort-of get around some of this is to avoid using the mixer altogether – to do this, don't give a mixer name in Shairport Sync's settings.Then, an internal attenuator will be used by Shairport Sync with a dynamic range of 48 dB, making the volume control a bit more useful. (You'll probably have to use alsamixer, or similar, to set the mixer's output to 100%.)

I suppose one could add an option to ignore the advertised mixer range and define a smaller, more realistic one, but the quality of the device is so poor that it doesn't seem worthwhile.

Whaddya think?

**Comment by webattitude** [comment] 2015-10-02 11:19
makes sense :)
working better now, thank you.

Anyway, weird thing : systemwide sound settings (in menu bar) don't let me use shairport as output... I can select the entry, but sound still going through macbook speakers, although iTunes can output to shairport...

**Comment by mikebrady** [comment] 2015-10-02 11:23
If you option-click the speaker icon in the menu bar, you should get a list of sound outputs, including the Shairport Sync device (?). There's still a two-second delay though...

**Comment by webattitude** [comment] 2015-10-02 12:19
Yes, right, but it's not working. Shairport output stays selected all time long, yet the sound still outputs to speakers.

**Comment by mikebrady** [comment] 2015-10-02 12:28
That's weird. I'm using 10.11 and it works fine...

**Comment by webattitude** [comment] 2015-10-02 20:54
new 10.11 here too, but no more chance with el capitan...
I can't see shairport at all in audio midi setup, whereas it appears in menubar sound dropdown (with option).

**Comment by webattitude** [comment] 2015-10-02 21:31
also, when I switch between internal speakers and shairport, there is a little _gap_ in sound, a little _hop_  (I dont know how to name it, my english limits :) )

**Comment by webattitude** [comment] 2015-10-03 14:57
hum... it worked this morning... but anymore. Weird.
OK, I'll deal with it like that for now. Besides, I've some issues with the wifi router, which seems to block dhcp with my android phone now... so I guess it may block other stuff too.

thanks anyway.
-Thomas

**Comment by mikebrady** [comment] 2015-10-05 10:49
Yeah, may people report problems with routers, particularly with respect to crossing between the wired to the WiFi domain, and especially with regard to Bonjour/Zeroconof/Avahi and multicast in general.

**Comment by mikebrady** [comment] 2015-10-06 11:10
Hi Thomas. There is a bug in Shairport Sync, for sure, that surfaces when you choose Shairport Sync device for systemwide output. Sometimes it starts properly and sometimes it enters a loop of being unable to "catch up" with the audio. Or something. I'm investigating.

**Comment by mikebrady** [comment] 2015-10-06 12:14
I believe I've found it. I'll post an update later today.

**Comment by webattitude** [comment] 2015-10-06 13:03
hey, that's cool

**Comment by PeterPablo** [comment] 2015-10-06 13:29
Just for reference, Mike seems to have addressed the issue by https://github.com/mikebrady/shairport-sync/commit/a89da7fded202a36bdaaa5e2008d4ec5246a6500.

**Comment by mikebrady** [comment] 2015-10-06 14:47
Thanks Peter. I'd be glad of any feedback.

Also, I'm thinking of adding yet another option – this one to set the maximum attenuation range. For example, the built-in DAC of a Raspberry Pi reports a volume adjustment range of 106.35 db, which is crazy. Setting a maximum range of about 35 dB for it would make Shairport Sync use the top 35 dB of the range only, so that the minimum value on the iTunes volume control would 35 dB down from the maximum -- just audible above the hiss -- and the rest of the volume control's extent of "movement" would actually be useful.

**Comment by PeterPablo** [comment] 2015-10-06 15:09
I'm about to reinstall my pi with Jessie. I'll report back my findings.
Rpi2 and Mac book, currently no external sound card. This will change next
week, though (hifiberry DAC+). Of course I'll checkout the develop branch.

**Comment by mikebrady** [comment] 2015-10-06 15:31
I've updated the build and install directions on the `development` branch, but there is still one issue. The `shairport-sync.service` file expects `shairport-sync` to be in `/usr/bin`, but I think it should be in `/usr/local/bin`. Other than that, it works pretty well.

As a matter of interest, what is your thinking on the location of the executable?

**Comment by PeterPablo** [comment] 2015-10-06 15:34
Even though I know my way around linux, I am unfortunately not qualified to answer that the correct location would be. Ok, new Pi is up and running...

**Comment by mikebrady** [comment] 2015-10-06 15:41
Thanks. I'll stick it upon as an issue...

**Comment by PeterPablo** [comment] 2015-10-06 15:47
Here, I'll collect my findings for the installation on Debian Jessie on a Raspberry PI 2:
* `libsoxr-dev` is semi-available in the repository of the foundation. `apt-get` finds the package but for me is unable to download it. I'll continue with a manual compilation and edit here later on.

**Comment by PeterPablo** [comment] 2015-10-06 16:08
@mikebrady ping, I updated my previous commit several times. I got it running pretty quickly, though with very strong hiss.

**Comment by webattitude** [comment] 2015-10-06 16:59
I'll reinstall my pi very soon too (as it seems to completely crash regularly... maybe sd card issue).
Do not hesitate to ask for any information/participation.

BTW, /usr/local/bin is theorically for user installed applications, ie outside package manager.

**Comment by webattitude** [comment] 2015-10-07 16:32
I've just reinstalled shairport-sync on a fresh raspbian. Unfortunately no sound out. I think the last sd card crash did burn the sound chip (is it at least possible ?).
There is also some work in the house now so maybe a wire is cut somewhere :)
Got a new router now, so I'll check as soon as the sd backup is ready.

**Comment by mikebrady** [comment] 2015-10-07 18:25
Hi Thomas it's very unlikely that a crash would burn out a sound chip. You should play with `alsamixer` to see what is out there.

**Comment by webattitude** [comment] 2015-10-07 19:57
Yes... my fault. I choose _auto_ for audio output when I first setup the distro with raspi-config.
I've just forced it to jack, and it's then working, at least with itunes...
with systemwide dropdown I can select shairport-sync device but sound still outputs from macbook speakers.

**Comment by webattitude** [comment] 2015-10-07 20:42
OK, sorry, didn't try with latest `max-volume-range` branch... till now. But it's still not working.
Is there some parameters to set up in conf file ? I've seen some _itunes_ lines..

**Comment by webattitude** [comment] 2015-10-07 20:46
As soon as I select shairport-sync device in itunes, your app logs this : 
```

Oct  7 22:44:31 soundsystem shairport-sync[8495]: culling threads.
Oct  7 22:44:31 soundsystem shairport-sync[8495]: new RTSP connection.
Oct  7 22:44:31 soundsystem shairport-sync[8495]:     CSeq: 1.
Oct  7 22:44:31 soundsystem shairport-sync[8495]:     User-Agent: iTunes/12.3 (Macintosh; OS X 10.11).
Oct  7 22:44:31 soundsystem shairport-sync[8495]:     Client-Instance: 17DBE13F46A9DF43.
Oct  7 22:44:31 soundsystem shairport-sync[8495]:     DACP-ID: 17DBE13F46A9DF43.
Oct  7 22:44:31 soundsystem shairport-sync[8495]:     Active-Remote: 1990208034.
Oct  7 22:44:31 soundsystem shairport-sync[8495]:     Apple-Challenge: zXXwbNNVzVAtml1jxrNtcg.
Oct  7 22:44:31 soundsystem shairport-sync[8495]:     Apple-Response: 3WqldHJhgRVMUJ9TPmNg8HpO8ybSftd/DWT2ZE0aCS6OGrNE6uLX2n/9e8dwvi8sEYLvp+zUAl7iBdH0dD6fBm6IpAHW5viiHWA89DDAYiyNXvAQ6uREyRqL0ZjTMYLzq5JQcpEVftaEvzkTnqcVMd1muteiqcsk/eT56HkdPBIGlnhG1b3hcn7gY/WLBT8FrDW8z+DTbTUHa4+zK557KL+Z+56D7vsXY8QPU3L3LE9T30LbGcvbvmHuhDyy41SdlEuRjE0H5sWbdkJJF83jhCX8/NX2nR5zYz6yNc7T058mPhr3M9F4YAmrxU+RM6XSYw4QUyqUG+tANfe0cAllag.
Oct  7 22:44:31 soundsystem shairport-sync[8495]:     CSeq: 1.
Oct  7 22:44:31 soundsystem shairport-sync[8495]:     Audio-Jack-Status: connected; type=analog.
Oct  7 22:44:31 soundsystem shairport-sync[8495]:     Public: ANNOUNCE, SETUP, RECORD, PAUSE, FLUSH, TEARDOWN, OPTIONS, GET_PARAMETER, SET_PARAMETER.
Oct  7 22:44:31 soundsystem shairport-sync[8495]: RTSP connection closed.
Oct  7 22:44:31 soundsystem shairport-sync[8495]: closing RTSP connection.
Oct  7 22:44:31 soundsystem shairport-sync[8495]: terminating RTSP thread.
```

whereas nothing at all appears when I select device in systemwide dropdown...

**Comment by webattitude** [comment] 2015-10-07 20:49
If I use the systemwide control while playing music with itunes (instead of canari), lot of repeating logs : 
```
Oct  7 22:47:49 soundsystem shairport-sync[8495]: +++++++++
Oct  7 22:47:49 soundsystem shairport-sync[8495]: +++++++++
Oct  7 22:47:49 soundsystem shairport-sync[8495]: ---------
Oct  7 22:47:49 soundsystem shairport-sync[8495]: ---------
Oct  7 22:47:49 soundsystem shairport-sync[8495]: ---------
Oct  7 22:47:49 soundsystem shairport-sync[8495]:     CSeq: 18.
Oct  7 22:47:49 soundsystem shairport-sync[8495]:     DACP-ID: A9AADDEC3BE44D8C.
Oct  7 22:47:49 soundsystem shairport-sync[8495]:     Active-Remote: 1341852058.
Oct  7 22:47:49 soundsystem shairport-sync[8495]:     User-Agent: AirPlay/250.10.
Oct  7 22:47:49 soundsystem shairport-sync[8495]:     CSeq: 18.
Oct  7 22:47:49 soundsystem shairport-sync[8495]:     Audio-Jack-Status: connected; type=analog.
Oct  7 22:47:49 soundsystem shairport-sync[8495]:     Public: ANNOUNCE, SETUP, RECORD, PAUSE, FLUSH, TEARDOWN, OPTIONS, GET_PARAMETER, SET_PARAMETER.
Oct  7 22:47:49 soundsystem shairport-sync[8495]: +++++++++
```

**Comment by PeterPablo** [comment] 2015-10-07 20:49
It just worked for me, though I don't have a log file. hmm, you have OSX El Capitan as well.

**Comment by webattitude** [comment] 2015-10-07 21:19
Which application, @PeterPablo ?

**Comment by PeterPablo** [comment] 2015-10-07 21:20
System sound, as noted above. I didn't even try iTunes.

**Comment by mikebrady** [comment] 2015-10-07 21:50
Hi @webattitude, @PeterPablo. I've just pushed a functional version of `max-volume-range` branch. You can set a `volume_range_db` which will limit the ratio between the highest and lowest volume to the number of decibels you specify. A value of 60 (i.e. 60 dB) would be okay for a decent stereo, I'd say. For the Raspberry Pi's build-in DAC, I'd suggest 35. It won't make a difference between functional and non functional, but I think it will help to get the most from the Raspberry Pi's built-in DAC.

Thomas, setting the verbosity to 3 is not much use in this circumstance – 2 or 1 is fine.

I've used the updated branch on a 2009 iMac, a 2014 MacBook Pro and a 2014 Mac Pro all successfully, with a Raspberry Pi running Raspbian Wheezy and Raspbian Jessie. Also Ubuntu 14.04 in VMWare, and also a FreeBSD installation on a PC Engines apu 4.

**Comment by webattitude** [comment] 2015-10-07 23:08
Do you have customized conf file ?

Here is a sample of the logs for itunes playing, but remote device selected by systemwide control : 
```
Oct  8 01:03:02 soundsystem shairport-sync[11295]: Process metadata with type 73736e63, code 70766f6c and length 25.
Oct  8 01:03:02 soundsystem shairport-sync[11295]:     CSeq: 4.
Oct  8 01:03:02 soundsystem shairport-sync[11295]:     Audio-Jack-Status: connected; type=analog.
Oct  8 01:03:03 soundsystem shairport-sync[11295]: Process metadata with type 73736e63, code 7072736d and length 0.
Oct  8 01:03:03 soundsystem shairport-sync[11295]: Lost sync with source for 4 consecutive packets -- flushing and resyncing. Error: -3992.
Oct  8 01:03:03 soundsystem shairport-sync[11295]: Process metadata with type 73736e63, code 70666c73 and length 0.
Oct  8 01:03:03 soundsystem shairport-sync[11295]: syncing to seqno 51196.
Oct  8 01:03:03 soundsystem shairport-sync[11295]:     CSeq: 5.
Oct  8 01:03:03 soundsystem shairport-sync[11295]:     DACP-ID: FEFBD3A4BD3B7838.
Oct  8 01:03:03 soundsystem shairport-sync[11295]:     Active-Remote: 1434531222.
Oct  8 01:03:03 soundsystem shairport-sync[11295]:     User-Agent: AirPlay/250.10.
Oct  8 01:03:03 soundsystem shairport-sync[11295]:     CSeq: 5.
Oct  8 01:03:03 soundsystem shairport-sync[11295]:     Audio-Jack-Status: connected; type=analog.
Oct  8 01:03:03 soundsystem shairport-sync[11295]:     Public: ANNOUNCE, SETUP, RECORD, PAUSE, FLUSH, TEARDOWN, OPTIONS, GET_PARAMETER, SET_PARAMETER.
```

**Comment by webattitude** [comment] 2015-10-07 23:30
Ok, it is working now : it looks like an alsa device grab issue. I'm not sure, not very easy with alsa and pulseaudio...
Thanks you anyway, for your work and your help.

**Comment by mikebrady** [comment] 2015-10-08 14:36
Thanks Thomas. Shairport Sync needs direct access to the real audio device, but releases it as soon as it pauses or stops.

@PeterPablo, I'll be merging the `max-volume-branch` into the `development` branch in the next day or two. In my brief use of it, setting the range to 35 dB makes quite a difference to the usability of Raspberry Pi built-in DAC.

**Comment by webattitude** [comment] 2015-10-08 18:13
Welcome.
BTW, I managed to use pulseaudio along with shairport Sync and https://github.com/hzeller/gmrender-resurrect, which can both play in the same time... it is not really desirable :), though it is not blocking.

**Comment by PeterPablo** [comment] 2015-10-09 09:08
Yesterday I only had little time and I must have made a mistake somewhere, as I didn't see the new option available in my config.txt. Probably I should have looked at the sample config. Nevertheless I understand it this way: when changing sound on my laptop, the software mixer (observable in alsamixer) should change it's current gain. This does not happen! In my case, it seems that the laptop attenuates the sound and this is sent to my pi, where the gain/attenuation is kept constant. From what I read, I think that what should happen is: laptop always sends unattenuated, the mixer does the attenuation?!

**Comment by mikebrady** [comment] 2015-10-09 09:20
What should happen is just as you say: if you change the sound level on your laptop, the change should be visible in `alsamixer` when you use it to look at the audio device used by Shairport Sync. This only happens if you set the (correct) mixer control name using the `mixer_control_name` setting in the `alsa` stanza of the `shairport-sync.conf` file. (Make sure you uncomment that line!).

If you give an incorrect mixer name, Shairport Sync won't start. If the mixer does not have a decibel scale, it can't be used. Either way, there'll be a message in the log. 

If a mixer is used, then the audio is sent to it at full volume, as you say. If a mixer isn't being used, the audio is attenuated by Shairport Sync and then sent to the output device.

**Comment by PeterPablo** [comment] 2015-10-09 09:38
Currently I run with an empty config file. Contradicting to what you say, the service starts up and I can use Shairport-sync just fine. Should the service log to it's own file in `/var/log`? I ask, since there is none. (I didn't jet start digging.) 
I currently run on a fresh Raspbian Jessie and use the line output.

**Comment by mikebrady** [comment] 2015-10-09 09:53
That sounds plausible: when you start it up with an empty settings file, Shairport Sync uses the default `alsa` output device and does not use a mixer, since you haven't specified one. Have a look at the "Configuring Shairport Sync" section of the README.md.

Jessie uses `journalctl` for logging, see, for example: https://www.digitalocean.com/community/tutorials/how-to-use-journalctl-to-view-and-manipulate-systemd-logs

**Comment by webattitude** [comment] 2015-10-09 10:33
Hi, I interfere again.
About log, I suggest to use a remote logging server, to avoid SD card writes overload, which seems to have lead to crash my pi several times.

**Comment by mikebrady** [comment] 2015-10-09 10:38
Thanks Thomas. Shairport Sync uses a standard library -- `libdaemon` -- for logging. it should be possible to redirect logging in the normal way. I would be very surprised if it leads to crashing, so long as you are all verbosity level 1. Verbosities 2 and 3 are much too chatty for anything but short-term debugging.

**Comment by webattitude** [comment] 2015-10-09 12:48
Ok, for information, and in case there are more applications onboard.
My pi stopped crashing since I redirected all logs to remote server.
I've been used to install ShairportSync, gmmediarenderer and pulseaudio on this one.

**Comment by mikebrady** [comment] 2015-10-13 17:00
Thanks again. I am going to close this now, if that's okay. Feel free to reopen if necessary.

**Closed by mikebrady** 2015-10-13 17:00 UTC
