### ISSUE TITLE
shairport thinks it's still playing OSX alt-click

### ISSUE THREAD

**Issue by elnin0815** [mikebrady/shairport-sync#69] opened 2015-04-06 14:46 UTC
Hi,

after i use shairport-sync as the systemwide audio device in OSX Yosemite (playing music with VLC, press pause in VLC, switch back zu internal speakers) shairport-sync thinks its still playing - i can't connect another Airplay Device.
I have to explicitly press Stop in VLC before switching the audio output back to internal speakers.

Is OSX not sending an terminating signal to the airplay receiver when switching back to the internal speakers? I can't see one in the log, even in -vvv mode.
It looks like the (empty) airplay stream is still received.

**Comment by mikebrady** [comment] 2015-04-06 20:15
No, as far as I know, OS X does not send a signal when it disconnects. Shairport Sync sees the event as a loss of signal, and waits, by default, for 120 seconds before dropping the session. You can change the time delay using the `-t` or `–timeout` option.

**Comment by elnin0815** [comment] 2015-04-08 09:20
I'm already using the -t 0 option. But if i select shaiport-sync as OSx Output device nobody else (iPhone) can connect and a busy signal is sent. If i use airplay with iTunes and try to connect the iPhone it just works iTunes stops playing and the sound comes from the phone. It seems, that OSX SoundOutput Airplay is handled differently compared to iTunes/iOS devices and it never drops the connection. (Only if i hit the stop button in VLC, after that other devices can connect again.

I found a similar Issue here:
https://github.com/mikebrady/shairport-sync/issues/39 Delay between pausing & sound stopping

If i play music with VLC the start of the audio tracks are missing (1-2 secs), when VLC switches to the next track in a playlist there are also ~2secs missing.

How can i support you with this problem? Should i make some shaiport-sync logs with (-v(v(v))) ?
Or would a wireshark dump help more?

**Comment by mikebrady** [comment] 2015-04-08 10:13
Let me check to see if I can reproduce this behaviour.

**Comment by mikebrady** [comment] 2015-04-08 18:14
Using an iMac running 10.0.2, iTunes 12.1.0.50, VLC 2.1.5 and the latest Shairport Sync (stable) with `-t0`, I don't think I'm getting the same behaviours:
* Selecting the Shairport Sync player from iTunes:
 * It plays fine.
 * It can be interrupted by a play request from an iPhone, and the iMac reverts to internal speakers.
* Selecting Shairport Sync as the output by option-clicking the sound control in the menu bar:
 * iTunes plays fine with a two-second delay.
 * a pause in iTunes stops sending audio to Shairport Sync and after a couple of seconds the Mac drops the play session.
 * VLC plays fine with a two-second delay
 * a "pause" in VLC seems to send silence to Shairport Sync; it does not drop the session.
 * a "stop" in VLC ends the session.
 * When VLC goes to the next track, it does go through a flush sequence between, whereas iTunes does not.
 * An attempt to interrupt it by a play request from an iPhone succeeds and the iMac reverts to internal speakers.
 * There is a two second delay in VLC; nothing seems to be lost, however.

So, all in all, it seems that Shairport Sync is behaving itself.  You can see these behaviours by monitoring the log when Shairport Sync is running at the `-vv` level of verbosity. It's puzzling, frankly.

**Comment by elnin0815** [comment] 2015-04-08 20:07
I'm using shairplay-sync 2.1.15-openssl-Avahi-ALSA with is included in pimusicbox 0.6RC.
I'll do your test procedure the next days and will provide -vv logs.

thanks for your work and support!

**Comment by mikebrady** [comment] 2015-05-05 12:02
Hi there. I've done some updates to this and replaced the `-t` option with two independent settings, one for disabling the busy signal and one for setting the timeout. They are in the (new) configuration file in the development version. Might be worth trying...

**Comment by mikebrady** [comment] 2015-09-01 12:04
That configuration file support is not in the stable master version.
I'm going to close this – feel free to reopen if there are developments.

**Closed by mikebrady** 2015-09-01 12:04 UTC
