### ISSUE TITLE
Support AirPlay 2 with multiroom

### ISSUE THREAD

**Issue by verseeq** [mikebrady/shairport-sync#709] opened 2018-06-01 12:22 UTC

**Comment by joerg-krause** [comment] 2018-06-01 14:26
Duplicate of #535

**Comment by Technodad** [comment] 2019-01-19 20:34
+1 on AirPlay 2, particularly with [AirPlay 2 embedding in TVs being one of the sleeper announcement at CES 2019](https://www.engadget.com/2019/01/11/apple-airplay-2-ces-2019/).

**Comment by seniorgod** [comment] 2019-01-26 10:07
+1

**Comment by Midifreakz** [comment] 2019-03-31 00:24
+1

**Comment by Episcop** [comment] 2019-06-15 14:41
+1

**Comment by ssbarnea** [comment] 2021-09-07 06:54
@github-action bot shut up, you are drunk.

**Comment by charlesomer** [comment] 2021-09-07 07:56
Since this is a duplicate of #535 as mentioned earlier, I think this issue can be closed?

**Closed as completed** 2021-10-22 19:30 UTC
Labels: question
