### ISSUE TITLE
How to start Shairport-Sync?

### ISSUE THREAD

**Issue by CalRae25** [mikebrady/shairport-sync#185] opened 2015-12-21 15:43 UTC
Hi Mike,
I've followed your very helpful instructions up to and including editing shairport-sync.conf, however I now don't know where to go from there! I'm using a Raspberry Pi 2 and am very new to Linux as a whole, so any help about how to actually start the program running and getting it to run on startup would be very much appreciated! Many thanks

**Comment by mikebrady** [comment] 2015-12-21 17:11
Thanks for your interest in Shairport Sync. Once it's installed and running, Shairport Sync shows up on the network as an AirPlay audio device, much like an AirPort Express.

See https://support.apple.com/en-us/HT204289 for information about that.

The Shairport Sync device should show up as a device you can choose as a destination for audio from, e.g. iTunes or an iOS device.

Once you have followed though all the instructions, and assuming you're on Raspbian Jessie (the latest Raspbian), you can start Shairport Sync with `$sudo systemctl start shairport-sync`. To enable it to start automatically on power-up, enter `$sudo systemctl enable shairport-sync`.

**Comment by efrecska** [comment] 2016-01-31 14:11
Hi Mike!

I am a novice too. I successfully installed shairport-sync to Raspbian Wheezy with a Musical Fidelity VLink USB card only until the first reboot. Right after the installation I entered a starting command:
'shairport-sync -a AirPi -- -d plughw:CARD=VLink' and it worked.
After the first reboot no sound from the VLink anymore and 'speaker-test -D plughw:0' gives the error message: "Unable to set hw parameters for playback: Broken pipe".
Previously the speaker test worked fine that way.
After a lot of failed trials with editing alsa.conf, asound.conf and .asoundrc files I reinstalled the full system from scratch and the same happened: VLink output worked until the first reboot after installing shairport-sync.

What is the right starting command and what brokes the pipe?
I would greatly appreciate your help!

Ed

**Comment by mikebrady** [comment] 2016-01-31 14:43
Hi Ed. Thanks for the post. It looks like you are outputting to an `alsa` device that isn't a real hardware card – it's an `alsa` virtual device, and it doesn't provide enough information for Shairport Sync to work properly. In particular it doesn't usually give true latency information.

If you use `alsamixer` or `amixer`, you should look for devices that have a name that begins with `hw:` – something like `hw:0` or `hw:1`. You should be able to identify the Musical Fidelity VLink USB card, and then you can set it to be your output device. If you're getting absolutely nowhere, check that you can output to the card using something like `aplay` (maybe you've already tried this), and then, try using the Pi's own built-in audio to ensure everything is working (it's not HiFi, but it's a good diagnostic).

Let me know how it's going.

**Comment by efrecska** [comment] 2016-02-01 17:37
Hi Mike! I reinstalled everything without changing any alsa settings (no commenting outs or else). The starting command 'shaiport-sync -a AirPi -- -d plughw:0,0' worked repeatedly and received audio from iTunes. Untill... Untill I switched to AirFoil. Then the 'Broken pipe' errors started to show up not only with shairport-sync but every other players (aplay, mplayer, etc.). Reboot did not help, it seems that a permanent change has occurred in the system. 
The issue is not starting shairport-sync anymore but the 'Broken pipe'. 
Should I move to another topic from here? 
What has ruined my environment and how to avoid it?

Thankfully,  Ed

**Comment by mikebrady** [comment] 2016-02-01 18:06
Hi Ed. That is a true mystery alright. What do you get if you enter `aplay -l`? Note the option is small L.

**Comment by efrecska** [comment] 2016-02-01 18:25
aplay -l
card 0: VLink [Musical Fidelity V-Link], device 0: USB Audio [USB Audio]

**Comment by efrecska** [comment] 2016-02-01 18:28
Subdevices: 1/1
Subdevice #0: subdevice #0,
card 1: ALSA...etc.
The listing hasn't changed. It is the same when it was working.
Thank you for your concerns,  Ed

**Comment by efrecska** [comment] 2016-02-01 18:37
.asoundrc:
pcm.!default {
type hw
card 1
}
ctl is as above
Changing to 0 doesn't make difference, it changes back at next reboot.
There is no /etc/asound.conf. I am a bit familiar with those and screwing them up never gave me 'Broken pipe errors'. That is new to me and seems to be related to a mess-up between AirFoil and shairport-sync???

**Comment by mikebrady** [comment] 2016-02-01 18:43
Right, so what happens if you use `-d hw:0`? The contents of those asound files will be irrelevant.

**Comment by efrecska** [comment] 2016-02-01 19:31
aplay -d hw:0 test.wav [44.1/16] is channeled to the onboard card (which is card=1) and works
aplay -D hw:0 test.wav: samp[le format non available. Available formats: -S24_3LE
I will create now a 24 bit wav and see.
Ed

**Comment by efrecska** [comment] 2016-02-01 19:45
aplay -D test.wav [44.1/24]: set params:1087: Channels count non available
If you are interested I may reinstall and recheck if it is AirFoil (Win v3.6.1) which causes the screw-up. 
Ed

**Comment by efrecska** [comment] 2016-02-01 21:09
Hi Mike!
aplay -d hw:0 test.wav [44.1/16] is channeled to the onboard card (which is card=1) and works.aplay -D hw:0 test.wav (goes probably to VLink): sample format non available. Available formats: -S24_3LEaplay -D test.wav [44.1/24]: set params:1087: Channels count non available.speaker-test -D hw:0 gives sample format problem.
If you are interested, I can reinstall the whole system and recheck if it is AirFoil (Win v3.6.1) which causes the crash. I may also try VOX from Mac OS. The point is that I want to stream 44.1/16 (or better) FLAC files to shairport-sync. I was playing FLAC on foobar via AirFoil when it crashed.Bests,
Ed
Date: Mon, 1 Feb 2016 10:43:17 -0800

**Comment by mikebrady** [comment] 2016-02-02 09:01
Hi Ed. I'm struggling trying to understand your system, I'm afraid.
 Perhaps it's the fact that the output from your commands isn't formatted in the post, but I just don't understand what's there.

Here, for example, is what I get from `aplay -l` on my Pi, which has three hardware devices – the built-in DAC, a USB DAC and an IQaudIO DAC. It's copied directly from the terminal window formatted in markdown to look right in the post:

```
pi@raspberrypi:~ $ aplay -l
**** List of PLAYBACK Hardware Devices ****
card 0: ALSA [bcm2835 ALSA], device 0: bcm2835 ALSA [bcm2835 ALSA]
  Subdevices: 8/8
  Subdevice #0: subdevice #0
  Subdevice #1: subdevice #1
  Subdevice #2: subdevice #2
  Subdevice #3: subdevice #3
  Subdevice #4: subdevice #4
  Subdevice #5: subdevice #5
  Subdevice #6: subdevice #6
  Subdevice #7: subdevice #7
card 0: ALSA [bcm2835 ALSA], device 1: bcm2835 ALSA [bcm2835 IEC958/HDMI]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 1: Device [USB Audio Device], device 0: USB Audio [USB Audio]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 2: IQaudIODAC [IQaudIODAC], device 0: IQaudIO DAC HiFi pcm512x-hifi-0 []
  Subdevices: 0/1
  Subdevice #0: subdevice #0
pi@raspberrypi:~ $ 
```
If you could post just that, I could begin to understand what you've got there, 

The contents of `asoundrc` are irrelevant if you direct Shairport Sync's output to a hardware device – one whose name begins with `hw`. Your posts seem contradictory on which device is the VLink device.

**Comment by efrecska** [comment] 2016-02-02 11:50
Hi Mike,
Here is the full aplay -l output:card 0: VLink [Musical Fidelity V-Link], device 0: USB Audio [USB Audio]  Subdevices: 1/1  Subdevice #0: subdevice #0card 1: ALSA [bcm2835 ALSA], device 0: bcm2835 ALSA [bcm2835 ALSA]  Subdevices: 8/8  Subdevice #0: subdevice #0  Subdevice #1: subdevice #1  Subdevice #2: subdevice #2  Subdevice #3: subdevice #3  Subdevice #4: subdevice #4  Subdevice #5: subdevice #5  Subdevice #6: subdevice #6  Subdevice #7: subdevice #7card 1: ALSA [bcm2835 ALSA], device 1: bcm2835 ALSA [bcm2835 IEC958/HDMI]  Subdevices: 1/1  Subdevice #0: subdevice #0
I am going to reinstall shairport-sync again starting from reinstalling Rasbian Wheezy (I cannot fix the 'Broken pipe' issue of this current system setup).What would be the command line starting command for card:0?

  
  


The final goal will be automatic startup at system login, but I am not there yet.Bests,  Ed

**Comment by efrecska** [comment] 2016-02-02 13:04
Current status (streaming MP3 from iTunes) with the aplay -l as above:

  
  


$ shairport-sync -a Airpi -- -d hw:0audio_alsa: Sample format not available for device "hw:0": Invalid argument$ shairport-sync -a Airpi -- -d hw:1works on the onboard card$ shairport-sync -a Airpi -- -d plughw:0works with the USB card (sounds good, no cracks or clippings)$ shairport-sync -a Airpi -- -d plughw:1works on the onboard cardI have been here before...Before using AirFoil for streaming FLAC I will try VOX from Mac OS.Ed

**Comment by mikebrady** [comment] 2016-02-02 13:19
Hi Ed. Thanks for this. This is what I think you sent:

```
card 0: VLink [Musical Fidelity V-Link], device 0: USB Audio [USB Audio]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 1: ALSA [bcm2835 ALSA], device 0: bcm2835 ALSA [bcm2835 ALSA]
  Subdevices: 8/8
  Subdevice #0: subdevice #0
  Subdevice #1: subdevice #1
  Subdevice #2: subdevice #2
  Subdevice #3: subdevice #3
  Subdevice #4: subdevice #4
  Subdevice #5: subdevice #5
  Subdevice #6: subdevice #6
  Subdevice #7: subdevice #7
card 1: ALSA [bcm2835 ALSA], device 1: bcm2835 ALSA [bcm2835 IEC958/HDMI]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
```
(It would be great if you would use Markdown to make the outputs look tidy – put three backquotes on a line above and below the output text.)

So, the VLink is hardware device 0, subdevice 0. Thus, the shairport command would be:

```
shairport-sync -a AirPi -- -d hw:0,0
```
From your next post, it seems like Shairport Sync is returning a message:
```
Sample format not available for device "hw:0"
```
If that is the case, then what's happening is that the VLink will not accept the 16 bit little-endian interleaved CD-type samples – "S16LE" – that Shairport Sync generates. If you can get that message again with the command line above, it's pretty definitive that the VLink is incompatible with Shairport Sync. You can test `hw:0` with `aplay` by trying to play a 44.1/16 stereo sample. I'm guessing that it will refuse.

Overall, I think that what's happening is that the VLink accepts 44.1/24 but not 44.1/16. The virtual device plughw:0,0 is accepting stuff at 44.1/16 from shairport sync and transcoding not to 44.1/24 before passing it to the VLink, making is kinda-work. The problem is that the plughw device (a) takes up a lot of processing time and (b) does not report latency, causing the system to fail after a short time.

Let me know your results.

**Comment by efrecska** [comment] 2016-02-02 13:43
Hi Mike!Indeed! I borrowed a HighFace USB dongle and it can handle all my stuff at hw:0.I just wonder, what caused those unrecoverable 'Broken pipe' errors, but really don't care unless they show up again.For automatic start at system boot I will follow your wiki (looks pretty discouraging for me).Where to start with it? Need a change in any conf file?Many thanks for your help!Ed

**Comment by mikebrady** [comment] 2016-02-02 14:49
Hi Ed. It's pretty straightforward really. If you follow the instructions in the README.md for a "System V" installation, all you have to do is enter a few settings in the `/etc/shairport-sync.conf` file, like the name you want and the out device. There are some examples too. Automatic startup is really handled very easily.

**Comment by mikebrady** [comment] 2016-02-02 14:50
What was causing the  'Broken pipe' errors? I have no idea, at this distance, I'm afraid...

**Comment by mikebrady** [comment] 2016-02-02 14:51
You don't need to do anything with any asoundrc files or any of that kind of stuff. Just get the settings in `/etc/shairport-sync.conf` right.

**Comment by mikebrady** [comment] 2016-02-02 14:51
Oops – didn't mean to close this.

**Comment by efrecska** [comment] 2016-02-02 18:16
A little editing doesn't sound problematic.
I am still surprised that the VLink a valued USB sound card cannot handle the most common format: 44.1/16.

**Comment by mikebrady** [comment] 2016-02-02 18:39
Yeah, that is very surprising to me, to be honest. It would be great to get some independent confirmation of that, but I can't find any details in the manuals on line. Also, it might be that the Linux driver is simply not exposing the facility. The device itself sounds really interesting. Finally, I would like to enable Shairport Sync to do 44.1/24 and 44.1/32, byt it won't be soon – don't hold your breath!

**Comment by mikebrady** [comment] 2019-10-11 16:11
Shairport Sync can now deal with 8/16/24 and 32 bit stereo at 44,100/88,200/176400 frames per second and can configure itself automatically. Closing this inactive issue. Please open a new one if necessary.

**Closed by mikebrady** 2019-10-11 16:11 UTC
Labels: question
