### ISSUE TITLE
Speaker blips when song manually starts and blips when manually stopped - V3.0.2 [FIXED]

### ISSUE THREAD

**Issue by kiwi-ed** [mikebrady/shairport-sync#548] opened 2017-06-30 14:55 UTC
Hi,

I've just updated from version 2.8 to 3.0.2 and now I seem to have inherited an issue. As mentioned in the title I get loud blips lasting ~100-300ms when starting or stopping the song manually. Interestingly the blip on stopping the song often appears to be a very tiny snip-it of the song itself. In slow-motion terms it's like the song is stopped then 1-2 seconds later the song is started again but immediately stopped again.

Thanks.

**Comment by mikebrady** [comment] 2017-06-30 19:25
Thanks for the report. What client are you playing from – for example, is it iTunes?

**Comment by kiwi-ed** [comment] 2017-06-30 20:49
iTunes, yes on Win7. The earlier 2.8 version was fine on the same client.





________________________________

**Comment by mikebrady** [comment] 2017-07-04 10:50
Hi there. I have been checking back, and I'm pretty sure we have corrected this problem some time past in the `development` version, if you'd care to try it out.

**Comment by kiwi-ed** [comment] 2017-07-04 11:14
Thanks! When do you think the normal downloadable release will catch up?

One other question, does shairport-sync use real time scheduling? A few times a day and only when using shairport-sync I get a "RT throttle" warning as some RT process/app is hogging the kernel. I use shairport-sync on a ~800Mhz Freescale i.mx7s processor over WIFI. I'm spinning shairport-sync up via start-stop-daemon which apparently does do a little RT stuff itself.


BR,


Ed.

________________________________

**Comment by mikebrady** [comment] 2017-07-05 06:58
It should be fairly soon – the next couple of weeks. It needs testing.

Shairport Sync doesn't knowingly use any real time scheduling stuff. I was trying to avoid that kind of thing so that it could live in peace in a regular Linux installation :)

**Comment by George-ou812** [comment] 2017-07-25 10:17
Believe it or not the RT throttle was actually being caused by over use of iw dev wlan0 link| to monitor if I was still connected to the AP. Once I started streaming music the IOCTL calls ( I'm assuming ) fought with the high wifi use and ground to a halt. Definitely fixed the RT issue getting rid of iw..

Cheers for the help..

**Comment by mikebrady** [comment] 2019-10-24 10:17
Closing the issue. Please open a new one if necessary.

**Closed by mikebrady** 2019-10-24 10:17 UTC
Labels: bug, fixed
