### ISSUE TITLE
3.3RC2 OpenWRT: alsa_backend_state => abm_disconnected

### ISSUE THREAD

**Issue by m42i** [mikebrady/shairport-sync#832] opened 2019-04-07 09:32 UTC
Sorry for the hickup creating, closing and reopening the ticket.

I was running 3.2 on OpenWRT 18.06 with an USB audio device fine and upgraded to 3.3RC2 and it stopped working.

This is what I get at the beginning of the log:

```
alsa: init() -- alsa_backend_state => abm_disconnected.
stall_monitor_error_threshold is 0x33333333, with alsa_maximum_stall_time of 0.200000 sec.
alsa: disable_standby_mode is "never".
alsa: output device name is "default".
The processor is running big-endian.
software version: "3.3rc2-libdaemon-mbedTLS-Avahi-ALSA-soxr-metadata-sysconfdir:/etc"
log verbosity is 3.
```

Using the default configuration gives the same message.

Full logs of connecting and playing a 3 second .wav file from macOS to shairport-sync.
[3.3RC2_mbedTLS_alsa_openwrt.log](https://github.com/mikebrady/shairport-sync/files/3051406/3.3RC2_mbedTLS_alsa_openwrt.log)
[3.2_mbedTLS_alsa_openwrt.log](https://github.com/mikebrady/shairport-sync/files/3051407/3.2_mbedTLS_alsa_openwrt.log)

**Comment by m42i** [comment] 2019-04-07 10:17
The current development branch doesn't work either and won't even give any log output.

**Comment by mikebrady** [comment] 2019-04-07 12:02
Thanks for the report. I'll have a look. It does work on Barrier Breaker -- 14.07, so it is time to bring it up to date!

**Comment by mikebrady** [comment] 2019-04-07 21:34
Well, I can reproduce the problem. It may take a little while to get to the source of it.

**Comment by mikebrady** [comment] 2019-04-09 22:14
Okay, this has been interesting.

There seem to have been many changes to the audio system. I have been using a TP Link TL-WR710N and a USB DAC. With Barrier Breaker, Shairport Sync ("SPS") Version 3.3rc2 worked perfectly. Updating to OpenWRT 18.06 on the same device with the same DAC caused problems like those you report.

 A few points:

* SPS is designed for, and works best, when it has direct access to a real hardware output device -- one with a name beginning with `hw:`. A device `hw:0` was present in Barrier Breaker on this device with the USB DAC, but it's gone in 18.06, which is very weird. 
* The ALSA `default` device does not seem to be a direct connection to hardware. Instead it seems to be some kind of a virtual device.
* SPS 3.3 has revised DAC delay timing software which relies on timing information coming directly from the hardware. Unfortunately, the `default` device is providing degraded versions of the hardware timing  information, causing the problems you have experienced.

I've just pushed an update in the `transit` branch that automatically reverts to the standard DAC delay timing software unless the output device is definitely a hardware device and this gets around the problem.

I'd be obliged if you gave it a spin and let us know how it goes -- it's working very nicely for me now on OpenWRT 18.06.

If my analysis is correct, it would be great if the hardware DACs were exposed in 18.06 as they were in past versions of OpenWRT.

**Comment by mikebrady** [comment] 2019-04-09 22:20
One other thing -- to see log messages on the command line, there's a new command line option: `-u`. This is to avoid reliance on `libdaemon` for logging, as it is no longer always necessary to demonise Shairport Sync. 
So, something like:
```
$ shairport-sync -vu --statistics
```
will give you log entries on the console.

**Comment by m42i** [comment] 2019-04-13 16:00
Thanks for the update! I too use a WR710N. 

I tried the `transit` branch, but the result is not great. Playing my 3 second .wav test file plays okay. But playing music results in distorted noise after some seconds and I get the following in the logs:
```
2.891184939|alsa: device status returns fault status -32 and SND_PCM_STATE_* 3  for play.
0.002852802|alsa: underrun while writing 352 samples to alsa device.
4.697025696|alsa: device status returns fault status -32 and SND_PCM_STATE_* 3  for play.
0.002297559|alsa: underrun while writing 351 samples to alsa device.
0.587078326|alsa: device status returns fault status -32 and SND_PCM_STATE_* 3  for play.
0.002834886|alsa: underrun while writing 351 samples to alsa device.
0.592201656|alsa: device status returns fault status -32 and SND_PCM_STATE_* 3  for play.
0.002419246|alsa: underrun while writing 351 samples to alsa device.
0.580060736|alsa: device status returns fault status -32 and SND_PCM_STATE_* 3  for play.
0.002876038|alsa: underrun while writing 351 samples to alsa device.
```

My wifi setup isn't ideal. The signal travels to another room and back, but with 3.2 i don't have this problem.

[3.3rc3.log](https://github.com/mikebrady/shairport-sync/files/3076422/3.3rc3.log)

**Comment by mikebrady** [comment] 2019-04-13 16:41
Thanks for the update. One thing that has changed in 3.2 versus 3.2 is that, if `soxr` is included in the build configuration, then interpolation is set by default to `soxr` at runtime. Up until now, you had to change the setting from `basic` to `soxr`. I notice that it is enabled your logs:
```
 0.000456016|stuffing option is "1" (0-basic, 1-soxr).
```
Could you try turning it off please? It may be that `soxr` interpolation is causing the device to bog down, as it's computationally very expensive. If this turns out to be the case, then I'll revert the default behaviour to `basic` no matter what the build configuration is.

**Comment by m42i** [comment] 2019-04-14 13:44
You were right, with the basic setting the playback is good.

**Comment by mikebrady** [comment] 2019-04-14 14:04
Many thanks. I’ll revert the default setting to `basic`.

**Comment by mikebrady** [comment] 2019-04-17 16:08
Actually I've done something slightly different. I've added an `auto` setting for the interpolation and a check is now done to see if the device is fast enough. If so, and if `soxr` support has been included at build time, `soxr` interpolation will be chosen, otherwise `basic` interpolation will be chosen. If you got a chance to try it out, at your leisure, it would b appreciated. It's in the `transit` branch at present.

**Comment by m42i** [comment] 2019-05-05 16:24
I finally had a chance to test the latest transit branch.

It seems that the basic interpolation is chosen correctly, but I still get a lot of noise.

I noticed as output_format S32 is chosen. But uncommenting and changing the setting to S16 doesn't change this.

Log for S16 and 44100 settings:
[shairport_sync_transit_S16_44k.log](https://github.com/mikebrady/shairport-sync/files/3145759/shairport_sync_transit_S16_44k.log)

**Comment by mikebrady** [comment] 2019-05-05 17:40
Thanks for testing. I’ve been doing a bit more digging on this. It seems the `default` device is a virtual device. Furthermore, I wrongly concluded that the hardware devices were not available for some reason. But actually they are, except that they do not accept the default `S16`, which is `S16_BE` on a big-endian device. Now, with automatic format selection, if you change the output device to the real hardware device — `hw:0`, `S16_LE` will be chosen for it, and for me at least, there is much less interpolation. It’s worth a try.

**Comment by m42i** [comment] 2019-05-06 14:43
You're right. Setting the hardware device to `hw:0` makes shairport-sync choose S16_LE as output_format and music plays fine.

**Comment by mikebrady** [comment] 2019-05-06 19:20
Great. Many thanks for your help with this.

**Comment by mikebrady** [comment] 2019-06-09 14:12
Closing this, as the issue has been resolved.

**Closed by mikebrady** 2019-06-09 14:12 UTC
