### ISSUE TITLE
[Problem]: “Bus error (core dumped)” when trying to play a playlist from OwnTone with MQTT enabled

### ISSUE THREAD

**Issue by aaronk6** [mikebrady/shairport-sync#1910] opened 2024-09-24 16:54 UTC
### What happened?

When I try to play a playlist from OwnTone on a shairport-sync speaker, shairport-sync crashes with the message “Bus error (core dumped)”.

I’m still investigating this, but I can reliably reproduce this with multiple playlists that contain Spotify tracks. In contrast, radio streams (via OwnTone) work fine.

I will add more findings later, but maybe this is already helpful at this stage. Let me know if there’s anything else I should try to narrow it down.

### Relevant log output

```
bad_dg_1     |         48.034405397 "rtsp.c:5677" Connection 3: New connection from 192.168.88.150:59118 to self at 192.168.88.8:7000.
bad_dg_1     |          0.000695982 "rtsp.c:2632" OPTIONS request
bad_dg_1     |          0.001671129 "rtsp.c:2632"   Type: "CSeq", content: "1"
bad_dg_1     |          0.000050019 "rtsp.c:2632"   Type: "User-Agent", content: "owntone/28.10"
bad_dg_1     |          0.000047611 "rtsp.c:2632"   Type: "Client-Instance", content: "68906BCA5356CD45"
bad_dg_1     |          0.000044815 "rtsp.c:2632"   Type: "DACP-ID", content: "68906BCA5356CD45"
bad_dg_1     |          0.000042963 "rtsp.c:2632"   Type: "Active-Remote", content: "3232258051"
bad_dg_1     |          0.000041074 "rtsp.c:2632"   No Content Plist. Content length: 0.
bad_dg_1     |          0.001705907 "rtsp.c:4497" Connection 3: ANNOUNCE
bad_dg_1     |          0.000074834 "rtsp.c:586" Connection 3: request to acquire principal_conn.
bad_dg_1     |          0.000048240 "rtsp.c:4501" Connection 3: ANNOUNCE has acquired play lock.
bad_dg_1     |          0.003470852 "rtsp.c:4543" Connection 3: Classic AirPlay connection from 192.168.88.150:59118 to self at 192.168.88.8:7000.
bad_dg_1     |          0.000103074 "rtsp.c:4719" Play connection from user agent "owntone/28.10" on RTSP conversation thread 3.
bad_dg_1     |          0.000502148 "rtsp.c:4751" Connection 3: ANNOUNCE has completed.
bad_dg_1     |          0.001764871 "rtsp.c:3453" Connection 3: SETUP
bad_dg_1     |          0.000074592 "rtsp.c:3460" Connection 3: SETUP: Active-Remote string seen: "3232258051".
bad_dg_1     |          0.002293482 "mqtt.c:108" [MQTT]: publishing under shairport-sync/bad_dg/active_remote_id
bad_dg_1     |          0.000169704 "rtsp.c:3480" Connection 3: SETUP: DACP-ID string seen: "68906BCA5356CD45".
bad_dg_1     |          0.000427518 "mqtt.c:108" [MQTT]: publishing under shairport-sync/bad_dg/dacp_id
bad_dg_1     |          0.000150222 "rtp.c:1033" Connection 3: SETUP -- Connection from 192.168.88.150 to self at 192.168.88.8.
bad_dg_1     |          0.000282908 "rtsp.c:3542" Connection 3: SETUP DACP-ID "68906BCA5356CD45" from 192.168.88.150 to 192.168.88.8 with UDP ports Control: 6001, Timing: 6002 and Audio: 6003.
bad_dg_1     |          0.000503537 "metadata_hub.c:570" MH Client IP set to: "192.168.88.150"
bad_dg_1     |          0.000388722 "mqtt.c:108" [MQTT]: publishing under shairport-sync/bad_dg/client_ip
bad_dg_1     |          0.000563981 "mqtt.c:108" [MQTT]: publishing under shairport-sync/bad_dg/server_ip
bad_dg_1     |          0.001666482 "rtsp.c:1575" Connection 3: RECORD
bad_dg_1     |          0.000051648 "dbus-service.c:226" Build metadata
bad_dg_1     |          0.000017000 "rtsp.c:1581" Connection 3: Classic AirPlay connection from 192.168.88.150:59118 to self at 192.168.88.8:7000.
bad_dg_1     |          0.000066685 "activity_monitor.c:64" abeg
bad_dg_1     |          0.000564389 "mqtt.c:108" [MQTT]: publishing under shairport-sync/bad_dg/active_start
bad_dg_1     |          0.000601482 "player.c:3611" Connection 3: player_play.
bad_dg_1     |          0.000787981 "mqtt.c:108" [MQTT]: publishing under shairport-sync/bad_dg/play_start
bad_dg_1     |          0.000654556 "activity_monitor.c:167" am_state: am_active
bad_dg_1     |          0.001466814 "rtsp.c:3612" Connection 3: request to set AirPlay Volume to: -10.800000.
bad_dg_1     |          0.004714556 "mpris-service.c:167" Build metadata
bad_dg_1     |          0.001986778 "metadata_hub.c:622" MH Server IP set to: "192.168.88.8"
bad_dg_1     |          0.002056685 "dbus-service.c:226" Build metadata
bad_dg_1     |          0.000876981 "dbus-service.c:636" >> setting volume to -10.8000.
bad_dg_1     |          0.000084537 "player.c:3476" Software attenuation set to -1733.400031, i.e 8907.993989 out of 65,536, for airplay volume of -10.800000
bad_dg_1     |          0.000038149 "loudness.c:47" Volume: -17.3 dB - Loudness gain @10Hz: 0.0 dB
bad_dg_1     |          0.000084314 "player.c:3517" player_volume_without_notification: volume mode is 0, airplay volume is -10.80, software_attenuation dB: -17.33, hardware_attenuation dB: 0.00, muting is disabled.
bad_dg_1     |          0.000284778 "mqtt.c:108" [MQTT]: publishing under shairport-sync/bad_dg/volume
bad_dg_1     |          0.002194259 "mpris-service.c:167" Build metadata
bad_dg_1     |          0.001548815 "dbus-service.c:226" Build metadata
bad_dg_1     |          0.000555834 "mpris-service.c:167" Build metadata
bad_dg_1     |          0.001010222 "mqtt.c:108" [MQTT]: publishing under shairport-sync/bad_dg/title
bad_dg_1     | Bus error (core dumped)
bad_dg_1     | s6-rc: info: service legacy-services: stopping
bad_dg_1     | s6-rc: info: service legacy-services successfully stopped
bad_dg_1     | s6-rc: info: service syslogd: stopping
bad_dg_1     | s6-rc: info: service 04-nqptp: stopping
bad_dg_1     | s6-rc: info: service 03-avahi: stopping
bad_dg_1     | Got SIGTERM, quitting.
```

### System Information.

Raspberry Pi 4 (2 GB)

### Configuration Information.

```
# shairport-sync --displayConfig
         0.000969407 "shairport.c:2129" >> Display Config Start.
         0.006077056 "shairport.c:2129"
         0.000043481 "shairport.c:2129" From "uname -a":
         0.000154334 "shairport.c:2129"  Linux dc15a8711008 6.1.0-rpi4-rpi-v8 #1 SMP PREEMPT Debian 1:6.1.54-1+rpt2 (2023-10-05) aarch64 Linux
         0.008257481 "shairport.c:2129"
         0.000046130 "shairport.c:2129" From /etc/os-release:
         0.000048926 "shairport.c:2129"  Alpine Linux v3.17
         0.003254870 "shairport.c:2129"
         0.000076519 "shairport.c:2129" Shairport Sync Version String:
         0.000042018 "shairport.c:2129"  4.3.4-dirty-AirPlay2-smi10-alac-OpenSSL-Avahi-ALSA-pa-dummy-stdout-pipe-soxr-convolution-metadata-mqtt-dbus-mpris-sysconfdir:/etc
         0.000103778 "shairport.c:2129"
         0.000054148 "shairport.c:2129" Command Line:
         0.000388056 "shairport.c:2129"  shairport-sync --displayConfig
         0.000153870 "shairport.c:2129"
         0.000047482 "shairport.c:2129" Configuration File:
         0.000043666 "shairport.c:2129"  /etc/shairport-sync.conf
         0.000039148 "shairport.c:2129"
         0.000656500 "shairport.c:2129" Configuration File Settings:
         0.000058778 "shairport.c:2129"  general :
         0.000041871 "shairport.c:2129"  {
         0.000043796 "shairport.c:2129"    name = "Bad DG";
         0.000043111 "shairport.c:2129"    output_backend = "pa";
         0.000038926 "shairport.c:2129"    airplay_device_id = 0x242C0A85803L;
         0.000228370 "shairport.c:2129"  };
         0.000227926 "shairport.c:2129"  sessioncontrol :
         0.000024759 "shairport.c:2129"  {
         0.000032112 "shairport.c:2129"    allow_session_interruption = "yes";
         0.000019111 "shairport.c:2129"  };
         0.000027166 "shairport.c:2129"  pa :
         0.000019648 "shairport.c:2129"  {
         0.000019408 "shairport.c:2129"    sink = "bad_dg";
         0.000018852 "shairport.c:2129"  };
         0.000122185 "shairport.c:2129"  diagnostics :
         0.000187759 "shairport.c:2129"  {
         0.000041519 "shairport.c:2129"    log_verbosity = 2;
         0.000060166 "shairport.c:2129"  };
         0.000048871 "shairport.c:2129"  metadata :
         0.000038333 "shairport.c:2129"  {
         0.000037167 "shairport.c:2129"    enabled = "yes";
         0.000117981 "shairport.c:2129"    include_cover_art = "yes";
         0.000071685 "shairport.c:2129"    cover_art_cache_directory = "/tmp/shairport-sync/.cache/coverart";
         0.000070241 "shairport.c:2129"    pipe_name = "/tmp/shairport-sync-metadata";
         0.000056019 "shairport.c:2129"    pipe_timeout = 5000;
         0.000032314 "shairport.c:2129"  };
         0.000019926 "shairport.c:2129"  mqtt :
         0.000019056 "shairport.c:2129"  {
         0.000019259 "shairport.c:2129"    enabled = "yes";
         0.000019241 "shairport.c:2129"    hostname = "homeassistant.example.com";
         0.000193648 "shairport.c:2129"    port = 1883;
         0.000021722 "shairport.c:2129"    username = "shairport";
         0.000017778 "shairport.c:2129"    password = "redacted";
         0.000031519 "shairport.c:2129"    topic = "shairport-sync/bad_dg";
         0.000040592 "shairport.c:2129"    publish_raw = "no";
         0.000038519 "shairport.c:2129"    publish_parsed = "yes";
         0.000038778 "shairport.c:2129"    publish_cover = "no";
         0.000040388 "shairport.c:2129"    enable_autodiscovery = "yes";
         0.000116926 "shairport.c:2129"    enable_remote = "no";
         0.000231463 "shairport.c:2129"  };
         0.000023297 "shairport.c:2129"
         0.000017648 "shairport.c:2129" >> Display Config End.
         0.000031666 "shairport.c:2131" >> Goodbye!
         0.000044389 "shairport.c:1592" exit function called...
         0.000059908 "shairport.c:1602" Stopping the activity monitor.
         0.000040777 "shairport.c:1604" Stopping the activity monitor done.
         0.000063445 "shairport.c:1607" Stopping DACP Monitor
         0.000043333 "shairport.c:1609" Stopping DACP Monitor Done
         0.000038611 "shairport.c:1620" Stopping D-Bus service
         0.000377556 "dbus-service.c:1219" stopping dbus service
         0.000176611 "shairport.c:1622" Stopping D-Bus service done
         0.000139685 "shairport.c:1638" Stopping metadata hub
         0.000022945 "shairport.c:1640" Stopping metadata done
         0.000018000 "shairport.c:1644" Stopping metadata
         0.000038074 "shairport.c:1646" Stopping metadata done
         0.000125018 "shairport.c:1729" normal exit
```

### PulseAudio or PipeWire installed?

- [X] Check if your system uses a Sound Server.

### How did you install Shairport Sync?

Docker

### Check previous issues

- [X] Confirm

**Comment by aaronk6** [comment] 2024-09-24 20:42
Turns out it only happens when MQTT is enabled.

**Comment by mikebrady** [comment] 2024-09-25 06:59
Thanks. I’m away from my machines for about the next two weeks, so it’ll take a little while to fix this, I’m afraid.

**Comment by aaronk6** [comment] 2024-09-25 07:34
No worries, I’ll see if I can further narrow it done in the meantime.

**Comment by mikebrady** [comment] 2024-11-01 10:32
Before I dig in to this, I was just wondering if you had succeeded in narrowing this problem down at all? Is it reliably reproducible?

**Comment by aaronk6** [comment] 2024-11-04 13:46
It only happens with certain combination and is not clearly tied to MQTT. Let me revisit this in the next days to create an overview of the combinations I tried.

**Comment by aaronk6** [comment] 2024-11-12 20:43
My first guess was that it has something to do with the title sent via MQTT, as it’s crashing right after this log message:

```
0.001010222 "mqtt.c:108" [MQTT]: publishing under shairport-sync/bad_dg/title
```

However, even after modifying `mqtt_publish` as shown below, it still crashes when playing a file via OwnTone.

```
void mqtt_publish(char *topic, char *data_in, uint32_t length_in) {
  debug(2, "[MQTT]: NOT publishing! (for debugging)");
  return;
}
```

Results in:

```
bad_dg_1     |          0.001188759 "mqtt.c:97" [MQTT]: NOT publishing! (for debugging)
bad_dg_1     | Bus error (core dumped)
```

**Comment by mikebrady** [comment] 2024-11-28 15:24
Haven't forgotten this!

**Comment by aaronk6** [comment] 2024-12-01 20:13
No worries! Let me know if there’s anything that would be useful for me to try.

**Comment by mikebrady** [comment] 2024-12-02 10:57
Just digging in to this now, building the latest version. There is an anomaly. You have:
```
0.001010222 "mqtt.c:108" [MQTT]: publishing under shairport-sync/bad_dg/title
```
The anomaly is the line number -- 108. In my case, please see below -- it's line 237. So, I wonder if the files are up to date or is it just an oversight?

Here is the Config:
```
>> Display Config Start.

From "uname -a":
 Linux RaspberryPi5B 6.6.51+rpt-rpi-2712 #1 SMP PREEMPT Debian 1:6.6.51-1+rpt3 (2024-10-08) aarch64 GNU/Linux

From /etc/os-release:
 Debian GNU/Linux 12 (bookworm)

From /sys/firmware/devicetree/base/model:
 Raspberry Pi 5 Model B Rev 1.0

Shairport Sync Version String:
 4.3.5-dev-58-gd8442c1a-AirPlay2-smi10-OpenSSL-Avahi-ALSA-jack-ao-soundio-soxr-metadata-mqtt-dbus-sysconfdir:/etc

Command Line:
 ./shairport-sync --displayConfig

Configuration File:
 /etc/shairport-sync.conf

Configuration File Settings:
 pw : 
 {
 };
 stdout : 
 {
 };
 ao : 
 {
 };
 mqtt : 
 {
   enabled = "yes";
   hostname = "localhost";
   port = 1883;
   username = "shairport";
   password = "shairport";
   topic = "shairport-sync/bad_dg";
   publish_parsed = "yes";
   enable_autodiscovery = "yes";
   enable_remote = "no";
 };

>> Display Config End.
>> Goodbye!
```
Here is a log of something that seems fairly close to the log above
```
       442.107525274 "rtsp.c:5691" Connection 3: New connection from 192.168.50.123:43078 to self at 192.168.50.44:7000.
         0.000499018 "rtsp.c:2646" OPTIONS request
         0.000016000 "rtsp.c:2646"   Type: "CSeq", content: "1"
         0.000005241 "rtsp.c:2646"   Type: "User-Agent", content: "owntone/28.10"
         0.000004111 "rtsp.c:2646"   Type: "Client-Instance", content: "AD6ED84659016DE7"
         0.000003630 "rtsp.c:2646"   Type: "DACP-ID", content: "AD6ED84659016DE7"
         0.000003500 "rtsp.c:2646"   Type: "Active-Remote", content: "3720609400"
         0.000003777 "rtsp.c:2646"   No Content Plist. Content length: 0.
         0.003790334 "rtsp.c:4511" Connection 3: ANNOUNCE
         0.000009815 "rtsp.c:586" Connection 3: request to acquire principal_conn.
         0.000004833 "rtsp.c:4515" Connection 3: ANNOUNCE has acquired play lock.
         0.000652944 "rtsp.c:4557" Connection 3: Classic AirPlay connection from 192.168.50.123:43078 to self at 192.168.50.44:7000.
         0.000025537 "rtsp.c:4733" Play connection from user agent "owntone/28.10" on RTSP conversation thread 3.
         0.000017241 "rtsp.c:4765" Connection 3: ANNOUNCE has completed.
         0.001781648 "rtsp.c:3467" Connection 3: SETUP
         0.000010000 "rtsp.c:3474" Connection 3: SETUP: Active-Remote string seen: "3720609400".
         0.000011482 "rtsp.c:3494" Connection 3: SETUP: DACP-ID string seen: "AD6ED84659016DE7".
         0.000002240 "rtp.c:1033" Connection 3: SETUP -- Connection from 192.168.50.123 to self at 192.168.50.44.
         0.000014852 "mqtt.c:237" [MQTT]: publishing under shairport-sync/bad_dg/active_remote_id
         0.000033556 "mqtt.c:237" [MQTT]: publishing under shairport-sync/bad_dg/dacp_id
         0.000009093 "rtsp.c:3556" Connection 3: SETUP DACP-ID "AD6ED84659016DE7" from 192.168.50.123 to 192.168.50.44 with UDP ports Control: 6001, Timing: 6002 and Audio: 6003.
         0.000008000 "mqtt.c:237" [MQTT]: publishing under shairport-sync/bad_dg/client_ip
         0.000097555 "metadata_hub.c:570" MH Client IP set to: "192.168.50.123"
         0.000025296 "metadata_hub.c:622" MH Server IP set to: "192.168.50.44"
         0.000023463 "mqtt.c:237" [MQTT]: publishing under shairport-sync/bad_dg/server_ip
         0.001736871 "rtsp.c:1589" Connection 3: RECORD
         0.000008870 "rtsp.c:1595" Connection 3: Classic AirPlay connection from 192.168.50.123:43078 to self at 192.168.50.44:7000.
         0.000005278 "activity_monitor.c:64" abeg
         0.000014796 "mqtt.c:237" [MQTT]: publishing under shairport-sync/bad_dg/active
         0.000005963 "activity_monitor.c:167" am_state: am_active
         0.000006408 "mqtt.c:237" [MQTT]: publishing under shairport-sync/bad_dg/active_start
         0.002571925 "audio_alsa.c:608" alsa: output format chosen is "S32".
         0.000150463 "audio_alsa.c:651" alsa: output speed chosen is 44100.
         0.000564593 "audio_alsa.c:1599" alsa: update timestamps available
         0.000010926 "audio_alsa.c:257" alsa: precision delay timing is not available because it's not definitely a hardware device.
         0.000005037 "audio_alsa.c:820" PCM handle name = 'default'
         0.000003667 "audio_alsa.c:834" alsa device parameters:
         0.000006148 "audio_alsa.c:837"   access type = MMAP_INTERLEAVED
         0.000008463 "audio_alsa.c:840"   format = 'S32_LE' (Signed 32 bit Little Endian)
         0.000008889 "audio_alsa.c:844"   subformat = 'STD' (Standard)
         0.000005333 "audio_alsa.c:848"   number of channels = 2
         0.000004981 "audio_alsa.c:851"   number of significant bits = 32
         0.000004612 "audio_alsa.c:859"   rate = 44100 frames per second (precisely).
         0.000004370 "audio_alsa.c:868"   precise (rational) rate = 44100.000 frames per second (i.e. 44100/1).
         0.000007778 "audio_alsa.c:882"   period_time = 5804 us (>).
         0.000005426 "audio_alsa.c:892"   period_size = 256 frames (precisely).
         0.000005018 "audio_alsa.c:908"   buffer_time = 1486077 us (>).
         0.000003908 "audio_alsa.c:921"   buffer_size = 65536 frames (>).
         0.000005148 "audio_alsa.c:931"   periods_per_buffer = 256 (precisely).
         0.000003907 "audio_alsa.c:1980" alsa: prepare() -- opened output device
         0.000004148 "player.c:3632" Connection 3: player_play.
         0.000051963 "mqtt.c:237" [MQTT]: publishing under shairport-sync/bad_dg/playing
         0.000014537 "mqtt.c:237" [MQTT]: publishing under shairport-sync/bad_dg/play_start
         0.001302130 "rtp.c:321" rtp_control_receiver start
         0.000050778 "dacp.c:411" set_dacp_server_information set IP to "192.168.50.123" and DACP id to "AD6ED84659016DE7".
         0.000081722 "player.c:2259" Set initial volume to -24.000000.
         0.000033759 "player.c:3515" Software attenuation set to -5489.100000, i.e 118.013022 out of 65,536, for airplay volume of -24.000000
         0.000023574 "loudness.c:47" Volume: -54.9 dB - Loudness gain @10Hz: 17.4 dB
         0.000005334 "player.c:3538" player_volume_without_notification: volume mode is 0, airplay volume is -24.00, software_attenuation dB: -54.89, hardware_attenuation dB: 0.00, muting is disabled.
         0.000008944 "player.c:2262" Play begin
         0.000026389 "mqtt.c:237" [MQTT]: publishing under shairport-sync/bad_dg/volume
         0.000029000 "rtp.c:583" rtp_timing_sender start
         0.000063185 "rtp.c:609" AP1 clock sender thread: initialised.
         0.000100296 "rtsp.c:3626" Connection 3: request to set AirPlay Volume to: -11.699999.
         0.000019741 "player.c:3515" Software attenuation set to -1935.629669, i.e 7057.730909 out of 65,536, for airplay volume of -11.699999
         0.000104759 "loudness.c:47" Volume: -19.4 dB - Loudness gain @10Hz: 0.0 dB
         0.000032223 "player.c:3538" player_volume_without_notification: volume mode is 0, airplay volume is -11.70, software_attenuation dB: -19.36, hardware_attenuation dB: 0.00, muting is disabled.
         0.000006463 "mqtt.c:237" [MQTT]: publishing under shairport-sync/bad_dg/volume
         0.001982111 "rtp.c:750" AP1 clock receiver thread: initialised.
         0.000021296 "rtp.c:771" clock synchronisation request: return time is    2.262 milliseconds.
         0.019939796 "rtp.c:468" New latency: 99225, sync latency: 88200, minimum latency: 0, maximum latency: 0, fixed offset: 11025, audio_backend_latency_offset: 0.000000.
         0.000016722 "rtp.c:515" AP1 control thread: set_ntp_anchor_info: rtptime: 2680509551, networktime: 1ea7ecb368511b5f.
         0.000427741 "player.c:489" Connection 3: synced by first packet, seqno 26830.
         0.000039611 "player.c:173" Hammerton Decoder used on encrypted audio.
         0.000080889 "player.c:1136" Accepting packet 26830 with timestamp 2680608776. Lead time is 2.238594 seconds.
         0.000016408 "player.c:1214" Connection 3: Lead time for first frame 2680608776: 2.238594 seconds.
         0.000171629 "audio_alsa.c:1949" alsa: play() -- alsa_backend_state => abm_playing
         0.278263574 "rtp.c:771" clock synchronisation request: return time is    1.130 milliseconds.
         0.001125352 "player.c:1247" Change in estimated first_packet_time: 0.071906 milliseconds for first_packet.
         0.299148222 "rtp.c:771" clock synchronisation request: return time is    1.332 milliseconds.
         0.207375648 "mdns_avahi.c:510" dacp_monitor for "AD6ED84659016DE7"
         0.092460148 "rtp.c:771" clock synchronisation request: return time is    1.098 milliseconds.
         0.000886778 "player.c:1247" Change in estimated first_packet_time: -0.106585 milliseconds for first_packet.
         0.130734092 "rtp.c:468" New latency: 99036, sync latency: 88011, minimum latency: 0, maximum latency: 0, fixed offset: 11025, audio_backend_latency_offset: 0.000000.
         0.000015760 "rtp.c:513" AP1 control thread: set_ntp_anchor_info: rtptime: 2680554092, networktime: 1ea7ecb3a4847bdf, frame adjustment:   0.000.
         0.124978314 "rtsp.c:671" One active connection.
         0.000056704 "rtsp.c:5691" Connection 4: New connection from 192.168.50.123:43082 to self at 192.168.50.44:7000.
         0.001252482 "rtsp.c:1183" AP2 read result 0, for a request count of 262144.
         0.000028037 "rtsp.c:1298" Connection 4: Connection closed by client.
         0.000007389 "rtsp.c:2672" Connection 4: TEARDOWN unspecified stream connection.
         0.000005055 "rtsp.c:2739" Connection 4: TEARDOWN unspecified stream -- close the connection complete
         0.000004093 "rtsp.c:5114" Connection 4: terminating -- closing RTSP connection socket 19: from 192.168.50.123:43082 to self at 192.168.50.44:7000.
         0.000029666 "rtsp.c:5391" Connection 4: RTSP thread exit.
         0.120572315 "dacp.c:464" dacp_monitor_port_update_callback with Remote ID "AD6ED84659016DE7", target ID "AD6ED84659016DE7" and port number 3689.
         0.014372370 "dacp.c:623" metadata_store.dacp_server_active set to 1.
         0.000029167 "dacp.c:631" metadata_store.advanced_dacp_server_active set to 1.
         0.000465815 "dacp.c:464" dacp_monitor_port_update_callback with Remote ID "AD6ED84659016DE7", target ID "AD6ED84659016DE7" and port number 3689.
         0.005112315 "dacp.c:708" Play status is "paused".
         0.000024000 "dacp.c:729" Shuffle status is "off".
         0.000009759 "dacp.c:750" Repeat status is "none".
         0.000009204 "dacp.c:803" DACP Composite ID seen
         0.000012055 "dacp.c:817" Item composite ID changed to 0x00000001000000000000000200000007.
         0.000009426 "dacp.c:771" DACP Track Name seen
         0.000068889 "dacp.c:775" DACP Track Name set to: "The Lucky One"
         0.000015982 "dacp.c:779" DACP Artist Name seen
         0.000009222 "dacp.c:783" DACP Artist Name set to: "Alison Krauss & Union Station"
         0.000008833 "dacp.c:787" DACP Album Name seen
         0.000008611 "dacp.c:791" DACP Album Name set to: "Alison Krauss & Union Station: Live"
         0.000008704 "dacp.c:795" DACP Genre seen
         0.000008241 "dacp.c:798" DACP Genre set to: "Country"
         0.000008333 "dacp.c:825" DACP Song Time seen: "220960" of length 4.
         0.000008963 "dacp.c:830" DACP Song Time set to: "220960"
         0.724677777 "metadata_hub.c:587" MH Progress String set to: "2680593416/2680608776/2690353112"
         0.001858537 "mqtt.c:237" [MQTT]: publishing under shairport-sync/bad_dg/title
         0.000027186 "metadata_hub.c:531" MH Metadata stream processing start.
         0.000010222 "metadata_hub.c:360" MH Song Data Kind seen: "2" of length 1.
         0.000001167 "metadata_hub.c:366" MH Song Data Kind set to: "2"
         0.000015796 "metadata_hub.c:376" MH Item ID seen: "7" of length 8.
         0.000004500 "metadata_hub.c:381" MH Item ID set to: "7"
         0.000005852 "metadata_hub.c:466" MH Song Album Artist set to: "Alison Krauss & Union Station"
         0.000009908 "metadata_hub.c:387" MH Song Time seen: "220960" of length 4.
         0.000003518 "mqtt.c:237" [MQTT]: publishing under shairport-sync/bad_dg/track_id
```

A few things:
1. As mentioned, the line numbers are different. That's definitely odd.
2. There is nothing in your log from "metadata_hub.c" nor "dacp.c". Is that something significant or simply the result of trimming the log?
3. I'm using the ALSA back end, not the PulseAudio one, and that might turn out to be significant.

**Comment by aaronk6** [comment] 2024-12-02 20:08
The line number issue is weird, let’s see if they line up when I try this with the `mikebrady/shairport-sync:4.3.5` Docker image.

I’ll also try a plain setup with ALSA and without Docker on a Raspberry Pi to match what you did.

**Comment by aaronk6** [comment] 2024-12-02 21:43
Alright, last finding for today: The ALSA-based setup on my old Pi is working fine.

```
default metadata_pipename is "/tmp/shairport-sync-metadata".
>> Display Config Start.

From "uname -a":
 Linux test-pi 6.6.63-v8+ #1821 SMP PREEMPT Mon Nov 25 13:50:21 GMT 2024 aarch64 GNU/Linux

From /etc/os-release:
 Debian GNU/Linux 12 (bookworm)

From /sys/firmware/devicetree/base/model:
 Raspberry Pi 3 Model B Rev 1.2

Shairport Sync Version String:
 ahi-ALSA-jack-ao-soundio-soxr-metadata-mqtt-dbus-sysconfdir:/etc

Command Line:
 shairport-sync -X

Configuration File:
 /etc/shairport-sync.conf

Configuration File Settings:
 pw :
 {
 };
 mqtt :
 {
   enabled = "yes";
   hostname = "homeassistant.example.com";
   port = 1883;
   username = "shairport";
   password = "redacted";
   topic = "shairport-sync/test_pi";
   publish_raw = "no";
   publish_parsed = "yes";
   publish_cover = "no";
   enable_autodiscovery = "yes";
   enable_remote = "no";
 };
 diagnostics :
 {
   log_verbosity = 2;
 };

>> Display Config End.
>> Goodbye!
```

Next, I’ll try a fresh Docker setup with ALSA, and then switch it over to Pulse.

**Comment by mikebrady** [comment] 2024-12-02 22:30
Thanks for all your hard work!

**Comment by aaronk6** [comment] 2024-12-03 22:32
Here’s today’s update. Surprisingly, everything on the test system has worked fine so far, without reproducing the issue:

1. Docker + ALSA
2. Docker + Pulse
3. Docker with 2 Shairport Sync instances on the same host (based on this guide: https://github.com/noelhibbard/shairport-sync-docker)

(All with MQTT working fine, of course.)

Case 3 matches my production setup relatively closely, so it’s interesting that the issue does not occur. However, what is still different in production:

* The audio device is not the Pi’s internal audio, but an attached 8-channel USB sound card. Using Pulse’s remap-sink module, I create 4 stereo pairs for every room, and each of those is used by one Shairport Sync instance.
* Probably slightly older package versions (the OS version is also Bookworm though).

The soundcard setup is something I can’t easily replicate on the test system at the moment.

My next move will be setting the production Pi from scratch to ensure everything is up to date. I have an Ansible Playbook to do this, so it should be relatively straightforward. If the issue then still occurs, I will bring the test system closer to the production system—step by step—and see which change will make it fail.

**Comment by mikebrady** [comment] 2024-12-04 16:14
Thanks again. I just found a small (?) bug that could possibly cause a memory problem. No reported instances, but it might be worth updating on the `development` branch anyway.

**Comment by aaronk6** [comment] 2024-12-04 21:08
Thanks! I tried with the latest development Docker container (`4.3.6-dev-4-g7c57cc33-dirty-AirPlay2-smi10-alac-OpenSSL-Avahi-ALSA-pa-pw-dummy-stdout-pipe-soxr-convolution-metadata-mqtt-dbus-mpris-sysconfdir:/etc`) and can still reproduce the issue in my production setup. I’ll do a clean install next. I will use a new SD card and keep the old one—just in case it works and we want to compare the differences.

**Comment by aaronk6** [comment] 2024-12-04 22:14
OK, it is actually working on the new SD card! 🎉 I have set up the system from scratch using a fresh Raspberry Pi OS and my Ansible Playbook. Quite interesting. Maybe the old SD card was just bad. I heard that this can sometimes lead to weird errors that are hard to track down.

I’m wondering if it’s worth the effort to continue investigating this. From what I can tell, no one else had this issue. Should we maybe just close this issue and call it a day?

**Comment by mikebrady** [comment] 2024-12-05 08:37
Good stuff. Yeah, I think it's a good idea to close the issue.

Many thanks -- you've put a great deal of effort into this, and the cause of the issue  remains elusive. The thing is, if it remains a problem, it will emerge in some other way and we might be able to open a new issue and catch it then!

Thanks again, and feel free to close this issue.

**Comment by aaronk6** [comment] 2024-12-05 14:43
What’s a bit puzzling is that the SD card appears to be fine.

File system check:

```
parallels@ubuntu-linux-2404:~$ sudo fsck.ext4 /dev/sdc2
e2fsck 1.47.0 (5-Feb-2023)
rootfs: clean, 83864/451584 files, 1380246/1808384 blocks
```

Check for bad blocks:

```
parallels@ubuntu-linux-2404:~$ sudo badblocks -v /dev/sdc2
Checking blocks 0 to 7233535
Checking for bad blocks (read-only test): done                                                 
Pass completed, 0 bad blocks found. (0/0/0 errors)
```

I’m going to close the issue nevertheless, but I’m keeping the SD card, just in case.

Thanks for supporting me on this one! I think my main take-away is to move to a test system earlier when investigating such an issue. 🙂

**Closed** 2024-12-05 14:43 UTC
Labels: troubleshooting

**Comment by mikebrady** [comment] 2024-12-05 14:58
Thanks. Yeah -- the bug may still be there!
