### ISSUE TITLE
Long silence phases followed by short playing attempts than back to normal 

### ISSUE THREAD

**Issue by ste94pz** [mikebrady/shairport-sync#858] opened 2019-06-03 20:23 UTC
Hi Mike, first of all I wanna congratulate with you for your great work on this software.
I'm on Ubuntu 18.04 on a Minix Z83-4U with PulseAudio 12.2 running in system-mode and the latest shairport-sync compiled from git sources with this settings:
`--with-alsa --with-avahi --with-ssl=openssl --with-metadata --with-soxr --with-systemd --sysconfdir=/etc --with-pa --with-soundio --with-stdout --with-pipe --with-apple-alac --with-convolution --with-mqtt-client`
I can listen to about two songs without problems then I have a long silence phase followed by some audio chunks mixed with silence, then everything turns back to normal for other two or three songs. After that, the problem reappears. I always had this problem, even with older versions of shairport-sync and PulseAudio. The pc is connected to the router through gigabit ethernet and I'm streaming from an iPhone X connected through WiFi 5ghz AC near to the router. I have this problem with every AirPlay source, both iPhones and iTunes. [Here](https://github.com/mikebrady/shairport-sync/files/3249321/log.txt) you can find a piece of journal output when the probem appears.

Thank you in advance.
Stefano.

**Comment by mikebrady** [comment] 2019-06-04 12:02
Thanks for the post. Would you be kind enough to post a log of the very start, where you might see something like this:
```
pi@RaspberryPi3BP:~/shairport-sync $ ./shairport-sync -vu 
         0.020127619|Started!
         0.000275053|software version: "3.3-OpenSSL-Avahi-ALSA-soxr-metadata-dbus-sysconfdir:/etc"
         0.000038802|log verbosity is 1.
         0.000058178|stall_monitor_error_threshold is 0x33333333, with alsa_maximum_stall_time of 0.200000 sec.
         0.000136927|alsa: disable_standby_mode is "always".
         0.000043959|alsa: output device name is "hw:ALSA".
         0.000461772|disable resend requests is off.
         0.000103854|diagnostic_drop_packet_fraction is 0.000000. A value of 0.0 means no packets will be dropped deliberately.
         0.000121928|statistics_requester status is 0.
         0.000075573|rtsp listening port is 5000.
         0.000070000|udp base port is 6001.
         0.000067761|udp port range is 10.
         0.000069792|player name is "RaspberryPi3BP".
         0.000067865|backend is "(null)".
         0.000067760|run_this_before_play_begins action is "(null)".
         0.000069428|run_this_after_play_ends action is "(null)".
         0.000068958|wait-cmd status is 0.
         0.000066823|run_this_before_play_begins may return output is 0.
         0.000069688|run_this_if_an_unfixable_error_is_detected action is "(null)".
         0.000074063|run_this_before_entering_active_state action is  "(null)".
         0.000070313|run_this_after_exiting_active_state action is  "(null)".
         0.000069166|active_state_timeout is  10.000000 seconds.
         0.000107345|mdns backend "(null)".
         0.000067812|interpolation setting is "auto".
         0.000095521|interpolation soxr_delay_threshold is 30.
         0.000070261|resync time is 0.050000 seconds.
         0.000069532|allow a session to be interrupted: 0.
         0.000067916|busy timeout time is 120.
         0.000068282|drift tolerance is 0.001995 seconds.
         0.000087656|password is "(null)".
         0.000066980|ignore_volume_control is 0.
         0.000088542|volume_max_db is not set
         0.000067240|volume range in dB (zero means use the range specified by the mixer): 0.
         0.000070677|volume_range_combined_hardware_priority (1 means hardware mixer attenuation is used first) is 0.
         0.000071511|playback_mode is 0 (0-stereo, 1-mono, 1-reverse_stereo, 2-both_left, 3-both_right).
         0.000073281|disable_synchronization is 0.
         0.000067657|use_mmap_if_available is 1.
         0.000067031|output_format automatic selection is disabled.
         0.000071563|output_format is "U8".
         0.000066510|output_rate automatic selection is enabled.
         0.000067969|audio backend desired buffer length is 0.200000 seconds.
         0.000071199|audio_backend_buffer_interpolation_threshold_in_seconds is 0.120000 seconds.
         0.000073541|audio backend latency offset is 0.000000 seconds.
         0.000070834|audio backend silence lead-in time is -1.000000 seconds. A value -1.0 means use the default.
         0.000073282|zeroconf regtype is "_raop._tcp".
         0.000067083|decoders_supported field is 3.
         0.000067865|use_apple_decoder is 1.
         0.000068958|alsa_use_hardware_mute is 0.
         0.000067553|no special mdns service interface was requested.
         0.000101354|configuration file name "/etc/shairport-sync.conf" resolves to "/etc/shairport-sync.conf".
         0.000078386|metadata enabled is 1.
         0.000068906|metadata pipename is "/tmp/shairport-sync-metadata".
         0.000072605|metadata socket address is "(null)" port 0.
         0.000071250|metadata socket packet size is "500".
         0.000068854|get-coverart is 1.
         0.000067709|loudness is 0.
         0.000067552|loudness reference level is -20.000000
         0.005670905|alsa: output speed chosen is 44100.
         0.026473681|*warning: Could not acquire a Shairport Sync native D-Bus interface "org.gnome.ShairportSync.i873" on the system bus.
         0.814591394|avahi: service '2D11D6B582C4@RaspberryPi3BP' successfully added.
         0.658688938|"soxr" interpolation has been chosen.
        21.455195256|Connection 2: SETUP DACP-ID "900B806C3A8FAA81" from 192.168.2.1 to 192.168.2.36 with UDP ports Control: 6001, Timing: 6002 and Audio: 6003.

```

**Comment by ste94pz** [comment] 2019-06-04 18:40
Yes, of course. I post the [log](https://github.com/mikebrady/shairport-sync/files/3254013/log.txt) as a file because if I paste it here the eol characters aren't recognized, I don't know why.
Since we are here, do you know why it says "Failed to load cookie file from cookie: No such file or directory" at the beginning? I think it's something related with PulseAudio in system-mode.

**Comment by mikebrady** [comment] 2019-06-04 19:48
Thanks. I was interested to see if it was possible that the CPU wasn't fast enough to support `soxr` interpolation, but it certainly looks like it is, so that's not a problem.

Since the device is connected over wired Ethernet, WiFi can't be a problem.

Of course, the possibility is that there is some problem with PulseAudio. To see if that might be the case, would it be possible to direct the output to the ALSA backend, even temporarily.

If you run `$ shairport-sync -h` from the command line, you should get a list of the ALSA hardware devices, e.g:
```
...
Settings and options for the audio backend "alsa":
    -d output-device    set the output device, default is "default".
    -c mixer-control    set the mixer control name, default is to use no mixer.
    -m mixer-device     set the mixer device, default is the output device.
    -i mixer-index      set the mixer index, default is 0.
    hardware output devices:
      "hw:ALSA"
      "hw:IQaudIODAC"
...
```
If the problem persisted with the ALSA backend, then it is hardly likely that it's a PulseAudio problem. However, if the problem disappears, then it might be something to do with PulseAudio.

Other possibilities might be something odd about your network, or maybe the CPU or the network gets extremely busy from time to time. At the iPhone/WiFi end, is it possible that there is a common local source of interference, e.g. a microwave oven? (This should not be a problem at 5GHz, TBH.)

**Comment by ste94pz** [comment] 2019-06-04 20:51
It's a minipc that I use as a home-server always on without the ui (I switch to only terminal mode with "sudo systemctl isolate multi-user.target"). When I need to use it as a normal pc, I start the ui with "sudo systemctl isolate graphical.target". The problem appears both in graphical and terminal mode. I use PulseAudio in system-mode because I need that multiple programs can access to the sound card and even when my user isn't logged in (when I don't use the pc, so in non-logged terminal mode, like an headless server). I don't know about the interferences, I don't have a microwave oven, I have around 11-12 wifi devices connected at 2.4ghz and 5ghz, and I have this problem with every device. I'll try to switch to ALSA and I'll let you know. Do you know if I can log some infos from PulseAudio?

**Comment by mikebrady** [comment] 2019-06-04 21:01
That's interesting alright, and I can see the need for multiple access to the sound card. If it's not too difficult to switch temporarily over to ALSA, it should be possible to tell pretty quickly if the problem persists.

Regarding PulseAudio, I'm afraid I have no real knowledge of it – it seems to be a huge system.

**Comment by mikebrady** [comment] 2019-06-04 21:09
There is nothing in the logs that looks alarming, just that, periodically and for some reason, the output falls far behind the input.

**Comment by mikebrady** [comment] 2019-06-05 10:31
On the subject of sharing the audio output device, on Ubuntu 19.04 and maybe on recent versions such as 18.04 and 18.10, the ALSA device called `default` permits sharing. This is the ALSA device that Shairport Sync will output to if you don't enter any output device information. It's not ideal, since Shairport Sync works best with a real hardware device, but it might work better than using PulseAudio – worth a try, certainly.

**Comment by bedrin** [comment] 2019-06-21 20:51
I've similar issue - silence for some time followed by few hiccups and then it returns back to normal. Happens probably once per 15 minutes or something.

I'm running Ubuntu 18.04 LTS but compiled Shairport manually (from tag 3.3.1, without soxr).
It's old EEE PC 901 with x32 Intel Atom N270 1600Mhz

Here's what I have in log files:
```
июн 21 23:33:12 eeepc shairport-sync[11693]:          2.010636003|RTSP Message Received: "OPTIONS * RTSP/1.0".
июн 21 23:33:12 eeepc shairport-sync[11693]:          0.000232844|    CSeq: 518.
июн 21 23:33:12 eeepc shairport-sync[11693]:          0.000141285|    DACP-ID: 4227CA30BF956875.
июн 21 23:33:12 eeepc shairport-sync[11693]:          0.000098892|    Active-Remote: 359134575.
июн 21 23:33:12 eeepc shairport-sync[11693]:          0.000097147|    User-Agent: AirPlay/383.1.3.
июн 21 23:33:12 eeepc shairport-sync[11693]:          0.000105387|Connection 1: Received an RTSP Packet of type "OPTIONS":
июн 21 23:33:12 eeepc shairport-sync[11693]:          0.000093376|  Type: "CSeq", content: "518"
июн 21 23:33:12 eeepc shairport-sync[11693]:          0.000091349|  Type: "DACP-ID", content: "4227CA30BF956875"
июн 21 23:33:12 eeepc shairport-sync[11693]:          0.000089953|  Type: "Active-Remote", content: "359134575"
июн 21 23:33:12 eeepc shairport-sync[11693]:          0.000090372|  Type: "User-Agent", content: "AirPlay/383.1.3"
июн 21 23:33:12 eeepc shairport-sync[11693]:          0.000101058|Connection 1: OPTIONS
июн 21 23:33:12 eeepc shairport-sync[11693]:          0.000093585|Connection 1: RTSP Response:
июн 21 23:33:12 eeepc shairport-sync[11693]:          0.000090442|  Type: "CSeq", content: "518"
июн 21 23:33:12 eeepc shairport-sync[11693]:          0.000091280|  Type: "Server", content: "AirTunes/105.1"
июн 21 23:33:12 eeepc shairport-sync[11693]:          0.000091838|  Type: "Public", content: "ANNOUNCE, SETUP, RECORD, PAUSE, FLUSH, TEARDOWN, OPTIONS, GET_PARAMETER, SET
июн 21 23:33:13 eeepc shairport-sync[11693]:          0.362248822|Large negative sync error: -4294967382 with should_be_frame_32 of 1357, nt of 4294889031 and current_del
июн 21 23:33:13 eeepc shairport-sync[11693]:          0.004010173|Play a silence of 11025 frames.
июн 21 23:33:13 eeepc shairport-sync[11693]:          0.143091113|Player: packets out of sequence: expected: 8474, got: 8483, with ab_read: 8484 and ab_write: 8715.
июн 21 23:33:13 eeepc shairport-sync[11693]:          0.034861619|Large negative sync error: -4294956706 with should_be_frame_32 of 9382, nt of 4294893607 and current_del
июн 21 23:33:13 eeepc shairport-sync[11693]:          0.003022157|Play a silence of 11025 frames.
июн 21 23:33:13 eeepc shairport-sync[11693]:          0.310435252|Player: packets out of sequence: expected: 8487, got: 8496, with ab_read: 8497 and ab_write: 8759.
июн 21 23:33:13 eeepc shairport-sync[11693]:          0.023260053|Large negative sync error: -4294946030 with should_be_frame_32 of 24230, nt of 4294898183 and current_de
июн 21 23:33:13 eeepc shairport-sync[11693]:          0.003850730|Play a silence of 11025 frames.
июн 21 23:33:14 eeepc shairport-sync[11693]:          0.321197847|Player: packets out of sequence: expected: 8500, got: 8509, with ab_read: 8510 and ab_write: 8802.
июн 21 23:33:14 eeepc shairport-sync[11693]:          0.023262289|Large negative sync error: -4294935353 with should_be_frame_32 of 39591, nt of 4294902759 and current_de
июн 21 23:33:14 eeepc shairport-sync[11693]:          0.003651898|Play a silence of 11025 frames.
июн 21 23:33:14 eeepc shairport-sync[11693]:          0.309835353|Player: packets out of sequence: expected: 8513, got: 8522, with ab_read: 8523 and ab_write: 8843.
июн 21 23:33:14 eeepc shairport-sync[11693]:          0.034766012|Large negative sync error: -4294924679 with should_be_frame_32 of 54949, nt of 4294907335 and current_de
июн 21 23:33:14 eeepc shairport-sync[11693]:          0.003284753|Play a silence of 11025 frames.
июн 21 23:33:14 eeepc shairport-sync[11693]:          0.310203825|Player: packets out of sequence: expected: 8526, got: 8535, with ab_read: 8536 and ab_write: 8889.
июн 21 23:33:14 eeepc shairport-sync[11693]:          0.023267248|Large negative sync error: -4294914007 with should_be_frame_32 of 69801, nt of 4294911911 and current_de
июн 21 23:33:14 eeepc shairport-sync[11693]:          0.001906334|Play a silence of 11025 frames.
июн 21 23:33:14 eeepc shairport-sync[11693]:          0.090080427|RTSP Message Received: "OPTIONS * RTSP/1.0".
июн 21 23:33:14 eeepc shairport-sync[11693]:          0.000130320|    CSeq: 519.
июн 21 23:33:14 eeepc shairport-sync[11693]:          0.000290182|    DACP-ID: 4227CA30BF956875.
июн 21 23:33:14 eeepc shairport-sync[11693]:          0.000074100|    Active-Remote: 359134575.
июн 21 23:33:14 eeepc shairport-sync[11693]:          0.000087997|    User-Agent: AirPlay/383.1.3.
июн 21 23:33:14 eeepc shairport-sync[11693]:          0.000058805|Connection 1: Received an RTSP Packet of type "OPTIONS":
июн 21 23:33:14 eeepc shairport-sync[11693]:          0.000046094|  Type: "CSeq", content: "519"
июн 21 23:33:14 eeepc shairport-sync[11693]:          0.000044697|  Type: "DACP-ID", content: "4227CA30BF956875"
июн 21 23:33:14 eeepc shairport-sync[11693]:          0.000046303|  Type: "Active-Remote", content: "359134575"
июн 21 23:33:14 eeepc shairport-sync[11693]:          0.000045117|  Type: "User-Agent", content: "AirPlay/383.1.3"
июн 21 23:33:14 eeepc shairport-sync[11693]:          0.000052658|Connection 1: OPTIONS
июн 21 23:33:14 eeepc shairport-sync[11693]:          0.000048399|Connection 1: RTSP Response:
июн 21 23:33:14 eeepc shairport-sync[11693]:          0.000045046|  Type: "CSeq", content: "519"
июн 21 23:33:14 eeepc shairport-sync[11693]:          0.000048469|  Type: "Server", content: "AirTunes/105.1"
июн 21 23:33:14 eeepc shairport-sync[11693]:          0.000048608|  Type: "Public", content: "ANNOUNCE, SETUP, RECORD, PAUSE, FLUSH, TEARDOWN, OPTIONS, GET_PARAMETER, SET
июн 21 23:33:15 eeepc shairport-sync[11693]:          0.231900621|Player: packets out of sequence: expected: 8539, got: 8548, with ab_read: 8549 and ab_write: 8930.
июн 21 23:33:15 eeepc shairport-sync[11693]:          0.023251396|Large negative sync error: -4294903327 with should_be_frame_32 of 85157, nt of 4294916487 and current_de
июн 21 23:33:15 eeepc shairport-sync[11693]:          0.001924981|Play a silence of 11025 frames.
июн 21 23:33:15 eeepc shairport-sync[11693]:          0.323235235|Player: packets out of sequence: expected: 8552, got: 8561, with ab_read: 8562 and ab_write: 8977.
июн 21 23:33:15 eeepc shairport-sync[11693]:          0.023126593|Large negative sync error: -4294892652 with should_be_frame_32 of 100516, nt of 4294921063 and current_d
июн 21 23:33:15 eeepc shairport-sync[11693]:          0.001870297|Play a silence of 11025 frames.
июн 21 23:33:15 eeepc shairport-sync[11693]:          0.323196823|Player: packets out of sequence: expected: 8565, got: 8574, with ab_read: 8575 and ab_write: 9017.
июн 21 23:33:15 eeepc shairport-sync[11693]:          0.023192870|Large negative sync error: -4294881978 with should_be_frame_32 of 115874, nt of 4294925639 and current_d
июн 21 23:33:15 eeepc shairport-sync[11693]:          0.001943349|Play a silence of 11025 frames.
июн 21 23:33:16 eeepc shairport-sync[11693]:          0.311629487|Player: packets out of sequence: expected: 8578, got: 8587, with ab_read: 8588 and ab_write: 9061.
июн 21 23:33:16 eeepc shairport-sync[11693]:          0.034744506|Large negative sync error: -4294871302 with should_be_frame_32 of 131234, nt of 4294930215 and current_d
июн 21 23:33:16 eeepc shairport-sync[11693]:          0.002880802|Play a silence of 11025 frames.
июн 21 23:33:16 eeepc shairport-sync[11693]:          0.310682475|Player: packets out of sequence: expected: 8591, got: 8600, with ab_read: 8601 and ab_write: 9105.
июн 21 23:33:16 eeepc shairport-sync[11693]:          0.023229608|Large negative sync error: -4294860629 with should_be_frame_32 of 146087, nt of 4294934791 and current_d
июн 21 23:33:16 eeepc shairport-sync[11693]:          0.002819343|Play a silence of 11025 frames.
июн 21 23:33:16 eeepc shairport-sync[11693]:          0.322016909|Player: packets out of sequence: expected: 8604, got: 8613, with ab_read: 8614 and ab_write: 9148.
июн 21 23:33:16 eeepc shairport-sync[11693]:          0.023377178|Large negative sync error: -4294849949 with should_be_frame_32 of 161443, nt of 4294939367 and current_d
июн 21 23:33:16 eeepc shairport-sync[11693]:          0.003703929|Play a silence of 11025 frames.
```

...

```
июн 21 23:33:18 eeepc shairport-sync[11693]:          0.000092537|Connection 1: RTSP Response:
июн 21 23:33:18 eeepc shairport-sync[11693]:          0.000085065|  Type: "CSeq", content: "521"
июн 21 23:33:18 eeepc shairport-sync[11693]:          0.000085274|  Type: "Server", content: "AirTunes/105.1"
июн 21 23:33:18 eeepc shairport-sync[11693]:          0.000089464|  Type: "Public", content: "ANNOUNCE, SETUP, RECORD, PAUSE, FLUSH, TEARDOWN, OPTIONS, GET_PARAMETER, SET
июн 21 23:33:18 eeepc shairport-sync[11693]:          0.013632009|Large negative sync error: -4294785902 with should_be_frame_32 of 253082, nt of 4294966823 and current_d
июн 21 23:33:18 eeepc shairport-sync[11693]:          0.002475456|Play a silence of 11025 frames.
июн 21 23:33:19 eeepc shairport-sync[11693]:          0.322596427|Player: packets out of sequence: expected: 8695, got: 8704, with ab_read: 8705 and ab_write: 9454.
июн 21 23:33:19 eeepc shairport-sync[11693]:          0.023184286|Large positive sync error: 192061.
июн 21 23:33:19 eeepc shairport-sync[11693]:          0.000162516|mutex_lock "&conn->flush_mutex" at "player.c:2243".
июн 21 23:33:19 eeepc shairport-sync[11693]:          0.000116632|mutex_unlock "&conn->flush_mutex" at "player.c:2248".
июн 21 23:33:19 eeepc shairport-sync[11693]:          0.000104410|Dropping flushed packet in buffer_get_frame, seqno 8708, timestamp 4455, flushing to timestamp: 196164. 
июн 21 23:33:19 eeepc shairport-sync[11693]:          0.000103990|Dropping flushed packet in buffer_get_frame, seqno 8709, timestamp 4807, flushing to timestamp: 196164. 
июн 21 23:33:19 eeepc shairport-sync[11693]:          0.000100918|Dropping flushed packet in buffer_get_frame, seqno 8710, timestamp 5159, flushing to timestamp: 196164. 
июн 21 23:33:19 eeepc shairport-sync[11693]:          0.000109369|Dropping flushed packet in buffer_get_frame, seqno 8711, timestamp 5511, flushing to timestamp: 196164. 
июн 21 23:33:19 eeepc shairport-sync[11693]:          0.000103571|Dropping flushed packet in buffer_get_frame, seqno 8712, timestamp 5863, flushing to timestamp: 196164.
```

...

```
июн 21 23:33:19 eeepc shairport-sync[11693]:          0.000050563|Dropping flushed packet in buffer_get_frame, seqno 9251, timestamp 195591, flushing to timestamp: 196164
июн 21 23:33:19 eeepc shairport-sync[11693]:          0.000054475|Dropping flushed packet in buffer_get_frame, seqno 9252, timestamp 195943, flushing to timestamp: 196164
июн 21 23:33:19 eeepc shairport-sync[11693]:          0.048271834|Player: packets out of sequence: expected: 8708, got: 9262, with ab_read: 9263 and ab_write: 9484.
июн 21 23:33:19 eeepc shairport-sync[11693]:          0.118527975|Dropping flush request in buffer_get_frame
июн 21 23:33:20 eeepc shairport-sync[11693]:          0.751586135|-6991054.81,     283.2,     305.9,      123369,     93,    489,      0,    477,   8467,  218,  749,   44
июн 21 23:33:20 eeepc shairport-sync[11693]:          0.539889766|RTSP Message Received: "OPTIONS * RTSP/1.0".
июн 21 23:33:20 eeepc shairport-sync[11693]:          0.000178021|    CSeq: 522.
июн 21 23:33:20 eeepc shairport-sync[11693]:          0.000112791|    DACP-ID: 4227CA30BF956875.
июн 21 23:33:20 eeepc shairport-sync[11693]:          0.000101895|    Active-Remote: 359134575.
июн 21 23:33:20 eeepc shairport-sync[11693]:          0.000095610|    User-Agent: AirPlay/383.1.3.
июн 21 23:33:20 eeepc shairport-sync[11693]:          0.000100010|Connection 1: Received an RTSP Packet of type "OPTIONS":
июн 21 23:33:20 eeepc shairport-sync[11693]:          0.000094004|  Type: "CSeq", content: "522"
июн 21 23:33:20 eeepc shairport-sync[11693]:          0.000089394|  Type: "DACP-ID", content: "4227CA30BF956875"
июн 21 23:33:20 eeepc shairport-sync[11693]:          0.000090023|  Type: "Active-Remote", content: "359134575"
июн 21 23:33:20 eeepc shairport-sync[11693]:          0.000095191|  Type: "User-Agent", content: "AirPlay/383.1.3"
июн 21 23:33:20 eeepc shairport-sync[11693]:          0.000102175|Connection 1: OPTIONS
```

This is my config:

```
general = {
 name = "Marshall";
 statistics = "yes";
 log_verbosity = 3;
 interface = "wlp1s0";
};

sessioncontrol = {
 allow_session_interruption = "yes";
};

alsa = {
  output_device = "hw:0";
};
```

Tried a few versions but all give the same results.
Any ideas what to try next? Appreciate any input!

**Comment by bedrin** [comment] 2019-06-21 21:35
So far it looks good after disabling Wi-Fi power saving as described in https://github.com/mikebrady/shairport-sync/blob/master/TROUBLESHOOTING.md

Stupid me - didn't read the instructions properly :(

Probably worth adding some kind of self-diagnostic either with printing to log (without enabling super verbosity) or even on install.

**Comment by mikebrady** [comment] 2019-06-21 21:46
No bother, thanks, and hopefully the problem is solved.

**Comment by mikebrady** [comment] 2019-10-27 10:30
Thanks for this contribution. Closing the issue. Please open a new one if necessary.

**Closed by mikebrady** 2019-10-27 10:30 UTC
Labels: resolved, troubleshooting
