### ISSUE TITLE
Compilation on Cygwin

### ISSUE THREAD

**Issue by sgielen** [mikebrady/shairport-sync#147] opened 2015-10-19 15:04 UTC
I tried compiling Shairport Sync on Cygwin, and got it working pretty quickly. The only change to the source code needed was to have COMPILE_FOR_LINUX_AND_FREEBSD set to 1 in `common.h` (you can use the `__CYGWIN__` define to check for the platform).

Dependencies in Cygwin are pkg-config, autoconf, autoconf2.5, automake, clang, libdaemon-devel, popt-devel, make, libao-devel, libssl-devel.

Libconfig is not in Cygwin yet, so it has to be compiled from http://www.hyperrealm.com/libconfig/; I used the default installation path of `/usr/local`, then compiled shairport-sync using:

```
PKG_CONFIG_PATH=/usr/local/lib/pkgconfig ./configure --with-ao --with-ssl=openssl
make install
```

After this, `shairport-sync` worked immediately. This can be added to README as soon as the #define is set correctly :)

**Comment by mikebrady** [comment] 2015-10-20 09:18
Thanks very much for this work! I'll try to get to that change in the next few days...

**Comment by mikebrady** [comment] 2015-10-21 09:27
I just put a check for that flag in the `development` branch. It's not yet a release, but it's at HEAD. Would you be kind enough to check that it does the trick please?

**Comment by noelhibbard** [comment] 2015-10-21 14:49
sgielen, I don't have much experience with cygwin but I gave this a shot yesterday and can't get libconfig to compile in cygwin so I can't go much farther.

I get this when configuring libconfig:
configure: error: C++ preprocessor "/lib/cpp" fails sanity check

Any ideas?

**Comment by sgielen** [comment] 2015-10-22 01:37
>  configure: error: C++ preprocessor "/lib/cpp" fails sanity check

My configure succeeds without error, after only installing the 'clang' dependency, which seemed to pull in gcc as well. FYI, I get a line saying `checking how to run the C preprocessor... gcc -E`. My `cpp` binary is at `/bin/cpp`. Does this help?

**Comment by sgielen** [comment] 2015-10-22 01:44
> I just put a check for that flag in the `development` branch. It's not yet a release, but it's at HEAD. Would you be kind enough to check that it does the trick please?

Yes! On `development` HEAD (07c3993) `shairport-sync.exe` is created and working well after installing libconfig manually and using the following commands:

```
autoreconf -if
PKG_CONFIG_PATH=/usr/local/lib/pkgconfig ./configure --with-ao --with-ssl=openssl --with-tinysvcmdns
make
./shairport-sync.exe
```

For future reference, `--with-pulseaudio` also builds but I don't have a pulseaudio server installed to test against. `--with-alsa` doesn't build, obviously, because Windows doesn't provide ALSA interfaces. Without `--with-tinysvcmdns` there is no mDNS support; I haven't checked avahi because it needs the daemon as well.

**Comment by mikebrady** [comment] 2015-10-22 06:38
Many thanks for that and for the extra information.

**Comment by mikebrady** [comment] 2015-10-30 17:05
I can confirm that I got this working on Cygwin running inside Window 10 64 bit.

**Comment by rkam** [comment] 2015-10-30 18:55
I can't get this to configure on Windows 7.  Any ideas?  (like, is it known to not work there?)

[ autoconf -if  gives:  configure.ac:54 error: possibly undefined macro: AC_DEFINE ... ]

Otherwise, I think it might have to do with the versions of the dependancies.  Can you provide me with which versions of these you are using?  (I am at the latest version for all of them)

pkg-config, autoconf, autoconf2.5, automake, clang, libdaemon-devel, popt-devel, make, libao-devel, libssl-devel

Thanks.

**Comment by mikebrady** [comment] 2015-10-30 19:18
Yeah, install `libtool`!

**Comment by mikebrady** [comment] 2015-10-30 19:20
(Sorry, I actually updated my comment previous to yours with a list of the dependencies I used.)

**Comment by rkam** [comment] 2015-10-31 00:36
I had libtool - I missed adding it to the list when I posted.

So, I started from scratch and it built just fine and it works on Windows 7, 64-bit.
I must have had something misconfigured or missing or something else. Sorry about that.

I am having sync issues though vs. the one running on my Raspberry PI (it's running behind on windows) -- I'll play around with it.

[I have the rPI connected to room speakers and win connected to (much better) desktop speakers]

**Comment by mikebrady** [comment] 2015-10-31 00:49
That's good to hear. But remember that the output from Shairport Sync on Cygwin won't be synchronized....

**Comment by mikebrady** [comment] 2015-10-31 14:07
I just added two settings to the "ao" back end to allow you to set the buffer size but also to add a positive or negative offset to the delay – it might help to – at least – start the Cygwin playback at the same time as the rPi. Still not synchronised, of course. They are the same as those used the "stdout" stanza. Documentation not updated yet.

**Comment by noelhibbard** [comment] 2015-11-03 19:38
I scrapped my install of cygwin and reinstalled using only the dependencies in Mike's post. This time I used the x64 build of cygwin. Not sure if that was part of my problem before or not (I don't think so). This time I was able to compile libconfig without a problem and then also compiled shairport-sync without a problem. The only problem I am having now is it isn't advertizing for some reason. I used --with-tinysvcmdns. Is there some other mDNS dependency I need to install or compile for cygwin?

**Comment by noelhibbard** [comment] 2015-11-03 19:49
Nevermind.. I figured it out. It's advertizing on my VirtualBox NIC so it isn't actually exposed to my network.

**Comment by mikebrady** [comment] 2015-11-03 22:33
Good stuff.

**Comment by mikebrady** [comment] 2016-02-01 12:27
Closing this, as the necessary changes have been made part of stable release 2.8.0.

**Comment by lordbarba** [comment] 2016-02-12 09:56
Hi All, 
i've tried everything but i was not able to build Shairport-sync under cygwin. May someone send me the compiled exe, please?

Thanks in advance
Leonardo

**Comment by mikebrady** [comment] 2016-02-12 10:08
Hi Leonardo. I just checked again with the latest Shairport Sync and it's building fine for me in Cygwin running in Windows 10 x64.

**Comment by lordbarba** [comment] 2016-02-12 10:55
Ok, at that point, I think i have a wrong cygwin installation. I'm a newbie to Cygwin.
Is there a step-by-step tutorial how to compile it?

Thanks
Leo

**Comment by mikebrady** [comment] 2016-02-12 11:06
There isn't a Cygwin guide, I'm afraid. But look at @sgielen's comments in this thread, but install the dependencies I listed. It should then be straightforward.

**Comment by lordbarba** [comment] 2016-02-12 11:10
Ok, 
I'm missing:
openssl-devel
libao-devel
popt-devel
libdaemon-devel

Is there particular version i have to install?

**Comment by lordbarba** [comment] 2016-02-12 13:42
FYI, 
I've solved all previous issue. Now problem is on LibConfig.
I've tried several version, but none of them work

```
configure: error: Package requirements (libconfig) were not met:
No package 'libconfig' found
```

This is the "which libconfig" output
```
$ which libconfig
which: no libconfig in (/usr/local/bin:/usr/bin:/cygdrive/c/Program Files (x86)/Intel/iCLS Client:/cygdrive/c/Program Files/Intel/iCLS Client:/cygdrive/c/Program Files (x86)/NVIDIA Corporation/PhysX/Common:/cygdrive/c/WINDOWS/system32:/cygdrive/c/WINDOWS:/cygdrive/c/WINDOWS/System32/Wbem:/cygdrive/c/WINDOWS/System32/WindowsPowerShell/v1.0:/cygdrive/c/Program Files/Intel/Intel(R) Management Engine Components/DAL:/cygdrive/c/Program Files (x86)/Intel/Intel(R) Management Engine Components/DAL:/cygdrive/c/Program Files/Intel/Intel(R) Management Engine Components/IPT:/cygdrive/c/Program Files (x86)/Intel/Intel(R) Management Engine Components/IPT:/cygdrive/c/Program Files/Intel/WiFi/bin:/cygdrive/c/Program Files/Common Files/Intel/WirelessCommon:/cygdrive/c/Program Files/Hewlett-Packard/SimplePass:/cygdrive/c/Program Files (x86)/Microsoft SQL Server/90/Tools/binn:/cygdrive/c/Program Files/Microsoft SQL Server/110/Tools/Binn:/cygdrive/c/Program Files (x86)/Microsoft SDKs/TypeScript/1.0:/cygdrive/c/Program Files/Microsoft SQL Server/120/Tools/Binn:/cygdrive/c/Program Files (x86)/GtkSharp/2.12/bin:/cygdrive/c/Users/envy/.dnx/bin:/cygdrive/c/Program Files/Microsoft DNX/Dnvm:/cygdrive/c/Program Files (x86)/nodejs:/cygdrive/c/Java64/bin:/cygdrive/c/Program Files (x86)/IDM Computer Solutions/UltraEdit:/cygdrive/c/Program Files (x86)/Windows Kits/10/Windows Performance Toolkit:/cygdrive/c/Users/envy/AppData/Roaming/npm:/cygdrive/c/Program Files (x86)/IDM Computer Solutions/UltraCompare:/usr/lib/lapack)

```

**Comment by mikebrady** [comment] 2016-02-12 15:25
You have to compile, make and install libconfig – see the first post and https://github.com/mikebrady/shairport-sync/issues/147#issuecomment-152588219

**Comment by mikebrady** [comment] 2016-02-12 22:19
Hi there. I just put up a rough guide at https://github.com/mikebrady/shairport-sync/blob/development/CYGWIN.md.

**Comment by lordbarba** [comment] 2016-02-12 22:33
You're great!!
I will try as i will go back to office and give you an update.
Thank you so much for your really kindly help!!

Leo

**Comment by joaodriessen** [comment] 2017-02-26 12:13
the guide works!

I have a "shairport-sync.exe" in my build directory, only I don't really know what to do with it. opening it in windows spits out that I don't have cygao-4.dll cygcrypto-1.0.0.dll cygwin1.dll cygdaemon-o.dll installed.
running it from a cygwin shell works though.

Output of "./shairport-sync.exe": 
Successful Startup
Could not establish mDNS advertisement!

is the mDNS error something that will prevent it from working properly?

How to I set it up to run at startup with my windows pc? and where do I locate the configuration options?

bloody brilliant app on linux! hope to get it up and running on my pc too.

**Comment by noelhibbard** [comment] 2017-02-28 20:36
If you don't want to run it within the cygwin shell then you need to make sure you have all those dlls in the same folder as shairport-sync or in your path somewhere. Here is a list of the needed dlls for shairport-sync to run:
cygao-4.dll
cygconfig-9.dll
cygcrypto-1.0.0.dll
cygdaemon-0.dll
cygiconv-2.dll
cygintl-8.dll
cygpopt-0.dll
cygwin1.dll
cygz.dll

If I remember correctly you need to use the --with-tinysvcmdns config option or else it defaults to Avahi which isn't available under cygwin. On my build I used these options:
./configure --with-stdout --with-pipe --with-tinysvcmdns --with-ssl=openssl --with-metadata --with-ao

--with-stdout, --with-pipe and --with-metadata are optional.

**Comment by mikebrady** [comment] 2017-03-01 13:31
Thanks @noelhibbard. Would that information be worth adding to the guide?

**Comment by joaodriessen** [comment] 2017-03-09 13:41
I would humbly suggest a fool proof guide to getting shairport-sync up and running on a windows PC (including customising it, running at startup etc.)
Besides that, there really is no reliable free alternative to this software and I believe integrating into some kind of windows app would be incredibly useful.

**Comment by mikebrady** [comment] 2017-03-12 15:44
Hello again @noelhibbard. I'm adding your fixes to the CYGWIN guide. If you stay inside the CYGWIN environment, what command and options do you use to actually run `shairport-sync.exe`?

**Comment by noelhibbard** [comment] 2017-03-13 18:07
Typically I the only option I supply is -c to point to a config file. I am compiling the dev branch right now to see if your code cleanup fixed the crashes I was having. When it is done compiling I will come back with all the details on what is needed to get it to run in and out of the cygwin shell.

**Comment by OneBobone** [comment] 2019-02-04 20:43
Managed to follow the guide and install on Win7 32bit.
Works nicely!
My remaining issue is how to address the channels on a 7.1 sound card from Attero? Currently getting the first pair, which is occupied...
Any ideas?

**Comment by mikebrady** [comment] 2019-10-08 11:27
Closing this due to inactivity.  Feel free to open a new issue.

**Closed by mikebrady** 2019-10-08 11:27 UTC
Labels: enhancement
