### ISSUE TITLE
Problem with setting mixer on Raspberry Pi 3

### ISSUE THREAD

**Issue by yetanotherman** [mikebrady/shairport-sync#503] opened 2017-04-01 13:55 UTC
Another problem - not related to attenuator, appeared at 3.x.x version.

In configuration where I run sound to Raspberry Pi 3 native "audio interface" and use its "mixer", it sometimes stop playing when I change volume on my MacBook Air (running macOs Sierra). Playback resumes after restarting shairport-sync. I see the following message in log when it happens:

Mar 31 17:35:20 kitchenpi shairport-sync[9681]: Failed to set playback dB volume

**Comment by mikebrady** [comment] 2017-04-01 14:12
That's interesting. When the condition that gives rise to this error is detected, Shairport Sync terminates by design. It seems from your report that perhaps the "mixer" reports some kind of error. So, I'll stop Shairport Sync terminating in that case and instead have it log a debug message.

**Comment by yetanotherman** [comment] 2017-04-01 14:24
Well, it is not terminating, I mean, the process is still there, but it says that it is in use when I try to reconnect - and no timeout happens

**Comment by mikebrady** [comment] 2017-04-01 14:25
I've just pushed that change onto the development branch. Can you access it at HEAD using GIT, or does it need to be a release?

**Comment by yetanotherman** [comment] 2017-04-01 14:27
No problem, I'll re-compile from HEAD

**Comment by mikebrady** [comment] 2019-10-24 10:03
Thanks for this contribution. Closing the issue. Please open a new one if necessary.

**Closed by mikebrady** 2019-10-24 10:03 UTC
